################################################################################
# Discovered & Registered Dynamic Services
################################################################################

services:
  - name: "hello.greet"
    script: "src/testapp/serv/greet.php"
    method: "POST"
