<?php
namespace App\ptable\Serv;

class PeriodicTableData
{
    public static function getElements(): array
    {
        return [
            ['atomic' => 1, 'symbol' => 'H', 'name' => 'Hydrogen', 'group' => 1, 'period' => 1, 'category' => 'nonmetal', 'mass' => '1.008'],
            ['atomic' => 2, 'symbol' => 'He', 'name' => 'Helium', 'group' => 18, 'period' => 1, 'category' => 'noble-gas', 'mass' => '4.0026'],
            ['atomic' => 3, 'symbol' => 'Li', 'name' => 'Lithium', 'group' => 1, 'period' => 2, 'category' => 'alkali-metal', 'mass' => '6.94'],
            ['atomic' => 4, 'symbol' => 'Be', 'name' => 'Beryllium', 'group' => 2, 'period' => 2, 'category' => 'alkaline-earth-metal', 'mass' => '9.0122'],
            ['atomic' => 5, 'symbol' => 'B', 'name' => 'Boron', 'group' => 13, 'period' => 2, 'category' => 'metalloid', 'mass' => '10.81'],
            ['atomic' => 6, 'symbol' => 'C', 'name' => 'Carbon', 'group' => 14, 'period' => 2, 'category' => 'nonmetal', 'mass' => '12.011'],
            ['atomic' => 7, 'symbol' => 'N', 'name' => 'Nitrogen', 'group' => 15, 'period' => 2, 'category' => 'nonmetal', 'mass' => '14.007'],
            ['atomic' => 8, 'symbol' => 'O', 'name' => 'Oxygen', 'group' => 16, 'period' => 2, 'category' => 'nonmetal', 'mass' => '15.999'],
            ['atomic' => 9, 'symbol' => 'F', 'name' => 'Fluorine', 'group' => 17, 'period' => 2, 'category' => 'halogen', 'mass' => '18.998'],
            ['atomic' => 10, 'symbol' => 'Ne', 'name' => 'Neon', 'group' => 18, 'period' => 2, 'category' => 'noble-gas', 'mass' => '20.180'],
            ['atomic' => 11, 'symbol' => 'Na', 'name' => 'Sodium', 'group' => 1, 'period' => 3, 'category' => 'alkali-metal', 'mass' => '22.990'],
            ['atomic' => 12, 'symbol' => 'Mg', 'name' => 'Magnesium', 'group' => 2, 'period' => 3, 'category' => 'alkaline-earth-metal', 'mass' => '24.305'],
            ['atomic' => 13, 'symbol' => 'Al', 'name' => 'Aluminum', 'group' => 13, 'period' => 3, 'category' => 'post-transition-metal', 'mass' => '26.982'],
            ['atomic' => 14, 'symbol' => 'Si', 'name' => 'Silicon', 'group' => 14, 'period' => 3, 'category' => 'metalloid', 'mass' => '28.085'],
            ['atomic' => 15, 'symbol' => 'P', 'name' => 'Phosphorus', 'group' => 15, 'period' => 3, 'category' => 'nonmetal', 'mass' => '30.974'],
            ['atomic' => 16, 'symbol' => 'S', 'name' => 'Sulfur', 'group' => 16, 'period' => 3, 'category' => 'nonmetal', 'mass' => '32.06'],
            ['atomic' => 17, 'symbol' => 'Cl', 'name' => 'Chlorine', 'group' => 17, 'period' => 3, 'category' => 'halogen', 'mass' => '35.45'],
            ['atomic' => 18, 'symbol' => 'Ar', 'name' => 'Argon', 'group' => 18, 'period' => 3, 'category' => 'noble-gas', 'mass' => '39.95'],
            ['atomic' => 19, 'symbol' => 'K', 'name' => 'Potassium', 'group' => 1, 'period' => 4, 'category' => 'alkali-metal', 'mass' => '39.098'],
            ['atomic' => 20, 'symbol' => 'Ca', 'name' => 'Calcium', 'group' => 2, 'period' => 4, 'category' => 'alkaline-earth-metal', 'mass' => '40.078'],
            ['atomic' => 21, 'symbol' => 'Sc', 'name' => 'Scandium', 'group' => 3, 'period' => 4, 'category' => 'transition-metal', 'mass' => '44.956'],
            ['atomic' => 22, 'symbol' => 'Ti', 'name' => 'Titanium', 'group' => 4, 'period' => 4, 'category' => 'transition-metal', 'mass' => '47.867'],
            ['atomic' => 23, 'symbol' => 'V', 'name' => 'Vanadium', 'group' => 5, 'period' => 4, 'category' => 'transition-metal', 'mass' => '50.942'],
            ['atomic' => 24, 'symbol' => 'Cr', 'name' => 'Chromium', 'group' => 6, 'period' => 4, 'category' => 'transition-metal', 'mass' => '51.996'],
            ['atomic' => 25, 'symbol' => 'Mn', 'name' => 'Manganese', 'group' => 7, 'period' => 4, 'category' => 'transition-metal', 'mass' => '54.938'],
            ['atomic' => 26, 'symbol' => 'Fe', 'name' => 'Iron', 'group' => 8, 'period' => 4, 'category' => 'transition-metal', 'mass' => '55.845'],
            ['atomic' => 27, 'symbol' => 'Co', 'name' => 'Cobalt', 'group' => 9, 'period' => 4, 'category' => 'transition-metal', 'mass' => '58.933'],
            ['atomic' => 28, 'symbol' => 'Ni', 'name' => 'Nickel', 'group' => 10, 'period' => 4, 'category' => 'transition-metal', 'mass' => '58.693'],
            ['atomic' => 29, 'symbol' => 'Cu', 'name' => 'Copper', 'group' => 11, 'period' => 4, 'category' => 'transition-metal', 'mass' => '63.546'],
            ['atomic' => 30, 'symbol' => 'Zn', 'name' => 'Zinc', 'group' => 12, 'period' => 4, 'category' => 'transition-metal', 'mass' => '65.38'],
            ['atomic' => 31, 'symbol' => 'Ga', 'name' => 'Gallium', 'group' => 13, 'period' => 4, 'category' => 'post-transition-metal', 'mass' => '69.723'],
            ['atomic' => 32, 'symbol' => 'Ge', 'name' => 'Germanium', 'group' => 14, 'period' => 4, 'category' => 'metalloid', 'mass' => '72.630'],
            ['atomic' => 33, 'symbol' => 'As', 'name' => 'Arsenic', 'group' => 15, 'period' => 4, 'category' => 'metalloid', 'mass' => '74.922'],
            ['atomic' => 34, 'symbol' => 'Se', 'name' => 'Selenium', 'group' => 16, 'period' => 4, 'category' => 'nonmetal', 'mass' => '78.971'],
            ['atomic' => 35, 'symbol' => 'Br', 'name' => 'Bromine', 'group' => 17, 'period' => 4, 'category' => 'halogen', 'mass' => '79.904'],
            ['atomic' => 36, 'symbol' => 'Kr', 'name' => 'Krypton', 'group' => 18, 'period' => 4, 'category' => 'noble-gas', 'mass' => '83.798'],
            ['atomic' => 37, 'symbol' => 'Rb', 'name' => 'Rubidium', 'group' => 1, 'period' => 5, 'category' => 'alkali-metal', 'mass' => '85.468'],
            ['atomic' => 38, 'symbol' => 'Sr', 'name' => 'Strontium', 'group' => 2, 'period' => 5, 'category' => 'alkaline-earth-metal', 'mass' => '87.62'],
            ['atomic' => 39, 'symbol' => 'Y', 'name' => 'Yttrium', 'group' => 3, 'period' => 5, 'category' => 'transition-metal', 'mass' => '88.906'],
            ['atomic' => 40, 'symbol' => 'Zr', 'name' => 'Zirconium', 'group' => 4, 'period' => 5, 'category' => 'transition-metal', 'mass' => '91.224'],
            ['atomic' => 41, 'symbol' => 'Nb', 'name' => 'Niobium', 'group' => 5, 'period' => 5, 'category' => 'transition-metal', 'mass' => '92.906'],
            ['atomic' => 42, 'symbol' => 'Mo', 'name' => 'Molybdenum', 'group' => 6, 'period' => 5, 'category' => 'transition-metal', 'mass' => '95.95'],
            ['atomic' => 43, 'symbol' => 'Tc', 'name' => 'Technetium', 'group' => 7, 'period' => 5, 'category' => 'transition-metal', 'mass' => '[98]'],
            ['atomic' => 44, 'symbol' => 'Ru', 'name' => 'Ruthenium', 'group' => 8, 'period' => 5, 'category' => 'transition-metal', 'mass' => '101.07'],
            ['atomic' => 45, 'symbol' => 'Rh', 'name' => 'Rhodium', 'group' => 9, 'period' => 5, 'category' => 'transition-metal', 'mass' => '102.91'],
            ['atomic' => 46, 'symbol' => 'Pd', 'name' => 'Palladium', 'group' => 10, 'period' => 5, 'category' => 'transition-metal', 'mass' => '106.42'],
            ['atomic' => 47, 'symbol' => 'Ag', 'name' => 'Silver', 'group' => 11, 'period' => 5, 'category' => 'transition-metal', 'mass' => '107.87'],
            ['atomic' => 48, 'symbol' => 'Cd', 'name' => 'Cadmium', 'group' => 12, 'period' => 5, 'category' => 'transition-metal', 'mass' => '112.41'],
            ['atomic' => 49, 'symbol' => 'In', 'name' => 'Indium', 'group' => 13, 'period' => 5, 'category' => 'post-transition-metal', 'mass' => '114.82'],
            ['atomic' => 50, 'symbol' => 'Sn', 'name' => 'Tin', 'group' => 14, 'period' => 5, 'category' => 'post-transition-metal', 'mass' => '118.71'],
            ['atomic' => 51, 'symbol' => 'Sb', 'name' => 'Antimony', 'group' => 15, 'period' => 5, 'category' => 'metalloid', 'mass' => '121.76'],
            ['atomic' => 52, 'symbol' => 'Te', 'name' => 'Tellurium', 'group' => 16, 'period' => 5, 'category' => 'metalloid', 'mass' => '127.60'],
            ['atomic' => 53, 'symbol' => 'I', 'name' => 'Iodine', 'group' => 17, 'period' => 5, 'category' => 'halogen', 'mass' => '126.90'],
            ['atomic' => 54, 'symbol' => 'Xe', 'name' => 'Xenon', 'group' => 18, 'period' => 5, 'category' => 'noble-gas', 'mass' => '131.29'],
            ['atomic' => 55, 'symbol' => 'Cs', 'name' => 'Cesium', 'group' => 1, 'period' => 6, 'category' => 'alkali-metal', 'mass' => '132.91'],
            ['atomic' => 56, 'symbol' => 'Ba', 'name' => 'Barium', 'group' => 2, 'period' => 6, 'category' => 'alkaline-earth-metal', 'mass' => '137.33'],
            ['atomic' => 57, 'symbol' => 'La', 'name' => 'Lanthanum', 'group' => 3, 'period' => 6, 'category' => 'lanthanide', 'mass' => '138.91'],
            ['atomic' => 58, 'symbol' => 'Ce', 'name' => 'Cerium', 'group' => 4, 'period' => 9, 'category' => 'lanthanide', 'mass' => '140.12'],
            ['atomic' => 59, 'symbol' => 'Pr', 'name' => 'Praseodymium', 'group' => 5, 'period' => 9, 'category' => 'lanthanide', 'mass' => '140.91'],
            ['atomic' => 60, 'symbol' => 'Nd', 'name' => 'Neodymium', 'group' => 6, 'period' => 9, 'category' => 'lanthanide', 'mass' => '144.24'],
            ['atomic' => 61, 'symbol' => 'Pm', 'name' => 'Promethium', 'group' => 7, 'period' => 9, 'category' => 'lanthanide', 'mass' => '[145]'],
            ['atomic' => 62, 'symbol' => 'Sm', 'name' => 'Samarium', 'group' => 8, 'period' => 9, 'category' => 'lanthanide', 'mass' => '150.36'],
            ['atomic' => 63, 'symbol' => 'Eu', 'name' => 'Europium', 'group' => 9, 'period' => 9, 'category' => 'lanthanide', 'mass' => '151.96'],
            ['atomic' => 64, 'symbol' => 'Gd', 'name' => 'Gadolinium', 'group' => 10, 'period' => 9, 'category' => 'lanthanide', 'mass' => '157.25'],
            ['atomic' => 65, 'symbol' => 'Tb', 'name' => 'Terbium', 'group' => 11, 'period' => 9, 'category' => 'lanthanide', 'mass' => '158.93'],
            ['atomic' => 66, 'symbol' => 'Dy', 'name' => 'Dysprosium', 'group' => 12, 'period' => 9, 'category' => 'lanthanide', 'mass' => '162.50'],
            ['atomic' => 67, 'symbol' => 'Ho', 'name' => 'Holmium', 'group' => 13, 'period' => 9, 'category' => 'lanthanide', 'mass' => '164.93'],
            ['atomic' => 68, 'symbol' => 'Er', 'name' => 'Erbium', 'group' => 14, 'period' => 9, 'category' => 'lanthanide', 'mass' => '167.26'],
            ['atomic' => 69, 'symbol' => 'Tm', 'name' => 'Thulium', 'group' => 15, 'period' => 9, 'category' => 'lanthanide', 'mass' => '168.93'],
            ['atomic' => 70, 'symbol' => 'Yb', 'name' => 'Ytterbium', 'group' => 16, 'period' => 9, 'category' => 'lanthanide', 'mass' => '173.05'],
            ['atomic' => 71, 'symbol' => 'Lu', 'name' => 'Lutetium', 'group' => 17, 'period' => 9, 'category' => 'lanthanide', 'mass' => '174.97'],
            ['atomic' => 72, 'symbol' => 'Hf', 'name' => 'Hafnium', 'group' => 4, 'period' => 6, 'category' => 'transition-metal', 'mass' => '178.49'],
            ['atomic' => 73, 'symbol' => 'Ta', 'name' => 'Tantalum', 'group' => 5, 'period' => 6, 'category' => 'transition-metal', 'mass' => '180.95'],
            ['atomic' => 74, 'symbol' => 'W', 'name' => 'Tungsten', 'group' => 6, 'period' => 6, 'category' => 'transition-metal', 'mass' => '183.84'],
            ['atomic' => 75, 'symbol' => 'Re', 'name' => 'Rhenium', 'group' => 7, 'period' => 6, 'category' => 'transition-metal', 'mass' => '186.21'],
            ['atomic' => 76, 'symbol' => 'Os', 'name' => 'Osmium', 'group' => 8, 'period' => 6, 'category' => 'transition-metal', 'mass' => '190.23'],
            ['atomic' => 77, 'symbol' => 'Ir', 'name' => 'Iridium', 'group' => 9, 'period' => 6, 'category' => 'transition-metal', 'mass' => '192.22'],
            ['atomic' => 78, 'symbol' => 'Pt', 'name' => 'Platinum', 'group' => 10, 'period' => 6, 'category' => 'transition-metal', 'mass' => '195.08'],
            ['atomic' => 79, 'symbol' => 'Au', 'name' => 'Gold', 'group' => 11, 'period' => 6, 'category' => 'transition-metal', 'mass' => '196.97'],
            ['atomic' => 80, 'symbol' => 'Hg', 'name' => 'Mercury', 'group' => 12, 'period' => 6, 'category' => 'transition-metal', 'mass' => '200.59'],
            ['atomic' => 81, 'symbol' => 'Tl', 'name' => 'Thallium', 'group' => 13, 'period' => 6, 'category' => 'post-transition-metal', 'mass' => '204.38'],
            ['atomic' => 82, 'symbol' => 'Pb', 'name' => 'Lead', 'group' => 14, 'period' => 6, 'category' => 'post-transition-metal', 'mass' => '207.2'],
            ['atomic' => 83, 'symbol' => 'Bi', 'name' => 'Bismuth', 'group' => 15, 'period' => 6, 'category' => 'post-transition-metal', 'mass' => '208.98'],
            ['atomic' => 84, 'symbol' => 'Po', 'name' => 'Polonium', 'group' => 16, 'period' => 6, 'category' => 'metalloid', 'mass' => '[209]'],
            ['atomic' => 85, 'symbol' => 'At', 'name' => 'Astatine', 'group' => 17, 'period' => 6, 'category' => 'halogen', 'mass' => '[210]'],
            ['atomic' => 86, 'symbol' => 'Rn', 'name' => 'Radon', 'group' => 18, 'period' => 6, 'category' => 'noble-gas', 'mass' => '[222]'],
            ['atomic' => 87, 'symbol' => 'Fr', 'name' => 'Francium', 'group' => 1, 'period' => 7, 'category' => 'alkali-metal', 'mass' => '[223]'],
            ['atomic' => 88, 'symbol' => 'Ra', 'name' => 'Radium', 'group' => 2, 'period' => 7, 'category' => 'alkaline-earth-metal', 'mass' => '[226]'],
            ['atomic' => 89, 'symbol' => 'Ac', 'name' => 'Actinium', 'group' => 3, 'period' => 7, 'category' => 'actinide', 'mass' => '[227]'],
            ['atomic' => 90, 'symbol' => 'Th', 'name' => 'Thorium', 'group' => 4, 'period' => 10, 'category' => 'actinide', 'mass' => '232.04'],
            ['atomic' => 91, 'symbol' => 'Pa', 'name' => 'Protactinium', 'group' => 5, 'period' => 10, 'category' => 'actinide', 'mass' => '231.04'],
            ['atomic' => 92, 'symbol' => 'U', 'name' => 'Uranium', 'group' => 6, 'period' => 10, 'category' => 'actinide', 'mass' => '238.03'],
            ['atomic' => 93, 'symbol' => 'Np', 'name' => 'Neptunium', 'group' => 7, 'period' => 10, 'category' => 'actinide', 'mass' => '[237]'],
            ['atomic' => 94, 'symbol' => 'Pu', 'name' => 'Plutonium', 'group' => 8, 'period' => 10, 'category' => 'actinide', 'mass' => '[244]'],
            ['atomic' => 95, 'symbol' => 'Am', 'name' => 'Americium', 'group' => 9, 'period' => 10, 'category' => 'actinide', 'mass' => '[243]'],
            ['atomic' => 96, 'symbol' => 'Cm', 'name' => 'Curium', 'group' => 10, 'period' => 10, 'category' => 'actinide', 'mass' => '[247]'],
            ['atomic' => 97, 'symbol' => 'Bk', 'name' => 'Berkelium', 'group' => 11, 'period' => 10, 'category' => 'actinide', 'mass' => '[247]'],
            ['atomic' => 98, 'symbol' => 'Cf', 'name' => 'Californium', 'group' => 12, 'period' => 10, 'category' => 'actinide', 'mass' => '[251]'],
            ['atomic' => 99, 'symbol' => 'Es', 'name' => 'Einsteinium', 'group' => 13, 'period' => 10, 'category' => 'actinide', 'mass' => '[252]'],
            ['atomic' => 100, 'symbol' => 'Fm', 'name' => 'Fermium', 'group' => 14, 'period' => 10, 'category' => 'actinide', 'mass' => '[257]'],
            ['atomic' => 101, 'symbol' => 'Md', 'name' => 'Mendelevium', 'group' => 15, 'period' => 10, 'category' => 'actinide', 'mass' => '[258]'],
            ['atomic' => 102, 'symbol' => 'No', 'name' => 'Nobelium', 'group' => 16, 'period' => 10, 'category' => 'actinide', 'mass' => '[259]'],
            ['atomic' => 103, 'symbol' => 'Lr', 'name' => 'Lawrencium', 'group' => 17, 'period' => 10, 'category' => 'actinide', 'mass' => '[266]'],
            ['atomic' => 104, 'symbol' => 'Rf', 'name' => 'Rutherfordium', 'group' => 4, 'period' => 7, 'category' => 'transition-metal', 'mass' => '[267]'],
            ['atomic' => 105, 'symbol' => 'Db', 'name' => 'Dubnium', 'group' => 5, 'period' => 7, 'category' => 'transition-metal', 'mass' => '[268]'],
            ['atomic' => 106, 'symbol' => 'Sg', 'name' => 'Seaborgium', 'group' => 6, 'period' => 7, 'category' => 'transition-metal', 'mass' => '[269]'],
            ['atomic' => 107, 'symbol' => 'Bh', 'name' => 'Bohrium', 'group' => 7, 'period' => 7, 'category' => 'transition-metal', 'mass' => '[270]'],
            ['atomic' => 108, 'symbol' => 'Hs', 'name' => 'Hassium', 'group' => 8, 'period' => 7, 'category' => 'transition-metal', 'mass' => '[269]'],
            ['atomic' => 109, 'symbol' => 'Mt', 'name' => 'Meitnerium', 'group' => 9, 'period' => 7, 'category' => 'transition-metal', 'mass' => '[278]'],
            ['atomic' => 110, 'symbol' => 'Ds', 'name' => 'Darmstadtium', 'group' => 10, 'period' => 7, 'category' => 'transition-metal', 'mass' => '[281]'],
            ['atomic' => 111, 'symbol' => 'Rg', 'name' => 'Roentgenium', 'group' => 11, 'period' => 7, 'category' => 'transition-metal', 'mass' => '[282]'],
            ['atomic' => 112, 'symbol' => 'Cn', 'name' => 'Copernicium', 'group' => 12, 'period' => 7, 'category' => 'transition-metal', 'mass' => '[285]'],
            ['atomic' => 113, 'symbol' => 'Nh', 'name' => 'Nihonium', 'group' => 13, 'period' => 7, 'category' => 'post-transition-metal', 'mass' => '[286]'],
            ['atomic' => 114, 'symbol' => 'Fl', 'name' => 'Flerovium', 'group' => 14, 'period' => 7, 'category' => 'post-transition-metal', 'mass' => '[289]'],
            ['atomic' => 115, 'symbol' => 'Mc', 'name' => 'Moscovium', 'group' => 15, 'period' => 7, 'category' => 'post-transition-metal', 'mass' => '[290]'],
            ['atomic' => 116, 'symbol' => 'Lv', 'name' => 'Livermorium', 'group' => 16, 'period' => 7, 'category' => 'post-transition-metal', 'mass' => '[293]'],
            ['atomic' => 117, 'symbol' => 'Ts', 'name' => 'Tennessine', 'group' => 17, 'period' => 7, 'category' => 'halogen', 'mass' => '[294]'],
            ['atomic' => 118, 'symbol' => 'Og', 'name' => 'Oganesson', 'group' => 18, 'period' => 7, 'category' => 'noble-gas', 'mass' => '[294]'],
        ];
    }

    public static function getElementBySymbol(string $symbol): ?array
    {
        $elements = self::getElements();
        foreach ($elements as $el) {
            if (strtolower($el['symbol']) === strtolower($symbol)) {
                return $el;
            }
        }
        return null;
    }
}
