import json
import os

with open('src/ptable/data/master_elements.json', encoding='utf-8') as f:
    master = json.load(f)

cf_data = next((e for e in master if e.get('name') == 'Californium'), None) if isinstance(master, list) else master.get('Cf')

cf_data['extract_html'] = """<p><b>Californium</b> (symbol <b>Cf</b>, atomic number 98) is a fascinating synthetic chemical element, meaning it does not occur naturally and must be created in a laboratory. It was first synthesized in 1950 at the University of California, Berkeley, by bombarding curium with alpha particles. This radioactive metal is named after the university and the state of California.</p>
<p>Although it is incredibly rare and expensive to produce, Californium is one of the few artificially created elements that has practical, real-world uses. It is primarily valued because some of its forms (isotopes), especially Californium-252, are powerful sources of neutrons. This makes it incredibly useful for jump-starting nuclear reactors, finding valuable ores and oil in the ground, and targeting certain types of cancers. In recent years, Indian news has occasionally been captivated by sensational hoaxes claiming massive seizures of "californium" worth billions of rupees. However, teams from India's prestigious Bhabha Atomic Research Centre (BARC) have consistently investigated these cases, proving that the seized materials were non-radioactive fakes, as true californium is strictly regulated and only handled by specialized atomic energy facilities.</p>
<p>Because of its intense radioactivity, californium must be handled with extreme care. It can bioaccumulate in skeletal tissue, posing significant health risks by disrupting red blood cell formation.</p>"""

cf_data['sections'] = {
    'Characteristics': '<p>Californium is a highly radioactive, silvery-white metal that slowly tarnishes when exposed to air at room temperature. Because it is synthetic and incredibly hard to produce, only very small amounts are ever made at one time, usually just micrograms or milligrams.</p>',
    'Physical properties': '<p>Despite its rarity, scientists have been able to study some of Californium\'s physical traits. It is a silvery-white metal that is soft enough to be easily cut with a knife. It melts at around 900 °C (1,650 °F) and boils at an estimated 1,743 °C (3,169 °F). Interestingly, it can act like a magnet at extremely low temperatures but loses this strong magnetic behavior as it warms up. Under normal conditions, its atoms pack together into a double-hexagonal crystal structure, but under intense pressure, the arrangement of its atoms changes entirely. While it shares some properties with other rare earth metals, it is relatively soft and compresses more easily than familiar metals like aluminum.</p>',
    'Isotopes': '<p>Isotopes are different versions of an element that have the same number of protons but a different number of neutrons. Californium has 20 known isotopes, ranging in mass from 237 to 256. All of them are radioactive and unstable. The most stable version is Californium-251, which has a half-life of 898 years (meaning it takes that long for half of it to decay). However, the most famous and useful isotope is Californium-252. Although it has a shorter half-life of just over 2.6 years, it is a tremendous emitter of neutrons—just one microgram can shoot out 2.3 million neutrons every second! Because of this extreme radioactivity, 252Cf is both highly valuable and hazardous, requiring heavily shielded containers for transport.</p>',
    'History': '<p>Californium was first created in February 1950 by a team of pioneering scientists—Stanley Gerald Thompson, Kenneth Street Jr., Albert Ghiorso, and Glenn T. Seaborg—at the University of California, Berkeley. They used a machine called a cyclotron to shoot alpha particles (helium nuclei) at another synthetic element, curium. The experiment produced just about 5,000 atoms of the new element, which lasted for only 44 minutes. They named it after California, breaking a previous naming tradition, playfully noting that just as it was hard for pioneers to reach California a century earlier, it was very hard to reach this element. Over the decades, production moved to specialized reactors, like the High Flux Isotope Reactor at the Oak Ridge National Laboratory in the USA, which became one of the few places in the world capable of making it in milligram quantities.</p>',
    'Occurrence': '<p>Because of its short half-life compared to the age of the Earth, you won\'t find californium naturally in the Earth\'s crust today. Any that might have existed from ancient natural nuclear reactions or cosmic events has long since decayed away. Today, traces of californium can only be found near facilities that actively use it, or in the radioactive fallout from atmospheric nuclear weapons tests conducted before 1980. Its extreme rarity and synthetic nature mean that when local Indian police occasionally bust smuggling rings claiming to sell natural californium rocks, institutions like BARC quickly debunk these claims, as the element cannot simply be mined from the earth.</p>',
    'Applications': '<p>Unlike many other synthetic elements that exist only for brief scientific curiosities, californium has important practical jobs. Because Californium-252 is such a strong neutron emitter, it is used as a portable neutron source. This is incredibly useful for jump-starting nuclear power plants, performing neutron radiography (a kind of X-ray that can see through metal to find aircraft defects), and detecting underground gold, silver, and oil deposits. It has also been used in medical treatments to target certain brain and cervical cancers when radiation needs to be applied directly to the tumor. Due to its intense radiation, even shipping a single gram of californium requires a massive 50-ton protective cask to keep people safe. In India, premier research organizations like the Bhabha Atomic Research Centre (BARC) have historically utilized imported Californium-252 sources for advanced post-graduate training in radiological physics and for vital research.</p>'
}

os.makedirs('src/ptable/data/drafts', exist_ok=True)
with open('src/ptable/data/drafts/Californium.json', 'w', encoding='utf-8') as f:
    json.dump({'Cf': cf_data} if isinstance(master, dict) else cf_data, f, indent=2, ensure_ascii=False)
print("Done")
