import json

data = {
    'extract_html': '<p>Thallium is a chemical element with the symbol <b>Tl</b> and atomic number 81. It is a soft, silvery-white metal that quickly tarnishes to a dull bluish-gray when exposed to air. Although it looks a lot like tin or lead, it hides a deadly secret: thallium is highly toxic and historically infamous as the "poisoner\'s poison." Discovered in 1861 by its brilliant green spectral line, it is now primarily used in high-tech electronics, specialized optics, and nuclear medicine. Because it is not found free in nature, it is typically gathered as a byproduct of refining other metal ores.</p>',
    'sections': {
        'Characteristics': '<p>Thallium is a heavy, post-transition metal that is soft enough to be cut with a standard knife at room temperature. Freshly cut thallium shines with a bright, silvery metallic luster, but it rapidly reacts with oxygen in the air, forming a heavy, grayish oxide crust that makes it look like lead. To prevent this, scientists often store it under oil.</p><p>Chemically, it behaves in unusual ways. While it shares a group on the periodic table with elements like aluminum and gallium, its chemical bonds are influenced by the "inert pair effect"—a phenomenon where its outermost electrons are reluctant to participate in reactions. This makes thallium often act more like potassium or silver in its compounds. When ingested, the human body actually mistakes thallium for potassium, which is one of the reasons it is so devastatingly toxic at a cellular level.</p>',
        'Isotopes': '<p>Thallium has 41 known isotopes, but only two of them—Thallium-203 and Thallium-205—are stable and make up all naturally occurring thallium on Earth. The rest are radioactive and generally short-lived.</p><p>The most famous of these radioactive forms is Thallium-201. Far from being a poison, this artificially created isotope is a lifesaver in modern medicine. Because it emits low-energy X-rays and gamma rays, it is widely used in nuclear cardiology. During a cardiac stress test, doctors inject a tiny, safe amount of Thallium-201 into a patient\'s bloodstream to capture highly detailed images of blood flow to the heart muscle, helping diagnose heart disease.</p>',
        'History': '<p>The story of thallium begins in 1861 with a brilliant flash of green light. British chemist William Crookes and French chemist Claude-Auguste Lamy independently discovered the element using a then-revolutionary technique called flame spectroscopy. When analyzing leftover sludge from a sulfuric acid factory, they noticed an unknown, bright green line in the spectrum. Crookes named the new element "thallium" after the Greek word <i>thallos</i>, meaning a green shoot or twig.</p><p>Though both men played crucial roles—Crookes identified it, and Lamy first isolated the solid metal—a bitter rivalry erupted over who deserved the credit.</p><p>In the 20th century, thallium gained a dark reputation. Because its soluble salts are colorless, odorless, and nearly tasteless, it became a popular ingredient in rat poisons and insecticides. Unfortunately, these same traits made it the weapon of choice for murderers, earning it the grim nickname of "the poisoner\'s poison." Today, its use in commercial pesticides has been largely banned worldwide.</p>',
        'Applications': '<p>While its days as a household pesticide are long gone, thallium remains valuable in specialized modern industries. It is a critical component in manufacturing high-tech infrared detectors, photoelectric cells, and specialized optical glasses that require a high refractive index.</p><p>In India, thallium occasionally makes headlines for different reasons. Due to its historical notoriety, it still surfaces in rare but high-profile homicidal poisonings and domestic disputes. These criminal cases highlight a major challenge in public health: diagnosing thallium poisoning is difficult because early symptoms—such as unexplained nerve pain, gastrointestinal distress, and delayed hair loss (alopecia)—mimic other illnesses. Consequently, Indian medical literature frequently emphasizes the need for heightened clinical awareness to catch and treat exposure early.</p><p>Despite its dark side, thallium\'s contributions to advanced electronics and nuclear medicine make it an irreplaceable, if dangerous, element in the modern world.</p>'
    }
}

with open('c:/projects/apache/school1/src/ptable/data/drafts/Thallium.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4)
