import json
import os

potassium_data = {
  "symbol": "K",
  "name": "Potassium",
  "atomic": 19,
  "category": "alkali metal",
  "description": "",
  "extract_html": "<p><a href=\"/school1/ptable/element/K\" class=\"wiki-link\" title=\"Potassium (K)\">Potassium</a> (symbol K, derived from Neo-Latin <i>kalium</i>, atomic number 19) is a soft, silvery-white alkali metal that is essential for life on Earth. So soft that it can easily be cut with a butter knife, potassium reacts violently with water, bursting into a striking lilac flame. It is the seventh most abundant element in Earth's crust and serves as the primary electrolyte inside living cells, powering nerve signals, muscle contractions, and heart rhythms across the biological world.</p>",
  "local_image": "https://upload.wikimedia.org/wikipedia/commons/b/b3/Potassium.JPG",
  "atomic_mass": 39.09831,
  "density": 0.862,
  "melt": 336.7,
  "boil": 1032,
  "phase": "Solid",
  "discovered_by": "Humphry Davy",
  "electron_configuration": "1s2 2s2 2p6 3s2 3p6 4s1",
  "electronegativity_pauling": 0.82,
  "electron_affinity": 48.383,
  "ionization_energies": [
    418.8,
    3052,
    4420,
    5877,
    7975,
    9590,
    11343,
    14944,
    16963.7,
    48610,
    54490,
    60730,
    68950,
    75900,
    83080,
    93400,
    99710,
    444880,
    476063
  ],
  "sections": {
    "Characteristics": "</div>\n<p><a href=\"/school1/ptable/element/K\" class=\"wiki-link\" title=\"Potassium (K)\">Potassium</a> is a classic Group 1 alkali metal with an atomic number of 19. It possesses a single valence electron in its outermost shell (electron configuration [Ar] 4s¹), which it readily sheds to form a positively charged cation (K⁺). Because of this outer electron structure, potassium is exceptionally reactive and electropositive, with a Pauling electronegativity of just 0.82.</p><p>In its pure elemental form, potassium is a soft, light, silvery metal. It is so soft that it can be effortlessly carved with a knife at room temperature. Freshly cut potassium shines brightly, but within seconds of exposure to air, it tarnishes to a dull grey as it reacts with atmospheric oxygen and moisture to form a coating of potassium oxide, hydroxide, and carbonate. To prevent rapid oxidation, pure potassium metal must be stored under mineral oil or kerosene.</p>\n<div class=\"mw-heading mw-heading3\">",
    "Physical properties": "</div>\n<p><a href=\"/school1/ptable/element/K\" class=\"wiki-link\" title=\"Potassium (K)\">Potassium</a> has a density of 0.862 g/cm³, making it the second-least dense metal after <a href=\"/school1/ptable/element/Li\" class=\"wiki-link\" title=\"Lithium (Li)\">lithium</a>. Because it is less dense than water (1.0 g/cm³), pure potassium metal actually floats on water while undergoing an intense chemical reaction.</p><p>Potassium has a remarkably low melting point of 63.5 °C (336.7 K), meaning a piece of potassium metal would melt in warm water, and a boiling point of 759 °C (1,032 K). Like other alkali metals, when heated in a flame, potassium ions emit a characteristic light: a soft violet or lilac flame color caused by electron excitation at a wavelength of 766.5 nanometers. This unique flame test signature allows scientists to easily identify potassium in chemical samples.</p>\n<div class=\"mw-heading mw-heading3\">",
    "Chemical properties": "</div>\n<p><a href=\"/school1/ptable/element/K\" class=\"wiki-link\" title=\"Potassium (K)\">Potassium</a> is even more chemically reactive than its neighbor <a href=\"/school1/ptable/element/Na\" class=\"wiki-link\" title=\"Sodium (Na)\">sodium</a>. When dropped into water, potassium reacts exothermically to produce potassium hydroxide (KOH) solution and liberating hydrogen gas (H₂). The heat released by this reaction is so intense that it instantly ignites the escaping hydrogen gas, creating a bright lilac-colored flame that often ends with a sharp miniature explosion.</p><p>Potassium reacts spontaneously with all halogens—<a href=\"/school1/ptable/element/F\" class=\"wiki-link\" title=\"Fluorine (F)\">fluorine</a>, <a href=\"/school1/ptable/element/Cl\" class=\"wiki-link\" title=\"Chlorine (Cl)\">chlorine</a>, <a href=\"/school1/ptable/element/Br\" class=\"wiki-link\" title=\"Bromine (Br)\">bromine</a>, and <a href=\"/school1/ptable/element/I\" class=\"wiki-link\" title=\"Iodine (I)\">iodine</a>—to form white crystalline salts such as potassium chloride (KCl). It also reacts with oxygen to form oxides, peroxides, and a deep orange-colored potassium superoxide (KO₂). Potassium superoxide is particularly valuable because it absorbs carbon dioxide while releasing pure oxygen gas, making it useful in self-contained breathing rebreathers for firefighters, submarines, and spacecraft.</p>\n<div class=\"mw-heading mw-heading3\">",
    "Isotopes": "</div>\n<p>There are 25 known isotopes of <a href=\"/school1/ptable/element/K\" class=\"wiki-link\" title=\"Potassium (K)\">potassium</a>, ranging from <sup>32</sup>K to <sup>57</sup>K, but natural potassium consists of a mixture of just three isotopes: stable <sup>39</sup>K (93.26%), stable <sup>41</sup>K (6.73%), and long-lived radioactive <sup>40</sup>K (0.0117%).</p><p>The primordial radioisotope <sup>40</sup>K has an extraordinarily long half-life of 1.25 billion years (1.25 × 10⁹ years). It decays through two separate nuclear pathways: 88.8% of the time it undergoes beta decay into stable calcium-40 (<sup>40</sup>Ca), and 11.2% of the time it undergoes electron capture or positron emission to turn into stable argon-40 (<sup>40</sup>Ar). Because argon is a noble gas that escapes molten lava but stays trapped inside solidifying rock, the buildup of <sup>40</sup>Ar from <sup>40</sup>K decay provides the foundation for <b>potassium-argon (K–Ar) dating</b>. Geologists and archeologists use K–Ar dating to determine the age of ancient volcanic rocks, fossil-bearing geological layers, and lunar samples.</p><p>Potassium-40 (<sup>40</sup>K) is also the single largest source of natural internal radioactivity in the human body and animal life. In a healthy 70 kg human, approximately 4,400 atomic nuclei of <sup>40</sup>K decay every single second, producing around 31 Becquerels of activity per gram of natural potassium. Bags of potassium-rich salt substitutes (potassium chloride) are so naturally radioactive that science educators frequently use them for classroom demonstrations with Geiger counters.</p>\n<div class=\"mw-heading mw-heading3\">",
    "History": "</div>\n<p>Human utilization of <a href=\"/school1/ptable/element/K\" class=\"wiki-link\" title=\"Potassium (K)\">potassium</a> compounds dates back thousands of years, long before the element itself was isolated in pure metallic form. The English name <i>potassium</i> comes from <i>potash</i>, referring to the traditional practice of leaching wood ashes in iron pots to obtain potassium carbonate. The chemical symbol <b>K</b> comes from the Neo-Latin name <i>kalium</i>, which originates from the Arabic word <i>al-qalyah</i>, meaning \"alkali\" or \"plant ashes\".</p><p>In ancient India, knowledge of potassium alkalis and salts was highly developed within traditional medicine and metallurgy. Ancient Ayurvedic texts like the <i>Charaka Samhita</i> and <i>Sushruta Samhita</i> describe <b>Kshara</b> (alkaline ash preparations). A prime example is <i>Yava Kshara</i>, prepared by burning dried barley stalks (*Hordeum vulgare*), dissolving the ash in water, filtering it multiple times, and evaporating the liquid to yield purified potassium carbonate (K₂CO₃). Ayurvedic physicians utilized <i>Yava Kshara</i> for its *Lekhana* (scraping/cleansing) and *Mutrala* (diuretic) properties to treat kidney stones, urinary disorders, and abdominal ailments.</p><p>Ancient Indian texts also recorded potassium nitrate (KNO₃) under the Sanskrit names <i>Suryakshar</i>, <i>Saurkshar</i>, or <i>Suvarchika</i>, known regionally as <i>Shora</i> or <i>Kalmi Shora</i>. Medieval alchemical and medical treatises like the 13th-century <i>Rasaratnasamuccaya</i> detailed the extraction and crystallization of <i>Shora</i> from soil enriched with organic matter. By the medieval and early modern eras, the fertile plains of Bihar became the global hub for saltpetre harvesting, managed by the traditional <i>Nuniah</i> community. Because saltpetre was the primary oxidizer in gunpowder, control over Bihar's <i>Shora</i> trade became a major strategic driver for European colonial powers like the Dutch, French, and British East India Companies.</p><p>In modern chemistry, pure elemental potassium was first isolated in 1807 by English chemist Sir Humphry Davy in London. Davy achieved this by passing an electric current through molten caustic potash (KOH)—making potassium the very first chemical element ever isolated using electrolysis. When Davy saw the tiny, silvery droplets of pure potassium metal burst into purple flames as they touched the air, he reportedly danced around the room in delight.</p>\n<div class=\"mw-heading mw-heading3\">",
    "Occurrence": "</div>\n<p><a href=\"/school1/ptable/element/K\" class=\"wiki-link\" title=\"Potassium (K)\">Potassium</a> is created in the universe during explosive stellar events known as Type II supernovae, through oxygen-burning and neon-burning nuclear fusion processes, as well as s-process nucleosynthesis. It ranks as the 20th most abundant element in the Solar System and the 17th most abundant element by mass on Earth.</p><p>Making up about 2.6% of Earth's crust by weight, potassium is the seventh most abundant element in the crust. Because of its extreme chemical reactivity, potassium is never found as a free metal in nature. Instead, it occurs in widespread minerals such as orthoclase feldspar, muscovite mica, sylvite (potassium chloride, KCl), carnallite, and polyhalite. Dissolved in ocean water, potassium has a concentration of about 0.39 g/L—roughly one twenty-seventh the concentration of <a href=\"/school1/ptable/element/Na\" class=\"wiki-link\" title=\"Sodium (Na)\">sodium</a>. Potassium ions are less abundant in seawater than sodium because plant roots absorb potassium rapidly and clay minerals in soil trap potassium ions tightly.</p><p>Geographically in India, while the nation has historically relied on imports for its potash needs, extensive deep-seated potash deposits have been identified in the <b>Nagaur-Ganganagar basin of Rajasthan</b>, particularly in Bikaner (Lakhasar) and Hanumangarh (Satipura) at depths of 500 to 750 meters. India has launched historic domestic mining projects in these Rajasthan blocks to extract sylvite and polyhalite minerals, advancing national agricultural self-reliance under the *Atmanirbhar Bharat* initiative.</p>\n<div class=\"mw-heading mw-heading3\">",
    "Biological role": "</div>\n<p><a href=\"/school1/ptable/element/K\" class=\"wiki-link\" title=\"Potassium (K)\">Potassium</a> is an essential macronutrient and the primary intracellular cation (positively charged ion) in all living animal cells. While <a href=\"/school1/ptable/element/Na\" class=\"wiki-link\" title=\"Sodium (Na)\">sodium</a> is concentrated in fluids outside cells, over 98% of the human body's total potassium resides inside cellular walls.</p><p>The fundamental mechanism sustaining cellular life is the <b>sodium-potassium pump (Na⁺/K⁺-ATPase)</b>, a vital cell membrane enzyme. Powered by ATP energy, this pump continuously moves three sodium ions (Na⁺) out of the cell for every two potassium ions (K⁺) it pumps inside. This active transport creates an electrochemical gradient across cell membranes known as the resting membrane potential. This electrical voltage powers nerve impulse transmission, regulates heartbeats, enables muscle contraction, and maintains cell volume and fluid balance.</p><p>An adult human body contains approximately 120 to 140 grams of potassium. Humans require about 3.5 to 4.7 grams of dietary potassium daily, obtained from foods like bananas, tender coconut water, potatoes, leafy green vegetables, pulses, and milk. Adequate potassium intake helps offset excess dietary sodium, lowering blood pressure and reducing cardiovascular risks. Severe potassium deficiency (hypokalemia) or excess (hyperkalemia) can cause dangerous muscle weakness and cardiac arrhythmias.</p>\n<div class=\"mw-heading mw-heading3\">",
    "Applications": "</div>\n<p>Over 93% of the world's harvested <a href=\"/school1/ptable/element/K\" class=\"wiki-link\" title=\"Potassium (K)\">potassium</a> is used in global agriculture as <b>potash fertilizers</b>, primarily potassium chloride (KCl), potassium sulfate (K₂SO₄), and potassium nitrate (KNO₃). Potassium fertilizer boosts plant growth, strengthens crop disease resistance, improves water retention, and increases agricultural yield.</p><p>In industrial chemistry, potassium hydroxide (KOH, caustic potash) is widely used to manufacture liquid soaps, detergents, and industrial cleaners. Potassium carbonate (K₂CO₃) is essential in producing specialty television and optical glasses, ceramics, and chemical catalysts. Potassium nitrate (KNO₃) serves in fireworks, black powder, and food curing. Potassium superoxide (KO₂) is utilized as an oxygen generator in closed-circuit breathing apparatuses. Additionally, a liquid alloy of sodium and potassium called <b>NaK</b> remains liquid at room temperature and is used as an efficient high-temperature heat-transfer coolant in specialized nuclear reactors and scientific equipment.</p>\n<div class=\"mw-heading mw-heading3\">"
  }
}

os.makedirs(r"c:\projects\apache\school1\src\ptable\data\drafts", exist_ok=True)
out_file = r"c:\projects\apache\school1\src\ptable\data\drafts\Potassium.json"
with open(out_file, "w", encoding="utf-8") as f:
    json.dump(potassium_data, f, indent=2, ensure_ascii=False)

print("Saved to", out_file)
