import json

draft = {
  'extract_html': '<p><b>Lutetium</b> (symbol <b>Lu</b>) is a fascinating chemical element with atomic number 71. As the very last element in the lanthanide series, it is a rare earth metal that shines with a beautiful silvery-white glow. While it resists tarnishing in dry air, it doesn\'t like moisture very much! Though it is rare and often overshadowed by more famous elements, lutetium is gaining a lot of modern importance. For instance, in India, its radioactive form is revolutionizing cancer treatments, and the rich coastal sands of states like Kerala and Tamil Nadu hold the very minerals, like monazite, where this hidden gem is found.</p>',
  'sections': {
    'Characteristics': '<p>Lutetium is the heaviest and hardest of all the rare earth elements. Despite its name, it\'s not impossibly rare—in fact, it\'s more common in the Earth\'s crust than silver! However, it is very difficult to separate from other elements, making it one of the most expensive rare earth metals in the world.</p>',
    'Physical properties': '<p>Even though it\'s classified as a lanthanide, lutetium\'s atoms are surprisingly small. This "lanthanide contraction" makes lutetium the densest, hardest, and highest-melting element in its family. It has a high melting point of 1,652 °C (3,006 °F) and acts more like a transition metal than a typical rare earth. Because its outer electrons are tightly bound, it typically forms stable +3 ions in chemical reactions.</p>',
    'Isotopes': '<p>In nature, you will mostly find two forms (or isotopes) of lutetium. The vast majority, about 97.4%, is the stable lutetium-175. The remaining 2.6% is lutetium-176, which is mildly radioactive. But don\'t worry—its half-life is an incredibly long 37 billion years! Because it decays so slowly, scientists use it as a cosmic clock to figure out the age of ancient meteorites and rocks. Beyond these natural forms, scientists have created many artificial radioactive isotopes in laboratories.</p>',
    'History': '<p>The discovery of lutetium in 1907 was a dramatic scientific race! Three scientists—Georges Urbain from France, Carl Auer von Welsbach from Austria, and Charles James from the United States—all independently found it hidden inside a mineral called ytterbia. Urbain was the first to publish his findings, so he won the right to name it. He chose "Lutecia", the ancient Roman name for his beloved hometown of Paris. Today, the focus on lutetium has shifted globally. In India, massive efforts by organizations like the Atomic Minerals Directorate explore monazite reserves to secure the future supply of rare earths like lutetium, connecting its Parisian naming roots to a vibrant modern scientific landscape in South Asia.</p>',
    'Applications': '<p>Because it is hard to extract and expensive, natural lutetium isn\'t used much in everyday products. However, its artificial radioactive version, Lutetium-177, is a true medical marvel! In India, scientists at the Bhabha Atomic Research Centre (BARC) have developed indigenous ways to produce Lutetium-177 using their Dhruva research reactor. This isotope is used in cutting-edge targeted radionuclide therapy to treat severe cancers, such as neuroendocrine tumors and prostate cancer. Thanks to these advancements, patients can receive world-class, affordable cancer care. Lutetium is also used in small amounts to speed up chemical reactions in petroleum refineries and to make special light-emitting crystals for medical scanners.</p>'
  }
}

with open('src/ptable/data/drafts/Lutetium.json', 'w', encoding='utf-8') as f:
  json.dump(draft, f, indent=4)
