import json

draft = {
    "extract_html": "<p><b>Niobium</b> is a shiny, light gray metal that plays a silent but essential role in our modern world. Though you might not hear about it every day, it is a superstar in high-tech industries. When mixed with other metals, it creates super-strong alloys used in everything from jet engines to rockets. It is also famous for its superconducting abilities, meaning it can carry electricity without any resistance when cooled down. In India, niobium is recognized as a strategic and critical mineral, playing a crucial part in the nation's <i>Atmanirbhar Bharat</i> (self-reliant India) initiative to develop advanced materials for space and nuclear energy right at home.</p>",
    "sections": {
        "History": "<p>Niobium's story began in 1801 when English chemist Charles Hatchett discovered it in a mineral sample and originally named it \"columbium.\" For decades, it was confused with another very similar element called tantalum. It was not until 1846 that German chemist Heinrich Rose realized they were two distinct elements and renamed it \"niobium\"—inspired by Niobe, the daughter of Tantalus in Greek mythology. Historically in India, the strategic importance of niobium became prominent in the mid-20th century as the country expanded its nuclear and military capabilities. Today, it remains a focal point for India's push towards self-reliance in critical materials, ensuring a steady domestic supply for next-generation technologies.</p>",
        "Characteristics": "<p>Niobium is a transition metal that is as soft and malleable as pure iron. When exposed to air at room temperature, it takes on a beautiful bluish tinge. One of its most magical properties is superconductivity: at extremely low temperatures, it allows electricity to flow with absolutely zero resistance. This makes it incredibly valuable for making powerful magnets. Indian scientific institutions, such as the Bhabha Atomic Research Centre (BARC) and the Indira Gandhi Centre for Atomic Research, have made significant breakthroughs in producing high-purity niobium ingots and developing niobium-titanium superconducting alloys indigenously. These advancements are essential for building cutting-edge particle accelerators and advanced nuclear reactors.</p>",
        "Isotopes": "<p>In nature, niobium exists entirely as a single stable isotope, known as Niobium-93. This means that all naturally occurring niobium is made up of atoms with the same mass. Scientists have also created several artificial, radioactive isotopes in laboratories, but they are generally short-lived and used mainly for research purposes. The predictable and stable nature of Niobium-93 is exactly what makes it so dependable when used in precise, high-tech engineering applications and energy research.</p>",
        "Occurrence": "<p>Niobium is never found as a free metal in nature; it prefers to bond with other elements in minerals like columbite and pyrochlore. While Brazil and Canada hold the vast majority of the world's niobium reserves, India has its own notable deposits. Major Indian sources are associated with carbonatite rocks and pegmatite belts. Significant exploration has taken place at Amba Dongar in Gujarat, where niobium is found as pyrochlore. Other important deposits are located in the Sung Valley and Samchampi Complex in the Northeast, Sevathur in Tamil Nadu, and the mica belts of Bihar and Rajasthan. The Geological Survey of India continues to actively explore these regions to secure the country's domestic supply.</p>",
        "Applications": "<p>Niobium is a true workhorse element. Its biggest job is strengthening steel; adding just a tiny pinch of niobium makes steel significantly stronger and lighter, which is perfect for building cars, bridges, and gas pipelines. In the aerospace industry, niobium alloys are used in jet engines and rocket nozzles because they can withstand extreme heat. Its superconducting magnets are crucial for MRI machines in hospitals. In India, modern research is taking niobium even further. For example, researchers at the Centre for Nano and Soft Matter Sciences (CeNS) in Bengaluru have recently developed innovative niobium-based materials (like lanthanum-doped silver niobate) for supercapacitors. These breakthroughs promise highly efficient energy storage solutions for the future of portable electronics and renewable energy in India.</p>"
    }
}

out_path = r"c:\projects\apache\school1\src\ptable\data\drafts\Niobium.json"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(draft, f, indent=4)
print("Saved to", out_path)
