import json
import os

with open('boron_extract.json', 'r', encoding='utf-8') as f:
    boron = json.load(f)

boron['extract_html'] = '<p><b><a href="/school1/ptable/element/B" class="wiki-link" title="Boron (B)">Boron</a></b> (symbol <b>B</b>, atomic number 5) is an incredibly versatile and fascinating metalloid. Unlike most elements, boron was not forged in the fiery cores of stars. Instead, it was born in the extreme environment of deep space, created when high-energy cosmic rays smashed into heavier matter. Because of this unique origin, boron is relatively rare in the universe and the Earth\'s crust. However, because its most common forms—minerals called borates—dissolve easily in water, it can be found in highly concentrated deposits here on Earth. Often described as a "schizophrenic" element, it confusingly blends the properties of both metals and non-metals. Today, boron is essential in everything from building ultra-strong aerospace parts to, possibly, the very origin of life.</p>'

boron['sections']['History'] = '</div>\n<figure class="mw-default-size" typeof="mw:File/Thumb"><img src="/school1/ptable/theme-assets/default/images/inline/775a874aadfdc99e73b765138414711a.jpg" decoding="async" width="250" height="250" class="mw-file-element" data-file-width="1632" data-file-height="1632" /><figcaption>Amorphous <a href="/school1/ptable/element/B" class="wiki-link" title="Boron (B)">boron</a> powder</figcaption></figure>\n<p>The name <i>boron</i> stems from <i>borax</i>, the mineral from which it was first extracted, and its ending reflects its chemical similarity to <a href="/school1/ptable/element/C" class="wiki-link" title="Carbon (C)">carbon</a>. Long before it was known as a unique element, early civilizations prized borate minerals. Over 4,000 years ago, ancient societies used them for metalworking. In ancient India, naturally occurring borax was well-known and called <i>Tankana</i> or <i>tincal</i>—a word that became the root for many modern names for the mineral. Harvested from the Himalayas and Tibet, it was widely used in traditional Ayurvedic medicine as <i>Tankana Bhasma</i> for treating ailments, and served as a crucial flux for purifying gold and silver. Around 300 AD, China began using borax for specialized ceramic glazes, which Marco Polo later introduced to Italy.</p>\n<figure class="mw-default-size mw-halign-left" typeof="mw:File/Thumb"><img src="/school1/ptable/theme-assets/default/images/inline/f04a847929d002552be76a1b1bd7b74e.jpg" decoding="async" width="190" height="181" style="--mw-file-upright: 0.75" class="mw-file-element mw-file-upright" data-file-width="535" data-file-height="510" /><figcaption>Sassolite</figcaption></figure>\n<p>Boron was not officially recognized as a distinct element until 1808. It was discovered independently by French chemists Joseph Louis Gay-Lussac and Louis Jacques Thénard, and British chemist Sir Humphry Davy. Davy, who playfully named the substance <i>boracium</i>, extracted it by applying electric currents and <a href="/school1/ptable/element/K" class="wiki-link" title="Potassium (K)">potassium</a> to boric acid. However, completely pure boron proved extremely stubborn to isolate. It took until 1909 for American chemist Ezekiel Weintraub to finally produce the first genuinely pure sample of the element.</p>\n<div class="mw-heading mw-heading2">'

boron['sections']['Isotopes'] = '</div>\n<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1368532237" /><div role="note" class="hatnote navigation-not-searchable">Main article: Isotopes of <a href="/school1/ptable/element/B" class="wiki-link" title="Boron (B)">boron</a></div>\n<p>In nature, boron exists mainly as two stable varieties, or isotopes: <sup>11</sup>B (which makes up about 80.1% of natural boron) and <sup>10</sup>B (the remaining 19.9%). Scientists have created 11 other isotopes in laboratories, but they are all incredibly unstable. For instance, <sup>7</sup>B exists for only 3.5×10<sup>−22</sup> seconds before falling apart!</p><p>The two stable isotopes are incredibly useful to researchers. When dissolved in water, <sup>10</sup>B and <sup>11</sup>B behave slightly differently. Because ocean water holds more <sup>11</sup>B compared to rocks on land, geologists can use this unique "isotopic signature" to track the history of ancient environments. In medicine, <sup>10</sup>B is a lifesaver. It is the key ingredient in Boron Neutron Capture Therapy (BNCT), a cutting-edge cancer treatment that uses targeted neutron beams to destroy brain tumors from the inside out, without harming healthy tissue.</p><p>Physicists are also captivated by a highly unstable isotope, <sup>17</sup>B. It possesses a bizarre "nuclear halo," meaning the atom is noticeably larger and more spread out than traditional rules of physics say it should be.</p>\n<div class="mw-heading mw-heading4">'

boron['sections']['Occurrence'] = '</div>\n<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1368532237" /><div role="note" class="hatnote navigation-not-searchable">Main article: Borate minerals</div>\n<figure class="mw-default-size mw-halign-right" typeof="mw:File/Thumb"><img src="/school1/ptable/theme-assets/default/images/inline/86ee14d71e196a043c9b9bb83312e342.jpg" decoding="async" width="250" height="195" class="mw-file-element" data-file-width="1024" data-file-height="800" /><figcaption>Borax crystals</figcaption></figure>\n<p>On a cosmic scale, boron is quite rare. Very little of it was made during the Big Bang. Unlike heavier elements like iron, boron is actually destroyed by the intense heat inside stars rather than created there. Instead, the universe makes boron through a dramatic process called "spallation," where high-speed cosmic rays crash into heavier atoms in deep space, shattering them into lighter pieces like boron.</p><p>Here on Earth, you will never find pure elemental boron out in nature. It is highly reactive with <a href="/school1/ptable/element/O" class="wiki-link" title="Oxygen (O)">oxygen</a>, meaning it prefers to form borate compounds. (However, scientists were amazed to find tiny flecks of pure boron in dirt brought back from the Moon!) Even though boron makes up a minuscule 0.001% of the Earth\'s crust, it is easy to mine because many borate minerals—like borax and boric acid—dissolve in water. Over millions of years, water has pooled these minerals together into large, rich deposits, especially in ancient, dried-up lakes and volcanic hot springs.</p>\n<div class="mw-heading mw-heading2">'

boron['sections']['Applications'] = '</div>\n<p>Though rarely discussed, boron is an unsung hero of the modern world. Most of the boron mined today is turned into boric acid or borax (sodium tetraborate). In the United States, roughly 70% of this supply is used to make specialized glass and ceramics. If you have ever baked with a Pyrex dish, peered through a telescope lens, or used laboratory beakers, you have relied on borosilicate glass. This special glass uses boron to endure sudden, extreme temperature changes without shattering.</p><p>Worldwide, boron\'s biggest job is in the production of fiberglass. Adding boron makes glass fibers tougher and easier to shape, which is vital for building home insulation and sturdy construction materials. Beyond glass, boron helps create incredibly tough ceramics and advanced materials. Boron fibers are exceptionally lightweight yet incredibly strong, making them ideal for high-tech aerospace parts and even bulletproof vests. You can also find boron silently working in automotive fluids to boost efficiency, in household detergents and bleaches, and in the manufacturing of modern computer semiconductors.</p>\n<div class="mw-heading mw-heading3">'

boron['sections']['Biological role'] = '</div>\n<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1368532237" /><div role="note" class="hatnote navigation-not-searchable">See also: <a href="/school1/ptable/element/B" class="wiki-link" title="Boron (B)">Boron</a> deficiency (plant disorder)</div>\n<p>For the plant kingdom, boron is non-negotiable. It acts as a critical micronutrient that builds and strengthens plant cell walls, ensuring healthy crops and abundant harvests. However, it walks a fine line: while plants need boron to thrive, soils with too much of it (anything above 1.8 parts per million) become toxic, causing leaves to wither and stunt growth.</p><p>In the microscopic world, nature uses boron to create unique antibiotics. Scientists discovered the first of these, boromycin, in the 1960s, followed by tartrolons in the 1990s. In modern laboratories, synthetic boron compounds called "BODIPYs" are incredibly popular. These brightly glowing fluorescent tags help scientists track and visualize hidden processes inside living cells.</p><p>Perhaps most mind-blowing of all is boron\'s potential link to our origins. Prominent scientists, such as chemist Steve Benner, suspect that ancient borate minerals played a vital role in the origin of life by stabilizing ribose, the fragile sugar backbone of RNA. In 2013, Benner even suggested that ancient Mars had better conditions for this boron-assisted RNA formation than Earth. This fascinating theory hints that primitive life might have actually started on Mars before meteorites carried it to our planet!</p>\n<div class="mw-heading mw-heading3">'

os.makedirs('src/ptable/data/drafts', exist_ok=True)
with open('src/ptable/data/drafts/Boron.json', 'w', encoding='utf-8') as f:
    json.dump(boron, f, indent=2)
