import json
import os

draft = {
    "extract_html": "<p><b>Praseodymium</b> (symbol <b>Pr</b>, atomic number 59) is a soft, silvery, and highly valued rare-earth metal. Known for its magnetic, electrical, and optical magic, it sits in the lanthanide series of the periodic table. While it's too eager to react with its surroundings to be found in its pure form in nature, it is widely used in our modern world. In fact, pure praseodymium slowly develops a cool green oxide coating when exposed to air! Though not known to ancient Indian metallurgists who worked with elements like gold and iron, today it holds immense strategic value. Under India's National Critical Mineral Mission, praseodymium is a key focus for its role in advanced technologies, with vital rare earth corridors being developed across states like Tamil Nadu, Odisha, and Kerala to secure the future of renewable energy and electric vehicles.</p>",
    "sections": {
        "Physical properties": "<p>Praseodymium is a soft, silvery metal that can be easily shaped and stretched. It is paramagnetic at room temperature, which means it is weakly attracted to magnets. Unlike some other rare-earth metals that have complicated magnetic behaviors at freezing temperatures, praseodymium keeps things simple and stays paramagnetic unless it gets extremely cold. It is strong and malleable, making it a wonderful ingredient for specialized metal alloys.</p>",
        "Chemical properties": "<p>When left out in the open air, praseodymium slowly tarnishes. Much like how iron forms rust, praseodymium grows a flaky green oxide crust; a small piece can completely corrode away in about a year! Because of this, it is usually stored in protective oil or sealed glass. It also reacts nicely with hot water to form praseodymium hydroxide, and it readily combines with all halogens (like chlorine and fluorine) to create various interesting salts. Most often, it prefers a '+3' oxidation state, giving its compounds a beautiful yellowish-green color that scientists love using to tint specialized glasses.</p>",
        "Isotopes": "<p>In nature, praseodymium is as pure as it gets: it has only one stable, naturally occurring form, known as praseodymium-141. This makes it what scientists call a 'monoisotopic' element. Its atomic core holds exactly 82 neutrons—a 'magic number' in physics that grants it extra stability. While researchers have created 38 other artificial, radioactive versions of praseodymium in labs, almost all of them break down in less than a minute. The longest-lasting artificial form is praseodymium-143, which sticks around for about 13 and a half days before decaying.</p>",
        "History": "<p>The story of praseodymium begins in the mid-1800s when European chemists were trying to untangle a mysterious earth called 'didymium'. For decades, they thought didymium was a single element. But in 1885, a clever Austrian chemist named Carl Auer von Welsbach managed to split it into two distinct new elements. Because one of them formed bright green salts, he named it 'praseodymium', combining the Greek words 'prasinos' (meaning leek-green) and 'didymos' (meaning twin). Its twin was named neodymium. Historically, ancient Indian alchemists (practitioners of <i>Rasashastra</i>) did not know of this element, as their profound metallurgical expertise focused on base and noble metals. However, the legacy of Indian metallurgy has evolved, and today Indian scientists are at the forefront of unlocking the secrets of rare earths like praseodymium.</p>",
        "Occurrence": "<p>Despite being called a 'rare-earth' metal, praseodymium isn't actually that rare! It is more common in the Earth's crust than elements like tin or boron. However, it is never found naturally by itself; it is always mingled with its rare-earth siblings like cerium, lanthanum, and neodymium. For India, this element is of massive geographical and strategic importance. India is home to about 6% of the world's rare earth reserves. Praseodymium is primarily extracted from a mineral called monazite, which is abundantly found in the coastal beach sands of Kerala, Tamil Nadu, Odisha, and Andhra Pradesh, as well as in inland deposits in Jharkhand and West Bengal. Recognizing its importance, India is developing 'Rare Earth Corridors' to seamlessly link the mining and processing of these vital sands.</p>",
        "Applications": "<p>Praseodymium has a colorful resume! In the 1920s, it was first used to give glass and ceramics a vibrant, warm yellow-orange hue known as 'Praseodymium Yellow.' Today, its uses are much more high-tech. Because of its unique light-filtering and glowing properties, it is essential in creating fiber optic cables, lasers, and even the safety goggles worn by welders and glassblowers. But its biggest claim to fame is its partnership with neodymium. Together, they form incredibly strong, durable permanent magnets (NdPr magnets) used in wind turbines, electric vehicle motors, and modern electronics. Indian scientific contributions are heavily focused on these applications. Modern Indian researchers are developing advanced sensors—such as cobalt-doped praseodymium orthoferrite for CO2 sensing—and supercapacitors for energy storage. Additionally, Indian chemical engineers are pioneering advanced solvent extraction techniques to efficiently separate praseodymium from its twin, neodymium, aiming to power the nation's clean energy revolution by 2030.</p>"
    }
}

os.makedirs('src/ptable/data/drafts', exist_ok=True)
with open('src/ptable/data/drafts/Praseodymium.json', 'w', encoding='utf-8') as f:
    json.dump(draft, f, indent=2)

print("Draft generated successfully.")
