import json
import os

extract_html = """<p><b>Ruthenium</b> is a rare, hard, silvery-white metal. It belongs to the platinum group of elements in the periodic table, meaning it shares many properties with platinum, like being highly resistant to rust and chemical attacks. Because of its toughness and ability to withstand high temperatures and corrosion, it is mostly used in electronics, such as electrical contacts and specialized resistors. It is also used to make metal alloys harder and in chemical processes as a catalyst. Discovered in 1844 by the Russian scientist Karl Ernst Claus, its name comes from "Ruthenia," the Latin word for Russia. While ancient civilizations were unaware of this element, modern science has found incredible uses for it, from advanced electronics to life-saving cancer treatments.</p>"""

sections = {
    "Physical properties": "<p>Ruthenium is a solid, hard, and shiny white metal that belongs to the platinum family. In the periodic table, it sits in group 8. It is very special because its outer electron shell only has one electron, unlike other similar metals that usually have two. This quirky arrangement doesn't change how it reacts with other chemicals, but it makes it a fascinating element for scientists to study. Ruthenium is incredibly tough, melting at a very high temperature of 2,334 &deg;C (4,233 &deg;F) and boiling at 4,150 &deg;C (7,502 &deg;F).</p>",
    
    "Chemical properties": "<p>Like other platinum-group metals, ruthenium is extremely stubborn when it comes to reacting with other chemicals. It doesn't tarnish or rust at room temperature, and it takes extreme heat (about 800 &deg;C) for it to react with oxygen. Normal acids won't melt it, though it can be broken down by certain harsh bleaching chemicals like sodium hypochlorite. When added in small amounts to other metals, such as platinum, palladium, or titanium, ruthenium acts like a super-shield, making the new metal mix much harder and more resistant to rust. Interestingly, ruthenium can hold on to a wide range of electrical charges (oxidation states), making it very versatile for different chemical reactions.</p>",
    
    "Isotopes": "<p>In nature, ruthenium exists as a mix of seven stable forms, known as isotopes. Scientists have also created over 30 artificial, radioactive isotopes of ruthenium in laboratories. While most of these radioactive versions break down (decay) very quickly&mdash;often in just a few minutes&mdash;some last a bit longer. For example, Ruthenium-106 is a radioactive version created from splitting uranium or plutonium, and it takes about a year to break down by half. This specific isotope has become highly important in the medical field.</p>",
    
    "Occurrence and Geography": "<p>Ruthenium is one of the rarest elements on Earth, ranking 78th in abundance in the Earth's crust. It is almost always found in tiny amounts mixed with other platinum-group metals in ores. The largest amounts are mined in the Ural Mountains of Russia, as well as in North America (Canada) and South Africa.</p><p>In India, there are no major commercial mines for ruthenium. While the Geological Survey of India (GSI) has found promising traces of platinum-group elements in places like Dras in Ladakh, the Baula-Nausahi complex in Odisha, Hanumalpur in Karnataka, and Sittampundi in Tamil Nadu, India still imports most of the ruthenium it needs for its high-tech industries.</p>",
    
    "History": "<p>For centuries, ancient civilizations, including the pre-Columbian peoples of the Americas, unknowingly used natural mixes of platinum metals. However, identifying ruthenium as a unique, separate element took a long time because it is so rare and hard to isolate. In 1827, scientists J&ouml;ns Berzelius and Gottfried Osann examined leftovers from Russian platinum but couldn't quite prove they had found a new element. Finally, in 1844, the Russian scientist Karl Ernst Claus succeeded. He isolated the metal at Kazan University and named it 'ruthenium' in honor of his homeland, Russia (from 'Ruthenia,' the Latin word for Russia).</p><p>Interestingly, while ancient India had a world-renowned metallurgical tradition&mdash;producing marvels like Wootz steel and the rust-resistant Iron Pillar of Delhi, which were well documented in ancient Sanskrit texts&mdash;ruthenium was completely unknown to them. It is a modern discovery that requires advanced chemistry to extract.</p>",
    
    "Applications and Modern Scientific Contributions": "<p>Today, ruthenium is a star in the electronics and chemical industries. About half of all ruthenium produced is used to make wear-resistant electrical contacts and thick-film resistors found in modern electronics. It is also used to harden the gold used in the tips of expensive fountain pens and is added to special superalloys used in jet engine turbines.</p><p>In modern science, particularly in India, ruthenium is making waves. The Bhabha Atomic Research Centre (BARC) in India achieved a major medical breakthrough by developing affordable, indigenous Ruthenium-106 (Ru-106) plaques to treat eye cancers, saving many lives and reducing reliance on expensive imports. Furthermore, scientists at Indian Institutes of Technology (IITs) and other research centers are actively studying new ruthenium-based drugs as less toxic alternatives to traditional cancer treatments. Indian researchers are also at the forefront of using ruthenium nanoparticles in green chemistry, helping to reduce pollution, and in cutting-edge physics to develop the next generation of electronic devices.</p>"
}

draft = {
    "extract_html": extract_html,
    "sections": sections
}

with open('src/ptable/data/drafts/Ruthenium.json', 'w', encoding='utf-8') as f:
    json.dump(draft, f, indent=2, ensure_ascii=False)

print("Draft saved successfully.")
