import json
import os

with open("src/ptable/data/master_elements.json", "r", encoding="utf-8") as f:
    data = json.load(f)

tl = data["Tl"]

tl["extract_html"] = "<p><b><a href=\"/school1/ptable/element/Tl\" class=\"wiki-link\" title=\"Thallium (Tl)\">Thallium</a></b> (symbol <b>Tl</b>, atomic number 81) is a soft, silvery-white heavy metal that looks a lot like <a href=\"/school1/ptable/element/Pb\" class=\"wiki-link\" title=\"Lead (Pb)\">lead</a> but acts very differently. Originally discovered from its bright green flame (its name means \"green shoot\"), it has gained a dark reputation as \"the poisoner's poison\" because its salts are colorless, odorless, and tasteless. While its extreme toxicity means it's heavily regulated and banned as a household poison, it still plays surprising roles in specialized electronics, optics, and even medical imaging. In India, it's notorious not just for high-profile criminal cases, but it's also a subject of serious clinical research for finding better antidotes and treatments.</p>"

tl["sections"] = {
    "Characteristics": "<p><a href=\"/school1/ptable/element/Tl\" class=\"wiki-link\" title=\"Thallium (Tl)\">Thallium</a> is a very soft metal—so soft you can cut it with a butter knife at room temperature! When freshly cut, it has a beautiful metallic shine, but the moment it touches the air, it quickly tarnishes to a dull, bluish-gray color, much like <a href=\"/school1/ptable/element/Pb\" class=\"wiki-link\" title=\"Lead (Pb)\">lead</a>. To protect it, scientists usually store thallium under a layer of oil. Chemically, it's quite strange; although it sits near heavy metals in the periodic table, it sometimes behaves more like <a href=\"/school1/ptable/element/K\" class=\"wiki-link\" title=\"Potassium (K)\">potassium</a>. This chemical \"disguise\" is exactly what makes it so dangerous—it can easily sneak into living cells that are looking for potassium, causing chaos from within.</p>",
    "Isotopes": "<p>In nature, <a href=\"/school1/ptable/element/Tl\" class=\"wiki-link\" title=\"Thallium (Tl)\">thallium</a> consists mainly of two stable isotopes, Thallium-203 and Thallium-205. However, scientists have identified over 40 different isotopes! The most famous artificial one is <b>Thallium-201</b>. Despite the element's overall toxicity, this specific radioactive isotope is incredibly useful in modern medicine. Because it emits easily detectable X-rays and gamma rays, doctors around the world—including in advanced cardiology centers in India—use Thallium-201 for nuclear cardiac stress tests. By injecting a tiny, safe amount into a patient, doctors can get a brilliant map of blood flow to the heart, helping to diagnose heart disease.</p>",
    "History": "<p><a href=\"/school1/ptable/element/Tl\" class=\"wiki-link\" title=\"Thallium (Tl)\">Thallium</a> was discovered in 1861 by two scientists, William Crookes and Claude Auguste Lamy, who were independently studying the glowing light emitted by certain minerals (a technique called flame spectroscopy). They noticed a brilliant, previously unseen green line in the spectrum, leading them to name the new element <i>thallos</i>, the Greek word for a \"green shoot or twig.\" For many decades, thallium was widely used as a highly effective rat poison and ant killer. However, its extreme danger to humans—often resulting in tragic accidents and intentional poisonings—led to global bans starting in the 1970s. In India, thallium has a darker modern history. Due to its tasteless and odorless nature, it has been involved in shocking criminal cases, such as the 2021 Delhi \"fish curry\" poisoning. This notoriety has prompted extensive research by Indian medical and forensic experts, who have developed specialized protocols using <b>Prussian blue</b>—the same vibrant blue pigment used by painters—as a highly effective antidote to flush the poison out of the body.</p>",
    "Applications": "<p>Today, because of its severe toxicity, you won't find <a href=\"/school1/ptable/element/Tl\" class=\"wiki-link\" title=\"Thallium (Tl)\">thallium</a> in everyday consumer products. However, it is highly valued in high-tech industries! Special thallium compounds are used to make infrared detectors, specialized camera lenses, and high-density glass that bends light in unique ways. In the natural environment, thallium is not found on its own but is usually extracted as a byproduct when refining ores like <a href=\"/school1/ptable/element/Cu\" class=\"wiki-link\" title=\"Copper (Cu)\">copper</a> and <a href=\"/school1/ptable/element/Pb\" class=\"wiki-link\" title=\"Lead (Pb)\">lead</a>. Interestingly, environmental studies in India have found elevated traces of thallium in certain river sediments, such as the Kortalaiyar River in Tamil Nadu, serving as an important indicator of industrial pollution and helping authorities monitor water safety.</p>"
}

os.makedirs("src/ptable/data/drafts", exist_ok=True)
with open("src/ptable/data/drafts/Thallium.json", "w", encoding="utf-8") as f:
    json.dump({ "Tl": tl }, f, indent=4)
    
print("Done writing Thallium.json")
