$jsonPath = 'c:\projects\apache\school1\np_data.json'
$outPath = 'c:\projects\apache\school1\src\ptable\data\drafts\Neptunium.json'

$data = Get-Content -Raw $jsonPath | ConvertFrom-Json

$data.extract_html = '<p><b>Neptunium</b> is a fascinating synthetic, radioactive metal with the symbol <b>Np</b> and atomic number 93. Named after the planet Neptune—following uranium, which was named after Uranus—neptunium was the very first transuranic element to be artificially created. It sits in the actinide series of the periodic table, possessing a silvery metallic appearance when freshly prepared. Although it can be found in vanishingly small trace amounts in natural uranium ores, nearly all of the world''s neptunium is produced in nuclear reactors as a byproduct of uranium irradiation.</p>'

$data.sections.Characteristics = 'Neptunium is a hard, silvery actinide metal that tarnishes slowly in air. It boasts a notably high density of 20.45 g/cm³ and melts at a relatively low 639 °C (1182 °F), but it boils at a much higher extrapolated temperature of 4174 °C (7545 °F). One of its most intriguing physical properties is its ability to exist in three different crystal structures depending on the temperature (orthorhombic at room temperature, tetragonal, and body-centered cubic at higher temperatures). Chemically, it''s quite active, capable of exhibiting oxidation states ranging from +2 to +7, with +5 being the most common in solutions. Because it is radioactive, handling it requires specialized safety equipment.'

$data.sections.Isotopes = 'All isotopes of neptunium are radioactive, meaning none are completely stable. The most significant and longest-lived isotope is neptunium-237, which has a staggering half-life of 2.14 million years. It decays mostly by emitting alpha particles. Another important isotope is neptunium-239, which has a much shorter half-life of just 2.4 days. This short-lived isotope was the very first form of neptunium ever synthesized and is an important intermediate step in the creation of plutonium-239 in nuclear reactors.'

$data.sections.Occurrence = 'For a long time, neptunium was considered an entirely artificial element. However, trace amounts of neptunium-237 and neptunium-239 do occur naturally in uranium-bearing ores. These tiny traces are created by natural nuclear reactions when uranium atoms capture stray neutrons. Despite this, the natural occurrence is so microscopic that practically all neptunium used in scientific research today is synthetically produced as a byproduct in nuclear power plants, extracted from spent nuclear fuel.'

$data.sections.History = 'The story of neptunium is a landmark in nuclear science. It was discovered in 1940 by scientists Edwin McMillan and Philip H. Abelson at the Berkeley Radiation Laboratory in California. By bombarding uranium-238 with slow neutrons using a cyclotron, they successfully created neptunium-239, marking the discovery of the first element heavier than uranium (a transuranic element). Following the planetary naming theme started by uranium (Uranus), they named the new element after the next planet in the solar system, Neptune. McMillan was later awarded the Nobel Prize in Chemistry in 1951 for this groundbreaking discovery.'

$data.sections.Applications = 'While neptunium doesn''t have many everyday commercial uses, it plays a vital strategic and scientific role. Its primary application is serving as the raw material to produce plutonium-238, an essential power source used in Radioisotope Thermoelectric Generators (RTGs). These RTGs act as long-lasting nuclear batteries for deep-space missions, powering iconic spacecraft like the Voyager probes and the Curiosity rover. In specialized industrial and research settings, neptunium is also used in instruments designed to detect high-energy neutrons.<br><br><b>The Indian Context:</b> In India, neptunium has a special significance within the nation''s ambitious Three-Stage Nuclear Power Programme, originally envisioned by Dr. Homi J. Bhabha. In the first stage, Indian Pressurized Heavy Water Reactors (PHWRs) use natural uranium as fuel. The neutron irradiation in these reactors naturally produces neptunium and plutonium as byproducts. Managing and processing these transuranic elements is a critical capability developed at institutions like the Bhabha Atomic Research Centre (BARC). The mastery over these processes is essential as India transitions toward Fast Breeder Reactors and ultimately a closed nuclear fuel cycle, optimizing energy output and carefully managing nuclear waste.'

$data | ConvertTo-Json -Depth 10 | Set-Content -Path $outPath
