import json
import os

draft_dir = 'c:/projects/apache/school1/src/ptable/data/drafts'
os.makedirs(draft_dir, exist_ok=True)

with open('c:/projects/apache/school1/src/ptable/data/master_elements.json', 'r', encoding='utf-8') as f:
    master = json.load(f)

rb = master['Rb']

rb['extract_html'] = "<p>Rubidium (symbol <strong>Rb</strong>, atomic number 37) is a very soft, silvery-white metal that belongs to the alkali metal family. Like its chemical cousins potassium and sodium, it is highly reactive. It is the first alkali metal in its group to be heavier than water. While ancient Indian alchemical texts (<em>Rasashastra</em>) intricately described the 'metals of antiquity' such as gold, silver, iron, and mercury, rubidium remained hidden from the world until modern times. Today, however, it plays a starring role in advanced Indian scientific research. For instance, the groundbreaking theories of Indian physicist Satyendra Nath Bose laid the foundation for the Bose-Einstein condensate, a state of matter first achieved using rubidium atoms! On Earth, it exists naturally as two isotopes, one of which is slightly radioactive with a half-life far longer than the age of the universe.</p>"

rb['sections'] = {
    'Characteristics': "Rubidium is a fascinating element with extreme behaviors, known for its softness, vivid color in a flame, and intense reactivity. It shares many characteristics with other alkali metals like potassium and caesium.",
    
    'Physical properties': "Rubidium is a very soft, ductile, silvery-white metal that you could easily cut with a butter knife. It melts at just 39.3 °C (102.7 °F), which means it would melt on a hot summer day in many parts of India! When heated to 688 °C (1,270 °F), it boils into a vapor. It easily forms mixtures, called amalgams or alloys, with metals like mercury, gold, iron, sodium, and potassium. When you put a tiny amount of rubidium in a flame, it produces a beautiful, bright purple-red color. This color is very similar to potassium's flame, so scientists use advanced tools like spectroscopes to tell them apart.",
    
    'Chemical properties': "Chemically, rubidium is incredibly eager to react with other elements. It is the second most electropositive (electron-donating) of the stable alkali metals. Because of this strong desire to react, dropping rubidium into water causes an explosive chemical reaction! It reacts violently, sinking in the water while producing hydrogen gas and rubidium hydroxide. The reaction is so vigorous that it usually bursts into flames, igniting the escaping hydrogen gas. Rubidium is so reactive that it can even catch fire spontaneously just by being exposed to the air. Therefore, it must be carefully stored in special mineral oils or in a vacuum to prevent it from reacting.",
    
    'Isotopes': "In nature, rubidium is found in two forms, called isotopes. About 72% of it is rubidium-85, which is perfectly stable. The remaining 28% is rubidium-87, which is slightly radioactive. However, you don't need to worry about its radioactivity! Rubidium-87 decays incredibly slowly, with a 'half-life' of 48.8 billion years—that's more than three times the estimated age of the entire universe! Because it decays at such a steady, slow rate into an element called strontium, geologists around the world (and in institutions like the Geological Survey of India) use rubidium to figure out the age of ancient rocks. By measuring the ratio of rubidium to strontium in a rock, they can trace the tectonic and geological history of places like the Peninsular Indian shield. Other artificial, highly radioactive isotopes of rubidium have been created in labs, but they last for only minutes or days.",
    
    'Occurrence': "Rubidium isn't the most abundant element, but it is more common in the Earth's crust than metals like copper or zinc. It is naturally found mixed into minerals like leucite, pollucite, and lepidolite. Lepidolite, a type of lithium-rich mica, is the main commercial source for rubidium. In India, geological explorations in regions such as the Govindpal area of Chhattisgarh's Bastar district have revealed lepidolite deposits with notable concentrations of rubidium. Furthermore, researchers are actively exploring geothermal systems, such as those in the Puga Valley of Eastern Ladakh, for potential rare metal enrichment, including rubidium. In the oceans, seawater contains a tiny but measurable amount of rubidium as well.",
    
    'History': "Rubidium was discovered in 1861 by two brilliant German scientists, Robert Bunsen and Gustav Kirchhoff. They found it using a brand-new tool they had just invented: the spectroscope, which identifies elements based on the unique colors of light they emit. When they analyzed the mineral lepidolite, they noticed striking deep red lines in the spectrum. Because of these bright red lines, they named the new element 'rubidium,' from the Latin word <em>rubidus</em>, meaning 'deep red'. They went to great lengths to study it, processing 150 kilograms of ore just to get a tiny pinch of rubidium salts! For many decades, rubidium remained a scientific curiosity with few practical uses. But its true potential was unlocked in the modern era of quantum physics. In 1995, rubidium-87 was cooled to near absolute zero to create a 'Bose-Einstein condensate'—a bizarre state of matter predicted decades earlier by Albert Einstein and Indian physicist Satyendra Nath Bose. This incredible achievement earned its creators the Nobel Prize in Physics in 2001, cementing Bose's and rubidium's intertwined legacy in the history of science.",
    
    'Applications': "Today, rubidium is a superstar in high-tech research and electronics. Because it is easily turned into a vapor and interacts perfectly with lasers, it is one of the most popular elements for laser cooling and studying quantum mechanics. Recently, researchers at the Raman Research Institute (RRI) in Bengaluru, India, have conducted groundbreaking experiments using ultra-cooled rubidium atoms to study 'Rydberg states,' which is crucial for building future quantum computers and advanced sensors. Rubidium is also used in atomic clocks, which are incredibly precise timekeepers essential for GPS satellites and telecommunications networks. It helps polarize gases for medical imaging, acts as a 'getter' to remove unwanted gases in vacuum tubes, and is used in special types of glass. In medicine, a short-lived isotope called rubidium-82 acts very much like potassium in the human body, allowing doctors to use it in PET scans to safely image the heart's blood flow and locate brain tumors. There has even been research into using rubidium supplements to help treat conditions like depression, showing just how versatile this 'deep red' element truly is."
}

out_file = os.path.join(draft_dir, 'Rubidium.json')
with open(out_file, 'w', encoding='utf-8') as f:
    json.dump(rb, f, indent=2, ensure_ascii=False)

print('Saved successfully to ' + out_file)
