import json
import os

input_file = r'c:\projects\apache\school1\scratch_lanthanum.json'
output_file = r'c:\projects\apache\school1\src\ptable\data\drafts\Lanthanum.json'

with open(input_file, 'r', encoding='utf-8') as f:
    data = json.load(f)

data['extract_html'] = """<p><b><a href=\"/school1/ptable/element/La\" class=\"wiki-link\" title=\"Lanthanum (La)\">Lanthanum</a></b> (symbol <b>La</b>, atomic number 57) is a soft, silvery-white metal that gives its name to the entire \"lanthanide\" series of the periodic table. It is highly reactive, meaning it is never found pure in nature, but instead hides within rich mineral sands like monazite and bastnäsite. Lanthanum is a modern technological marvel, secretly powering everything from the high-end camera lenses in our smartphones to the massive batteries in hybrid electric vehicles. In India, lanthanum holds immense strategic importance due to the country's vast coastal reserves of monazite sand, placing it at the heart of the nation's push for self-reliance in rare-earth technologies.</p>"""

data['sections'] = {
    'Characteristics': """<p><a href=\"/school1/ptable/element/La\" class=\"wiki-link\" title=\"Lanthanum (La)\">Lanthanum</a> is the prototype of the lanthanide series. It is a soft, malleable metal—so soft you can easily cut it with a knife! When freshly cut, it shines with a brilliant silvery-white metallic luster, but it quickly tarnishes and oxidizes when exposed to air, turning dark. Because it is highly reactive, it even reacts with water to form lanthanum hydroxide and hydrogen gas. Despite its name being part of the \"rare earth\" elements, lanthanum is actually quite common in the Earth's crust—it is nearly three times as abundant as <a href=\"/school1/ptable/element/Pb\" class=\"wiki-link\" title=\"Lead (Pb)\">lead</a>. However, it is challenging to separate from its neighboring rare-earth metals.</p>""",
    
    'Isotopes': """<p>In nature, <a href=\"/school1/ptable/element/La\" class=\"wiki-link\" title=\"Lanthanum (La)\">lanthanum</a> is primarily made up of two isotopes: stable Lanthanum-139 (which makes up about 99.91% of natural lanthanum) and primordial, long-lived radioactive Lanthanum-138 (making up the remaining 0.09%). Lanthanum-138 has an incredibly long half-life of over 100 billion years—much older than the universe itself! Scientists have also created dozens of artificial, highly radioactive isotopes in laboratories, though most of them decay away in just a few minutes or hours.</p>""",
    
    'History': """<p>The element was discovered in 1839 by the Swedish chemist Carl Gustaf Mosander. While studying a mineral called cerite, Mosander noticed an impurity that he successfully extracted by treating the mineral with dilute nitric acid. He named this new substance <i>lanthana</i>, from the Ancient Greek word <i>lanthanein</i>, which translates to \"to lie hidden\"—a perfect name for an element so difficult to find and isolate! For many decades, isolating pure lanthanum was incredibly difficult until modern chemical processes were developed.<br><br>In the Indian context, the history of lanthanum is deeply intertwined with the discovery of massive <b>monazite sand</b> deposits along the coasts of Kerala, Tamil Nadu, and Odisha. In the early 20th century, these rich beach sands drew global attention. Recognizing their strategic value, India established Indian Rare Earths Limited (IREL) in 1950. Operating facilities like the Rare Earth Refining Unit in Aluva, Kerala, India took control of its domestic lanthanum and rare-earth processing, ensuring these \"hidden\" elements played a vital role in national development.</p>""",
    
    'Applications': """<p><a href=\"/school1/ptable/element/La\" class=\"wiki-link\" title=\"Lanthanum (La)\">Lanthanum</a> is the silent engine of modern green technology and high-end optics. Its most famous application is in the massive Nickel-Metal Hydride (NiMH) batteries that power millions of hybrid electric cars worldwide; a single hybrid car battery can contain over 10 kilograms of lanthanum! When added to glass, lanthanum oxide improves the refractive index, which is why it is widely used to manufacture professional camera lenses, telescope optics, and even the glass in modern smartphone cameras.<br><br>In India, lanthanum is critical to the country's <b>\"Mine-to-Magnet\"</b> and rare-earth corridor initiatives. Through state-owned IREL's Rare Earth Extraction Plant (REEP) in Odisha, India actively processes lanthanum to reduce dependence on foreign imports. Beyond green tech, lanthanum is famously found in your pocket: it is a key ingredient in <i>mischmetal</i>, a special alloy used to make the sparking flints in everyday lighters!</p>""",
    
    'Biological role': """<p>For most of history, scientists believed that <a href=\"/school1/ptable/element/La\" class=\"wiki-link\" title=\"Lanthanum (La)\">lanthanum</a> had absolutely no biological role in any living organism. In human medicine, its main use is actually pharmacological: a compound called lanthanum carbonate is prescribed to patients with severe kidney disease to help absorb excess phosphate from their diet. However, in a surprising recent discovery, scientists found that certain unique bacteria (called methanotrophs) living in extreme volcanic mudpots actually rely on lanthanum as a vital nutrient! These bacteria use lanthanum as a cofactor for an enzyme that helps them consume methane gas, proving that even \"rare earths\" can be the secret to life for some of Earth's most resilient microbes.</p>"""
}

os.makedirs(os.path.dirname(output_file), exist_ok=True)
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4)
print("Saved to", output_file)
