import json
import os

with open('c:/projects/apache/school1/li_data.txt', 'r', encoding='utf-8') as f:
    data = json.load(f)

data['extract_html'] = """<p><strong>Lithium</strong> (from the Greek word <em>lithos</em>, meaning &quot;stone&quot;) is a fascinating chemical element with the symbol <strong>Li</strong> and atomic number 3. As a soft, silvery-white metal belonging to the alkali metal group, it holds the remarkable title of being the lightest metal and the least dense solid element on Earth under standard conditions. Because it is highly reactive, you will never find it freely in nature; instead, it is always locked away in minerals and salts.</p>"""

data['sections'] = {
    'Isotopes': """<p>In nature, lithium comes in two stable forms, or isotopes: <sup>6</sup>Li and <sup>7</sup>Li. The vast majority (about 95.15%) is <sup>7</sup>Li. Interestingly, these natural isotopes have unusually low nuclear binding energy compared to their neighbors, helium and beryllium. In fact, lithium is the only light element that can produce net energy through nuclear fission! Because of this unique trait, lithium is surprisingly less common in our Solar System than 28 of the first 34 chemical elements, despite being incredibly light.</p><p>Scientists have also discovered seven radioactive isotopes of lithium, though they are highly unstable. The longest-lived is <sup>8</sup>Li, with a half-life of just 838 milliseconds, while the shortest-lived, <sup>4</sup>Li, vanishes in a tiny fraction of a second. Lithium's isotopes behave differently during natural processes like mineral formation and metabolism, meaning they naturally separate over time. This separation is also done artificially; for example, the lighter <sup>6</sup>Li isotope has been heavily used in nuclear physics and weapons manufacturing. This has slightly altered the natural ratio of lithium isotopes on Earth, making its standard atomic weight a bit tricky to pin down!</p>""",
    
    'Occurrence': """<p>Because lithium is highly reactive, it never exists as a pure metal in nature. Instead, it is found hidden in mineral-rich rocks and brines. The primary sources of lithium are pegmatite minerals, such as spodumene, petalite, and lepidolite. Today, a huge portion of the world's lithium comes from natural salt flats—particularly the &quot;Lithium Triangle&quot; spanning the Andes mountains in Argentina, Bolivia, and Chile. In these regions, lithium-rich brine is pumped to the surface and left to evaporate in massive, colorful solar ponds, leaving behind concentrated lithium salts that can be collected and processed.</p>""",

    'History': """<p>The story of lithium begins in 1800 when Brazilian scientist José Bonifácio de Andrada e Silva discovered the mineral petalite in a Swedish mine. But it wasn't until 1817 that Johan August Arfwedson, working in the lab of famous chemist Jöns Jakob Berzelius, realized this ore contained an entirely new element. Berzelius named the new substance &quot;lithion&quot; (from <em>lithos</em>, Greek for &quot;stone&quot;) because it was discovered in a rock, unlike sodium and potassium which were found in plants and animal blood. The element was officially named <strong>lithium</strong>.</p><p>Although early scientists knew lithium was there (noticing its bright red flame), they couldn't easily separate the pure metal. It was finally isolated in 1821 by British chemist William Thomas Brande using a process called electrolysis. Throughout the 20th century, lithium found a completely unexpected use in medicine. In 1949, Australian psychiatrist John Cade discovered its ability to treat mania, and it quickly became a revolutionary, non-patented treatment for bipolar disorder. During the Cold War, lithium production soared as the US and other nations used its isotopes to produce tritium for nuclear fusion weapons.</p>""",

    'Applications': """<p>Lithium is often called the &quot;white gold&quot; of the modern world because it is absolutely essential to today's technology and the global energy transition. Its most famous application is in <strong>lithium-ion batteries</strong>. Because lithium is extremely light and holds a significant electrical charge, these batteries are perfect for powering smartphones, laptops, and electric vehicles (EVs), as well as storing energy from renewable sources like solar and wind.</p><p>Beyond batteries, lithium has several other critical industrial uses. It is added to glass and ceramics to make them resistant to sudden temperature changes—perfect for stovetops and lab equipment. In aviation, it is mixed with aluminum and magnesium to create super-strong, lightweight alloys for aircraft. Additionally, lithium-based greases are highly prized as lubricants because they can withstand extreme temperatures without breaking down. Finally, lithium carbonate continues to be a life-changing pharmaceutical, remaining one of the most effective treatments for bipolar disorder.</p>"""
}

os.makedirs('c:/projects/apache/school1/src/ptable/data/drafts', exist_ok=True)
with open('c:/projects/apache/school1/src/ptable/data/drafts/Lithium.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
