import json
import os

with open('eu_scratch.json', encoding='utf-8') as f:
    data = json.load(f)

data['extract_html'] = '''<p>Europium is a chemical element with the symbol <strong>Eu</strong> and atomic number 63. It belongs to the lanthanide series of rare-earth elements and is known as the softest, least dense, and most chemically reactive of the group—so soft it can be easily cut with a knife! Its most famous superpower is glowing brightly when used in phosphorescent materials. It is what gave older color televisions their vibrant red colors, and it is even used as an anti-counterfeiting measure in euro banknotes. In India, trace amounts of europium are found in the monazite sands along the coasts of Kerala, Tamil Nadu, and Odisha, connecting this fascinating element to local geology and modern Indian scientific research.</p>'''

data['sections']['Physical properties'] = '''<p>Europium is a soft, silvery-white metal. It is about as soft as lead, meaning it can be dented and cut quite easily. It forms a basic "body-centered cubic" crystal structure. Among its rare-earth neighbors, europium stands out because its atoms take up a relatively large amount of space. This unusual trait happens because its electrons are arranged in a way that makes it act a bit differently, giving it unique magnetic properties.</p>'''

data['sections']['Chemical properties'] = '''<p>Europium is the most reactive of all the rare-earth elements. If you leave a shiny piece of europium out in the air, it quickly reacts with oxygen and tarnishes, completely oxidizing in just a few days. It also reacts violently with water—much like calcium does—to produce hydrogen gas. Because it is so eager to react, scientists rarely get to see its pure, shiny metallic form unless it is carefully stored under special mineral oil. If heated to between 150 and 180 °C, europium will literally catch fire in the air! It also dissolves easily in certain acids, forming beautiful pale pink solutions.</p>'''

data['sections']['Isotopes'] = '''<p>In nature, europium is mostly made of two main types (or isotopes): Europium-151 and Europium-153. They exist in almost equal amounts. While Europium-153 is perfectly stable, Europium-151 is very slightly radioactive. However, its radioactivity is so weak and slow that it takes billions of years to decay, making it practically harmless. Scientists have also created several artificial, highly radioactive isotopes of europium in laboratories, but these break down very quickly, mostly in a matter of days or minutes.</p>'''

data['sections']['Occurrence'] = '''<p>You will not find europium sitting freely in nature. Instead, it is locked away in various minerals like bastnäsite and monazite. In <strong>India</strong>, monazite is prominently found in the famous coastal beach sands of states like Kerala, Tamil Nadu, Andhra Pradesh, and Odisha. Because these sands contain valuable elements like thorium (crucial for India's nuclear energy program) and rare earths like europium, their mining and processing are carefully managed by the Indian government through IREL (India) Limited.</p>
<p>In geology, scientists study the "europium anomaly"—how much europium is in a rock compared to other rare-earth elements—to understand how ancient magmas cooled and formed rocks. Even out in space, astronomers look for the signature of europium in stars to figure out when and how those stars were born!</p>'''

data['sections']['History'] = '''<p>Because rare-earth elements naturally mix together in rocks and behave very similarly, early scientists had a remarkably tough time telling them apart. In 1885, William Crookes noticed some strange, unknown glowing lines when studying rare-earth minerals. By 1896, French chemist Eugène-Anatole Demarçay suspected that samples of a recently discovered element called samarium were actually hiding another unknown element. Demarçay finally managed to separate it in 1901 and named it "europium" after the continent of Europe.</p>'''

data['sections']['Applications'] = '''<p>Europium has some very specialized, brilliant uses—literally! Its most famous application relies on its ability to glow (phosphoresce). It is the magical ingredient that provided the bright red colors in traditional tube televisions and helps create the crisp, white light in modern fluorescent bulbs.</p>
<p>Today, <strong>Indian scientists and research institutions</strong> are actively researching europium-doped materials to develop better LEDs, advanced lasers, and cutting-edge tools for bio-imaging. In medicine, europium compounds are used to tag antibodies, helping doctors detect specific diseases with laser-excited fluorescence. Because it glows brightly under UV light, europium is even printed on euro banknotes as a hidden anti-counterfeiting security feature. Furthermore, europium is highly valued in nuclear research for its excellent ability to absorb neutrons, making it useful in the control rods of nuclear reactors.</p>'''

os.makedirs('src/ptable/data/drafts', exist_ok=True)
with open('src/ptable/data/drafts/Europium.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2)
