import json
import os

with open("Be_extract.json", "r", encoding="utf-8") as f:
    data = json.load(f)

data["extract_html"] = """<p><a href="/school1/ptable/element/Be" class="wiki-link" title="Beryllium (Be)">Beryllium</a> is a fascinating chemical element with the symbol <strong>Be</strong> and atomic number 4. Born in the depths of space through the collisions of cosmic rays, it remains a relatively rare element in the universe. On Earth, this highly reactive metal never exists on its own; it is always found locked away within colorful minerals, bound in combination with other elements.</p>"""

data["sections"]["Characteristics"] = "</div>\n<div class=\"mw-heading mw-heading3\">"

data["sections"]["Physical properties"] = """</div>
<p>Beryllium is a hard, steel-gray metal that is brittle at room temperature. It boasts a close-packed hexagonal crystal structure and an exceptional stiffness (Young's modulus of 287 GPa)—making it about 35% stiffer than steel! Despite this incredible rigidity, beryllium is remarkably lightweight. This unique combination of stiffness and low density allows sound to travel through beryllium at a staggering speed of 12.9 km/s at room conditions.</p>
<p>When it comes to handling heat, beryllium is unmatched. It dissipates the most heat per unit weight of any metal, thanks to its incredibly high specific heat (1925 J·kg<sup>−1</sup>·K<sup>−1</sup>) and excellent thermal conductivity (216 W·m<sup>−1</sup>·K<sup>−1</sup>). Furthermore, it has a very low coefficient of linear thermal expansion (11.4×10<sup>−6</sup> K<sup>−1</sup>). This means that even under extreme temperature changes, beryllium won't easily warp or change shape, making it incredibly stable.</p>
<div class="mw-heading mw-heading3\">"""

data["sections"]["Occurrence"] = """</div>
<p>Beryllium is hidden within more than 100 different minerals, though most of them are quite rare. Some of the more common beryllium-bearing minerals include bertrandite, beryl, chrysoberyl, and phenakite. You might even own some beryllium yourself, as precious forms of beryl include beloved gemstones like aquamarine, red beryl, and emerald! The signature vivid green of an emerald is actually caused by a tiny dash of chromium (about 2%) mixed into the beryl crystal.</p>
<p>The two primary ores mined for beryllium are beryl and bertrandite, which are primarily found in Argentina, Brazil, India, Madagascar, Russia, and the United States. Global reserves of this precious ore are estimated to be over 400,000 tonnes.</p>
<p>Across the cosmos, beryllium is quite rare; the Sun contains a mere 0.1 parts per billion (ppb) of it. Here on Earth, it is the 47th most abundant element in the crust, found at concentrations of 2 to 6 parts per million (ppm). It is most concentrated in soils (around 6 ppm), while trace amounts of the isotope <sup>9</sup>Be drift through our atmosphere. In the oceans, beryllium is incredibly scarce at just 0.2 to 0.6 parts per trillion, though it is slightly more abundant in freshwater streams at about 0.1 ppb.</p>
<div class="mw-heading mw-heading2\">"""

data["sections"]["Chemical properties"] = """</div>
<p>An atom of beryllium has the electronic configuration [He] 2s<sup>2</sup>. It typically exhibits an oxidation state of +2, meaning it shares its two outer electrons. Because beryllium atoms and ions are incredibly small, they have very high ionization potentials and do not form simple +2 ions. Instead, beryllium forms strong covalent bonds and often links together into polymer-like chains, such as in solid beryllium chloride (BeCl<sub>2</sub>). Chemically, it shares a fascinating "diagonal relationship" with aluminum, meaning the two elements behave in remarkably similar ways. Furthermore, beryllium is uniquely attracted to electron-rich areas, generating weak intermolecular bonds similar to hydrogen bonding.</p>
<p>In everyday conditions, beryllium protects itself from the air by instantly forming a microscopically thin (1 to 10 nanometers) shield of beryllium oxide on its surface, which can thicken to about 25 nm over time. This armor prevents further reaction. However, if heated above 500 °C, the oxygen begins to penetrate deeper into the metal. If ignited above 2500 °C, beryllium bursts into a brilliant flame, leaving behind a mix of beryllium oxide and beryllium nitride. Like aluminum, it easily dissolves in non-oxidizing acids (such as hydrochloric acid and diluted sulfuric acid) and alkaline solutions, but it shrugs off water and nitric acid thanks to its protective oxide shield.</p>
<p>Beryllium combines with other elements to form a wide variety of fascinating structures. In their solid states, many of these binary compounds form polymers. For example, beryllium fluoride (BeF<sub>2</sub>) forms a structure similar to silica with connected tetrahedra, while beryllium chloride and bromide form long chain-like structures. Beryllium oxide (BeO) is a heat-resistant (refractory) white solid with a wurtzite crystal structure, and it surprisingly conducts heat just as well as some metals! Other compounds include beryllium sulfide, selenide, and telluride (which have a zincblende structure), as well as high-melting-point beryllium nitride (Be<sub>3</sub>N<sub>2</sub>) and structurally similar beryllium phosphide (Be<sub>3</sub>P<sub>2</sub>). There are also various beryllium borides (like Be<sub>5</sub>B and BeB<sub>12</sub>) and beryllium azide (BeN<sub>6</sub>). Beryllium carbide (Be<sub>2</sub>C) is a striking brick-red compound that reacts with water to produce methane gas. Beryllium even forms tiny nanoclusters with silicon! While usually found in a +2 state, scientists have also discovered incredibly rare complexes where beryllium exhibits +1 or even 0 oxidation states.</p>
<div class="mw-heading mw-heading3\">"""

data["sections"]["History"] = """</div>
<p>Humans have prized beryllium-containing minerals for thousands of years. As far back as the Ptolemaic dynasty of ancient Egypt, people treasured beryl and emeralds, and an ancient manuscript called the Papyrus Graecus Holmiensis even details how to create artificial versions of these gems! For a long time, early scientists believed these stones were simply forms of aluminum silicate. It wasn't until mineralogist René Just Haüy noticed their identical crystal shapes that he asked chemist Louis-Nicolas Vauquelin to investigate further.</p>
<p>In 1798, Vauquelin discovered a brand new element hidden inside the emeralds. At first, it was named "glucine" because some of its compounds tasted sweet (though we now know they are highly toxic!). The name <i>beryllium</i> was introduced by Friedrich Wöhler in 1828, but both names were used interchangeably until 1949, when "beryllium" was officially adopted globally.</p>
<p>The pure metal itself was finally isolated in 1828 by two scientists, Friedrich Wöhler and Antoine Bussy, working entirely independently. Wöhler achieved this by layering beryllium chloride and highly reactive potassium in a platinum crucible and heating it with a simple alcohol lamp. The reaction burned brilliantly white-hot, leaving behind a fine, dark-gray metallic powder that he couldn't even melt! True pure beryllium (99.5%) was later achieved in 1898 by Paul Lebeau using electrolysis.</p>
<p>One of beryllium's most famous historical moments occurred in 1932. When scientist James Chadwick bombarded a sample of beryllium with alpha particles, he observed a strange new radiation—which led directly to his Nobel Prize-winning discovery of the neutron!</p>
<p>In the 1920s, beryllium was incredibly expensive, costing an astronomical $5,000 per pound, but improved extraction methods dropped the price to $50 by 1931. Demand for the metal skyrocketed during World War II for use in strong beryllium-copper alloys and as green-glowing phosphors in early fluorescent lights (though it was later replaced when its toxicity was discovered). By 1957, pure beryllium became widely commercially available. Today, it is mostly produced by reacting beryllium fluoride with magnesium, with the United States acting as the leading global producer.</p>
<div class="mw-heading mw-heading3\">"""

data["sections"]["Applications"] = """</div>
<p>Although you rarely see pure beryllium in everyday life, it is a critical "behind-the-scenes" material in modern technology and industry. It is most commonly mixed with metals like copper or aluminum to create specialized alloys. Beryllium-copper, for example, is highly conductive, incredibly strong, and uniquely "non-sparking"—making it an essential material for heavy-duty industrial tools used in explosive environments like oil rigs.</p>
<p>Because it is so stiff, lightweight, and stable across wild temperature changes, beryllium is a superstar in the aerospace and defense sectors. It is heavily used in the construction of supersonic aircraft, military sensors, and satellites. Most famously, the breathtaking golden mirrors of the <strong>James Webb Space Telescope</strong> are carved from solid beryllium, allowing them to remain perfectly rigid and functional in the freezing vacuum of deep space.</p>
<p>Beryllium is also nearly transparent to X-rays! This unique trait makes incredibly thin beryllium foils the perfect window material for X-ray machines and advanced medical imaging equipment, allowing the rays to pass through clearly without being absorbed. Furthermore, because of its unique interaction with neutrons (first discovered back in 1932), it is still highly valued today as a moderator and reflector in nuclear reactors, helping to control and sustain nuclear reactions.</p>
<div class="mw-heading mw-heading3\">"""

os.makedirs("src/ptable/data/drafts", exist_ok=True)
with open("src/ptable/data/drafts/Beryllium.json", "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)
