import json
import os

with open('c:/projects/apache/school1/scratch_mt.json', encoding='utf-8') as f:
    d = json.load(f)
mt = d['Mt']

mt['extract_html'] = """<p><b><a href="/school1/ptable/element/Mt" class="wiki-link" title="Meitnerium (Mt)">Meitnerium</a></b> is a highly radioactive, synthetic superheavy element with the symbol <b>Mt</b> and atomic number 109. You won't find it in nature; it can only be created in highly advanced laboratories by smashing atoms together at incredible speeds! First synthesized in 1982 by a German research team, it honors the brilliant nuclear physicist Lise Meitner, one of the pioneers of nuclear fission. Because it decays away in just a matter of seconds (its most stable known isotope has a half-life of only 4.5 seconds!), scientists have never been able to observe a chunk of it. However, it sits in group 9 of the periodic table, and is predicted to be a solid metal sharing similarities with elements like <a href="/school1/ptable/element/Co" class="wiki-link" title="Cobalt (Co)">cobalt</a> and <a href="/school1/ptable/element/Ir" class="wiki-link" title="Iridium (Ir)">iridium</a>.</p>"""

mt['sections'] = {
    'History': """<p>The story of <a href="/school1/ptable/element/Mt" class="wiki-link" title="Meitnerium (Mt)">meitnerium</a> begins in August 1982 at the GSI Helmholtz Centre for Heavy Ion Research in Darmstadt, Germany. A team led by Peter Armbruster and Gottfried Münzenberg successfully created a single atom of the element by bombarding a target of <a href="/school1/ptable/element/Bi" class="wiki-link" title="Bismuth (Bi)">bismuth</a>-209 with accelerated nuclei of <a href="/school1/ptable/element/Fe" class="wiki-link" title="Iron (Fe)">iron</a>-58. It took a week of continuous bombardment to produce just one atom! In 1997, it was officially named meitnerium to honor the Austrian-Swedish physicist <b>Lise Meitner</b>, who played a crucial role in the discovery of nuclear fission. Naming an element after her was a fitting tribute to her groundbreaking work, which changed the course of nuclear physics forever. While meitnerium itself was discovered in Germany, the quest to understand superheavy elements is a global effort. Today, Indian scientists and institutions, such as the Indian Institute of Technology (IIT) Roorkee and the Saha Institute of Nuclear Physics, are actively contributing to the theoretical models of superheavy element synthesis. Recently, researchers from IIT Roorkee even participated in the international discovery of a new superheavy isotope, <a href="/school1/ptable/element/Sg" class="wiki-link" title="Seaborgium (Sg)">seaborgium</a>-257, continuing the legacy of expanding the periodic table's frontiers.</p>""",
    'Isotopes': """<p>Because <a href="/school1/ptable/element/Mt" class="wiki-link" title="Meitnerium (Mt)">meitnerium</a> is a synthetic element, it has no stable or naturally occurring isotopes. Every single atom of it has to be artificially created in a lab, either by directly fusing two lighter atoms together or by watching even heavier, newly created elements decay into it. So far, scientists have identified eight different radioactive isotopes of meitnerium, with mass numbers ranging from 266 to 278 (along with an unconfirmed isotope at 282). None of them stick around for long! The most stable confirmed isotope is meitnerium-278, and it has a half-life of just 4.5 seconds. When these isotopes break down, they mostly do so through alpha decay (spitting out a <a href="/school1/ptable/element/He" class="wiki-link" title="Helium (He)">helium</a> nucleus) or occasionally through spontaneous fission, where the atom simply splits apart. This extreme instability makes studying meitnerium incredibly difficult, as atoms vanish almost as soon as they are formed!</p>"""
}

os.makedirs('c:/projects/apache/school1/src/ptable/data/drafts', exist_ok=True)
with open('c:/projects/apache/school1/src/ptable/data/drafts/Meitnerium.json', 'w', encoding='utf-8') as f:
    json.dump({'Mt': mt}, f, indent=4)
