import json
import os

rewritten = {
    "extract_html": "<p><b>Zirconium</b> (symbol <b>Zr</b>, atomic number 40) is a silvery-white, strong, and corrosion-resistant metal that looks a bit like titanium. Long before it was used in modern science, zirconium was known in ancient times in the form of zircon crystals, which were prized as colorful gemstones. In fact, the name <i>zirconium</i> comes from the Persian word <i>zargun</i>, meaning &quot;gold-like.&quot; While you might know it best from its use in cubic zirconia—a popular diamond substitute—zirconium is incredibly important in modern technology. It is highly heat-resistant and doesn\\'t absorb neutrons, making it essential for nuclear power plants. It is also used in spacecraft, medical implants, and everyday products like deodorants. Zirconium is abundant in nature, and India holds some of the world\\'s most significant deposits along its beautiful coastal beaches.</p>",
    "sections": {
        "Characteristics": "<p>Zirconium is a tough, silvery metal that refuses to rust or corrode easily, even when exposed to harsh chemicals like acids or saltwater. Because it is highly resistant to heat, it is considered a &quot;refractory&quot; metal, meaning it can withstand extreme temperatures without melting or breaking down. At room temperature, it is solid, bendable, and easy to shape. Interestingly, while solid zirconium is very safe and stable, zirconium powder can easily catch fire if it isn\\'t handled carefully!</p>",
        "Isotopes": "<p>In nature, zirconium is found as a mix of five different types, called isotopes. Four of these are completely stable, meaning they don\\'t break down over time. The fifth one is mildly radioactive, but it takes an incredibly long time to decay—more than 20 quintillion years! Scientists also use synthetic (man-made) isotopes of zirconium in medical research, especially for tracking how well certain medicines work inside the body.</p>",
        "Occurrence": "<p>Zirconium is quite common in the Earth\\'s crust, but you won\\'t find it just lying around as a pure metal. Instead, it is locked inside minerals, most famously <b>zircon</b>. These zircon crystals are incredibly durable; in fact, some zircon grains found on Earth are billions of years old, acting as tiny &quot;time capsules&quot; that help scientists understand the early history of our planet.</p> <p><b>Indian Geographical Relevance:</b> India is incredibly rich in zirconium resources, with over 30 million tonnes of zircon reserves. These are mostly found in the heavy mineral sands along the coastlines of Odisha (like the Chhatrapur coast), Tamil Nadu (Manavalakurichi region), and Kerala (Kollam district). Over millions of years, ocean waves and winds naturally concentrated these minerals on the beaches, creating some of the most economically valuable &quot;placer deposits&quot; in the world.</p>",
        "History": "<p>The story of zirconium begins long before modern chemistry. Ancient people cherished zircon crystals as beautiful gemstones, calling them names like jargon, jacinth, or hyacinth.</p> <p><b>Indian Historical and Cultural Context:</b> In ancient Indian texts and Hindu mythology, zircon holds a special place; legends even describe a magical, jewel-encrusted Kalpavriksha (wish-fulfilling tree) that had vibrant green zircon leaves. Throughout the Middle Ages, people believed these stones could bring wealth, promote wisdom, and ensure a peaceful night\\'s sleep.</p> <p>It wasn\\'t until 1789 that a German chemist named Martin Heinrich Klaproth realized that zircon contained a brand new element. A few decades later, in 1824, the Swedish chemist Jöns Jacob Berzelius finally managed to extract zirconium in its metal form.</p>",
        "Applications": "<p>Today, zirconium is a superstar in both industry and everyday life. Because it doesn\\'t absorb the neutrons flying around inside a nuclear reactor, it is the perfect material for building the tubes that hold nuclear fuel.</p> <p><b>Modern Indian Scientific Contributions:</b> India’s own <b>Nuclear Fuel Complex (NFC)</b> plays a major role here, producing specialized zirconium sponge and zirconium alloys to power the country\\'s expanding nuclear energy program.</p> <p>Beyond nuclear power, zirconium is used to make strong, heat-resistant parts for space vehicles and jet engines. In the medical field, zirconium compounds (like zirconia) are used to make incredibly strong and safe dental implants and artificial joints, because the human body naturally accepts them. You can even find zirconium in everyday items, like antiperspirant deodorants and the water purifiers used in homes!</p>"
    }
}

out_path = r"c:\projects\apache\school1\src\ptable\data\drafts\Zirconium.json"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(rewritten, f, indent=2, ensure_ascii=False)

print("File written successfully to", out_path)
