import json
import os

drafts_dir = 'src/ptable/data/drafts'
os.makedirs(drafts_dir, exist_ok=True)

data = {
    'extract_html': '<p><b>Cadmium</b> is a soft, silvery-white metal with the symbol <b>Cd</b> and atomic number 48. It looks and acts a lot like zinc, but it is rarer and much more toxic. You\\'ll often find cadmium hiding inside zinc ores rather than on its own. It\\'s famous for its use in rechargeable nickel-cadmium batteries and for making bright yellow, orange, and red paints.</p>\n<p>Even though it has been used in many modern products, cadmium is highly toxic to humans and the environment. Because of this, many countries are stepping away from using it. In India, for instance, cadmium isn\\'t naturally mined on its own, but it is extracted as a byproduct of zinc smelting by companies like Hindustan Zinc in Rajasthan. While not a part of traditional Ayurvedic medicine, strict testing is required in India today to ensure herbal remedies aren\\'t accidentally contaminated by this heavy metal.</p>',
    'sections': {
        'Characteristics': '<p>Cadmium is a soft, malleable, and ductile metal that you can almost cut with a knife. It has a beautiful silvery-bluish tint. When you bend a piece of cadmium, it makes a surprising "crying" or crackling sound, much like tin does! It melts at 321 °C (610 °F), which is quite low for a metal. Chemically, Cadmium is very similar to its periodic table neighbor, zinc, but it doesn\\'t rust easily. It resists corrosion well, which is why it has been used to plate other metals to protect them. It doesn\\'t dissolve in water but will react with acids.</p>',
        'History': '<p>Cadmium was discovered in 1817 by German chemist Friedrich Stromeyer. He found it as an impurity in zinc carbonate (calamine). Pharmacists noticed that some calamine turned yellow when heated, which shouldn\\'t happen if it were pure. Stromeyer investigated and discovered a brand new element! He named it "cadmium" after the Latin word for calamine, <em>cadmia</em>.</p><p>Before the rise of modern chemistry, elements like cadmium were unknown to ancient civilizations. For example, in ancient Indian texts and Ayurveda, cadmium is completely absent. Its modern presence in some herbal formulations is strictly due to accidental soil or industrial contamination, which today\\'s Indian authorities tightly monitor under the Drugs and Cosmetics Act.</p>',
        'Occurrence': '<p>You won\\'t find solid chunks of pure cadmium lying around in nature. It usually sneaks into zinc ores, like sphalerite. Because it tags along with zinc, it is almost entirely produced as a byproduct of mining and refining zinc.</p><p>Geographically, in places like India, cadmium production is closely tied to zinc mining. Hindustan Zinc Limited, based in the mineral-rich state of Rajasthan (operating famous mines like Rampura Agucha and Zawar), is the primary producer of cadmium in India. The metal is recovered during the hydrometallurgical refining processes at their massive zinc smelters.</p>',
        'Applications': '<p>For a long time, the biggest use of cadmium was in rechargeable nickel-cadmium (Ni-Cd) batteries. These were the go-to rechargeable batteries for electronics before lithium-ion batteries took over.</p><p>Cadmium is also famous in the art world. Cadmium pigments produce brilliant, long-lasting yellows, oranges, and reds. Despite the toxicity, some artists still prefer them because of their vibrant colors. It is also used to coat steel to prevent rust, in some specialized alloys, and in control rods for nuclear reactors because it is great at absorbing neutrons.</p>',
        'Biological role': '<p>Cadmium has almost no known useful biological role in humans or most animals. Instead, it is highly toxic. Over time, cadmium can build up in the body, especially in the kidneys, causing severe health issues and bone softening (a disease historically known as <em>Itai-itai</em> in Japan).</p><p>In modern India, the Ministry of AYUSH has set strict regulations to ensure that traditional medicines (like Ayurvedic, Siddha, and Unani) are rigorously tested for heavy metals. This ensures that accidental cadmium contamination from soil or water doesn\\'t harm consumers. Because of its toxicity, the world is moving away from cadmium. The European Union and other international bodies have restricted its use in electronics and jewelry to protect human health and the environment.</p>'
    }
}

with open(os.path.join(drafts_dir, 'Cadmium.json'), 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
