import json
import os

with open('src/ptable/data/master_elements.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

te = data['Te']

te['extract_html'] = "<p><b>Tellurium</b> is a rare, brittle, and silvery-white metalloid that bridges the gap between metals and non-metals. Discovered in 1782 in the mountains of modern-day Romania, this element is actually rarer on Earth than platinum! While tellurium wasn't used by ancient civilizations—including in India, where it has no historical footprint—it has become incredibly important in the modern world. Today, the Government of India classifies tellurium as a \"critical mineral\" because it is a key ingredient in advanced technologies like solar panels and thermoelectric devices. Though toxic in large amounts and known to give a person's breath a distinct garlic-like smell if exposed, tellurium is quietly powering the clean-energy revolution of tomorrow.</p>"

te['sections']['Characteristics'] = "<p>Tellurium is a fascinating element that falls into the \"metalloid\" category, meaning it acts a bit like a metal and a bit like a non-metal. It is chemically related to sulfur and selenium. When you find it in its pure, crystalline form, it is silvery-white and shines like a metal, but it is extremely brittle and can be easily crushed into a powder. One of its most unique quirks is that it is far more common out in the wider universe than it is here on Earth. When our planet was forming in the scorching early days of the solar system, tellurium turned into a gas and floated away into space, leaving very little behind in the Earth's crust!</p>"

te['sections']['Physical properties'] = "<p>Tellurium comes in two main forms, or \"allotropes\": a silvery-white crystal and a dark brown-black powder. The crystalline version is a semiconductor, which means it can carry electricity under certain conditions. Interestingly, tellurium conducts electricity slightly better when light shines on it! It has a very high melting point of about 450°C (841°F) and boils at nearly 988°C (1810°F), making it the most heat-resistant element in its chemical family. If you manage to melt it down, liquid tellurium is surprisingly corrosive and can easily eat through metals like copper, iron, and stainless steel.</p>"

te['sections']['Chemical properties'] = "<p>At the atomic level, crystalline tellurium is built like a spiral staircase. Its atoms form parallel, helical chains with three atoms making up each turn of the spiral. Because of this stable structure, the gray crystalline form of tellurium doesn't react much with the oxygen in the air at room temperature. It also doesn't evaporate easily. When it does form chemical bonds, it prefers to team up with metals, most famously combining with gold in nature to create unique minerals.</p>"

te['sections']['Isotopes'] = "<p>Isotopes are variations of an element that have the same number of protons but different numbers of neutrons. Tellurium has eight naturally occurring isotopes. Six of them are completely stable, but two (Tellurium-128 and Tellurium-130) are slightly radioactive. Don't worry, though—Tellurium-128 has a half-life of 2.2 septillion years (that's 2.2 followed by 24 zeros!). This is the longest known half-life of any radioactive isotope, making it about 160 trillion times older than the entire universe! Scientists have also created over 30 artificial, short-lived radioactive versions of tellurium in laboratories to study its atomic behavior.</p>"

te['sections']['Occurrence'] = "<p>Tellurium is one of the rarest solid elements on Earth. To put it in perspective, it is just as scarce in the Earth's crust as platinum! You can occasionally find pure tellurium in nature, but it usually prefers to bond with other metals. It is most famous for bonding with gold to form minerals like <i>calaverite</i>. While you won't find large mines dedicated solely to tellurium, it is typically collected as a bonus by-product when mining for copper or lead. In India, geologists have discovered promising tellurium deposits combined with bismuth and gold in the Parsoi area of Uttar Pradesh's Mahakoshal belt. Recognizing its growing importance for the future, the Indian government officially designated tellurium as one of 30 \"critical minerals\" in 2023, and public sector companies like Hindustan Copper Ltd (HCL) have taken steps to recover it during copper processing.</p>"

te['sections']['History'] = "<p>Tellurium was discovered in 1782 by Franz-Joseph Müller von Reichenstein, an Austrian mining inspector working in Transylvania (modern-day Romania). He was studying a strange gold ore and realized it contained an unknown element. After three years of rigorous testing, he noticed that when heated, this mystery metal gave off a white smoke that smelled strongly of radishes! The element was officially named \"tellurium\" in 1798 by German chemist Martin Heinrich Klaproth, drawing from the Latin word <i>tellus</i>, meaning \"Earth.\" While tellurium doesn't appear in ancient Indian texts or early history, it made a brief splash in the 1920s when scientists tried using it to stop car engines from knocking. The idea was abandoned because it gave the exhaust an unbearable garlic-like stench!</p>"

te['sections']['Applications'] = "<p>Today, tellurium is a rising star in green technology. Its biggest modern use is in the manufacturing of high-efficiency cadmium telluride (CdTe) thin-film solar panels. In India, premier scientific institutions like the IITs and the Indian Institute of Science (IISc) are actively researching tellurium nanostructures to create even better solar cells, cutting-edge photodetectors, and thermoelectric devices that can turn waste heat directly into electricity. Aside from renewable energy, tellurium is mixed into copper, iron, and steel to make them easier to machine and cut. It is also added to rubber to help it withstand heat and wear.</p>"

te['sections']['Biological role'] = "<p>Tellurium has no known biological use for humans or animals. In fact, our bodies actively try to get rid of it! If a person is exposed to even small amounts of tellurium, their body converts it into a harmless gas called dimethyl telluride. The only side effect? It gives their breath and sweat an incredibly strong, pungent garlic odor that can last for weeks! However, some simple organisms handle it differently. Certain types of fungi can actually use tellurium as a substitute for sulfur when building proteins, and some bacteria have the fascinating ability to absorb toxic tellurium compounds and turn them into pure, metallic tellurium crystals right inside their cells.</p>"

os.makedirs('src/ptable/data/drafts', exist_ok=True)
with open('src/ptable/data/drafts/Tellurium.json', 'w', encoding='utf-8') as f:
    json.dump(te, f, indent=4)
