variables:
    dbtype: mysql
    sqlite_path: var/db/merged_fix_verified.sqlite
    db_engine: pdo
    dbname: lekhak1
    dbhost: 127.0.0.1
    dbuser: root
    dbpasswd: hello123
    global_table_prefix: lek_
    installed: true
