variables:
    dbtype: sqlite
    sqlite_path: ':memory:'
    db_engine: pdo
    dbname: lekhak1
    dbhost: localhost
    dbuser: root
    dbpasswd: hello123
    global_table_prefix: lek_
    installed: true
