<?php
/**
 * Lekhak CMS Integration Test Suite
 * Performs end-to-end verification of API, Routing, and Data Integrity.
 */

class LekhakTester {
    private $baseUrl = "http://[::1]/school1";
    private $apiBase = "http://[::1]/school1/admin-api";
    private $testNodeId = null;

    public function run() {
        echo "🚀 Starting Lekhak CMS Extensive Testing...\n\n";

        $this->testApiStats();
        $this->testCreateNode();
        $this->testListNodes();
        $this->testReadNode();
        $this->testPublishNode();
        $this->testFrontendRouting();

        echo "\n✨ Testing Complete.\n";
    }

    private function log($msg, $success = true) {
        $status = $success ? "✅ [PASS]" : "❌ [FAIL]";
        echo "$status $msg\n";
    }

    private function post($action, $data = []) {
        $url = $this->apiBase . "?action=" . $action;
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
        curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
        $res = curl_exec($ch);
        curl_close($ch);
        return json_decode($res, true);
    }

    private function get($url) {
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $res = curl_exec($ch);
        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        return ['code' => $code, 'body' => $res];
    }

    public function testApiStats() {
        $res = $this->post('get_dashboard_stats');
        if ($res && $res['success']) {
            $this->log("Dashboard Stats API: Total=" . $res['stats']['total']);
        } else {
            $this->log("Dashboard Stats API failed.", false);
        }
    }

    public function testCreateNode() {
        $data = [
            'title' => 'Automated Test Post ' . time(),
            'body' => 'This is a test content body generated by the Antigravity tester.',
            'status' => 'draft'
        ];
        $res = $this->post('save_node', $data);
        if ($res && $res['success'] && !empty($res['id'])) {
            $this->testNodeId = $res['id'];
            $this->log("Create Node (Draft): ID=" . $this->testNodeId);
        } else {
            $this->log("Create Node failed: " . ($res['message'] ?? 'No response'), false);
        }
    }

    public function testListNodes() {
        $res = $this->post('list_nodes');
        if ($res && $res['success'] && count($res['nodes']) > 0) {
            $this->log("List Nodes API: Count=" . count($res['nodes']));
        } else {
            $this->log("List Nodes API failed.", false);
        }
    }

    public function testReadNode() {
        if (!$this->testNodeId) return;
        
        $url = $this->apiBase . "?action=get_node&id=" . $this->testNodeId;
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $res = json_decode(curl_exec($ch), true);
        curl_close($ch);

        if ($res && $res['success'] && $res['node']['id'] == $this->testNodeId) {
            $this->log("Read Node API: Title='{$res['node']['title']}'");
        } else {
            $this->log("Read Node API failed.", false);
        }
    }

    public function testPublishNode() {
        if (!$this->testNodeId) return;

        $data = [
            'id' => $this->testNodeId,
            'title' => 'Updated & Published Post ' . time(),
            'body' => 'Updated content body.',
            'status' => 'published'
        ];
        $res = $this->post('save_node', $data);
        if ($res && $res['success']) {
            $this->log("Publish Node API: Success. URL=" . $res['url']);
            
            // Verify Public Access
            $publicUrl = "http://localhost" . $res['url'];
            $page = $this->get($publicUrl);
            if ($page['code'] == 200 && strpos($page['body'], 'Updated content body') !== false) {
                $this->log("Frontend Verification: Node is visible and content matches.");
            } else {
                $this->log("Frontend Verification failed for URL: $publicUrl (Code: {$page['code']})", false);
            }
        } else {
            $this->log("Publish Node API failed.", false);
        }
    }

    public function testFrontendRouting() {
        // Test Lekhak Homepage
        $home = $this->get($this->baseUrl . "/lekhak/");
        if ($home['code'] == 200 && strpos($home['body'], 'Lekhak CMS') !== false) {
            $this->log("Root Routing: Lekhak Homepage resolved.");
        } else {
            $this->log("Root Routing failed (Code: {$home['code']}).", false);
        }

        // Test Admin Entry
        $admin = $this->get($this->baseUrl . "/lekhak/admin");
        if ($admin['code'] == 200 && strpos($admin['body'], 'Lekhak Admin') !== false) {
            $this->log("Admin Routing: Lekhak Workbench resolved.");
        } else {
            $this->log("Admin Routing failed (Code: {$admin['code']}).", false);
        }
    }
}

$tester = new LekhakTester();
$tester->run();
