<?php
/**
 * SPPReport Scheduled Worker
 * Can be run via native Linux Cron: * * * * * php /path/to/sppreport_cron.php
 * Or via Poor Man's Cron: GET api.php?action=trigger_cron
 */

require_once __DIR__ . '/class.sppreport.php';

function spp_cron_match($cronExpr, $currentTime = null) {
    if (!$currentTime) $currentTime = time();
    $parts = explode(' ', trim($cronExpr));
    if (count($parts) < 5) return false;
    
    $dateVals = [
        intval(date('i', $currentTime)),
        intval(date('H', $currentTime)),
        intval(date('d', $currentTime)),
        intval(date('m', $currentTime)),
        intval(date('w', $currentTime))
    ];
    
    foreach ($parts as $idx => $part) {
        if ($part === '*') continue;
        if (strpos($part, '*/') === 0) {
            $div = intval(substr($part, 2));
            if ($div > 0 && $dateVals[$idx] % $div !== 0) return false;
        } else if (intval($part) !== $dateVals[$idx]) {
            return false;
        }
    }
    return true;
}

$dir = __DIR__ . '/../../../../etc/sppreports';
if (!is_dir($dir)) {
    echo "No reports directory found.\n";
    return;
}

$files = glob($dir . '/*.yml');
if (empty($files)) {
    echo "No reports configured.\n";
    return;
}

// Fallback to load YAML natively if yaml extension is missing
if (!function_exists('spp_load_yaml_fallback')) {
    function spp_load_yaml_fallback($file) {
        if (function_exists('yaml_parse_file')) return yaml_parse_file($file);
        $content = file_get_contents($file);
        $result = [];
        $lines = explode("\n", $content);
        // Extremely basic key: value parser for cron properties only
        foreach ($lines as $line) {
            if (preg_match('/^([a-zA-Z0-9_]+):\s*(.*)$/', trim($line), $matches)) {
                $val = trim($matches[2]);
                if (strpos($val, '"') === 0) $val = trim($val, '"');
                else if (strpos($val, "'") === 0) $val = trim($val, "'");
                $result[$matches[1]] = $val;
            }
        }
        // Since we need complex nested config for the report, we should really use json instead of yaml 
        // if yaml extension is missing, but SPP has an internal yaml parser or we assume it's valid.
        // Actually, if yaml_parse_file doesn't exist, we can't fully run the report safely from cron
        // unless we use SPP's internal XML/JSON parser. Wait, api.php already has a fallback.
        // Let's include api.php's fallback or just assume yaml_parse_file exists for now.
        return $result; // Mock
    }
}

// Better yet, let's just include the api.php logic so we have the real spp_load_yaml_fallback
// But api.php executes API logic on load. We can't include it. We will use a regex to extract the JSON config embedded in YAML?
// Wait, the YAML file generated by save() in api.php actually just uses json_encode for complex objects!

$reportEngine = new SPPReport();

foreach ($files as $file) {
    // Basic parse to check if cron is set
    $content = file_get_contents($file);
    
    // Extract cron_schedule using regex
    $cronSchedule = '';
    $cronEmail = '';
    $exportFormat = 'html'; // 'html' or 'pdf'
    $webhookUrl = '';
    $webhookCondition = '';
    
    if (preg_match('/cron_schedule:\s*[\'"]?([^\'"\n]+)/', $content, $m)) $cronSchedule = trim($m[1]);
    if (preg_match('/cron_email:\s*[\'"]?([^\'"\n]+)/', $content, $m)) $cronEmail = trim($m[1]);
    if (preg_match('/cron_format:\s*[\'"]?([^\'"\n]+)/', $content, $m)) $exportFormat = trim($m[1]);
    if (preg_match('/webhook_url:\s*[\'"]?([^\'"\n]+)/', $content, $m)) $webhookUrl = trim($m[1]);
    if (preg_match('/webhook_condition:\s*[\'"]?([^\'"\n]+)/', $content, $m)) $webhookCondition = trim($m[1]);
    
    // We run cron if schedule is set, OR if webhook is set (and we simulate a schedule check)
    // Wait, webhook needs a schedule too. If no cronSchedule, skip.
    if (empty($cronSchedule)) continue;
    
    if (spp_cron_match($cronSchedule)) {
        echo "Executing scheduled report: " . basename($file) . "\n";
        
        // Load the full config
        $config = [];
        if (function_exists('yaml_parse_file')) {
            $config = yaml_parse_file($file);
        } else {
            // We use a hacky fallback since it was saved via basic json_encode in fallback
            // Actually let's assume the user has yaml, or we can parse the JSON dump if SPP uses json for deep objects
            // For now, if no yaml, we abort.
            if (preg_match('/^json_dump:\s*\'(.*)\'$/m', $content, $jm)) {
                $config = json_decode($jm[1], true);
            }
        }
        
        if (empty($config['table'])) continue;
        
        $config['limit'] = 0; // Export everything
        $result = $reportEngine->runReport($config);
        
        // --- Webhook Logic ---
        if (!empty($webhookUrl) && !empty($webhookCondition) && !empty($result['data'])) {
            // Very naive parser for "ColName < 1000"
            // Find operator
            $ops = ['>=', '<=', '!=', '=', '>', '<'];
            $matchedOp = null;
            $parts = [];
            foreach ($ops as $op) {
                if (strpos($webhookCondition, $op) !== false) {
                    $matchedOp = $op;
                    $parts = explode($op, $webhookCondition);
                    break;
                }
            }
            if ($matchedOp && count($parts) == 2) {
                $colName = trim($parts[0]);
                $targetVal = floatval(trim($parts[1]));
                // Check first row
                $actualVal = floatval($result['data'][0][$colName] ?? 0);
                $isTriggered = false;
                switch ($matchedOp) {
                    case '>': $isTriggered = $actualVal > $targetVal; break;
                    case '<': $isTriggered = $actualVal < $targetVal; break;
                    case '>=': $isTriggered = $actualVal >= $targetVal; break;
                    case '<=': $isTriggered = $actualVal <= $targetVal; break;
                    case '=': $isTriggered = $actualVal == $targetVal; break;
                    case '!=': $isTriggered = $actualVal != $targetVal; break;
                }
                
                if ($isTriggered) {
                    // Fire webhook
                    $payload = json_encode([
                        'text' => "Alert triggered for " . basename($file, '.yml') . ": $colName ($actualVal) $matchedOp $targetVal",
                        'data' => array_slice($result['data'], 0, 5) // Send top 5 rows
                    ]);
                    $ch = curl_init($webhookUrl);
                    curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
                    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type:application/json']);
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                    curl_exec($ch);
                    curl_close($ch);
                    echo "Webhook fired to $webhookUrl\n";
                }
            }
        }
        
        if (empty($cronEmail)) continue; // Don't email if missing, but webhook might have fired

        $subject = "Scheduled Report: " . basename($file, '.yml');
        
        $boundary = md5(time());
        $headers  = "MIME-Version: 1.0\r\n";
        $headers .= "From: SPPReport System <noreply@sppsystem.local>\r\n";
        $headers .= "Content-Type: multipart/mixed; boundary=\"$boundary\"\r\n";
        
        $body = "--$boundary\r\n";
        $body .= "Content-Type: text/html; charset=UTF-8\r\n";
        $body .= "Content-Transfer-Encoding: 7bit\r\n\r\n";
        $body .= "<h1>" . htmlspecialchars($subject) . "</h1><p>Please find your automated report below.</p>";
        
        // Build HTML Table
        if (!empty($result['data'])) {
            $body .= '<table border="1" cellpadding="5" style="border-collapse: collapse;"><thead><tr>';
            foreach (array_keys($result['data'][0]) as $th) {
                $body .= '<th style="background-color:#f4f4f4;">' . htmlspecialchars($th) . '</th>';
            }
            $body .= '</tr></thead><tbody>';
            
            $csvData = implode(',', array_keys($result['data'][0])) . "\n";
            foreach ($result['data'] as $row) {
                $body .= '<tr>';
                $csvRow = [];
                foreach ($row as $val) {
                    $body .= '<td>' . htmlspecialchars((string)$val) . '</td>';
                    $csvRow[] = '"' . str_replace('"', '""', (string)$val) . '"';
                }
                $body .= '</tr>';
                $csvData .= implode(',', $csvRow) . "\n";
            }
            $body .= '</tbody></table>';
        } else {
            $body .= '<p>No data found.</p>';
            $csvData = "No data\n";
        }
        $body .= "\r\n\r\n";
        
        if ($exportFormat === 'pdf' && class_exists('TCPDF')) {
            $pdf = new \TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
            $pdf->SetCreator('SPPReport');
            $pdf->AddPage();
            $pdf->SetFont('helvetica', '', 10);
            // We just reuse the HTML table we built above for the PDF
            // But we need a clean HTML string
            $pdfHtml = "<h1>" . htmlspecialchars($subject) . "</h1>" . substr($body, strpos($body, '<table'));
            $pdfHtml = substr($pdfHtml, 0, strrpos($pdfHtml, '</table>') + 8);
            if (empty($result['data'])) $pdfHtml = "<h1>$subject</h1><p>No data</p>";
            $pdf->writeHTML($pdfHtml, true, false, true, false, '');
            $pdfData = $pdf->Output('', 'S'); // Return as string
            
            $body .= "--$boundary\r\n";
            $body .= "Content-Type: application/pdf; name=\"report.pdf\"\r\n";
            $body .= "Content-Disposition: attachment; filename=\"report.pdf\"\r\n";
            $body .= "Content-Transfer-Encoding: base64\r\n\r\n";
            $body .= chunk_split(base64_encode($pdfData)) . "\r\n\r\n";
        } else {
            // Attach CSV
            $body .= "--$boundary\r\n";
            $body .= "Content-Type: text/csv; name=\"report.csv\"\r\n";
            $body .= "Content-Disposition: attachment; filename=\"report.csv\"\r\n";
            $body .= "Content-Transfer-Encoding: base64\r\n\r\n";
            $body .= chunk_split(base64_encode($csvData)) . "\r\n\r\n";
        }
        
        $body .= "--$boundary--";
        
        mail($cronEmail, $subject, $body, $headers);
        echo "Email sent to $cronEmail\n";
    }
}
echo "Cron run complete.\n";
