.TH "chaos-inject" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
chaos-inject \- Configure ChaosMonkey parameters and trigger resilience testing fault injections in staging environments.
.SH SYNOPSIS
.B php spp.php chaos-inject
.SH DESCRIPTION
Configure ChaosMonkey parameters and trigger resilience testing fault injections in staging environments.
