.TH "config:export" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
config:export \- Export database tables and global settings to SQL, SQLite, or XDB format
.SH SYNOPSIS
.B php spp.php config:export
.SH DESCRIPTION
Export database tables and global settings to SQL, SQLite, or XDB format
