.TH "config:import" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
config:import \- Import database tables and settings from an exported SQL, SQLite, or XDB file
.SH SYNOPSIS
.B php spp.php config:import
.SH DESCRIPTION
Import database tables and settings from an exported SQL, SQLite, or XDB file
