.TH "config:sync" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
config:sync \- Synchronize framework configurations (e.g. workflows, dynamic fields) to DB schemas or system registries
.SH SYNOPSIS
.B php spp.php config:sync
.SH DESCRIPTION
Synchronize framework configurations (e.g. workflows, dynamic fields) to DB schemas or system registries
