.TH "crypto-shard-generate" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
crypto-shard-generate \- Generate Shamir Secret key shards across vault nodes and verify Zero-Knowledge MPC signing.
.SH SYNOPSIS
.B php spp.php crypto-shard-generate
.SH DESCRIPTION
Generate Shamir Secret key shards across vault nodes and verify Zero-Knowledge MPC signing.
