.TH "delete:app" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
delete:app \- Delete an SPP application context and all its data (files, config, caches, views)
.SH SYNOPSIS
.B php spp.php delete:app
.SH DESCRIPTION
Delete an SPP application context and all its data (files, config, caches, views)
