.TH "deploy:token:rotate" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
deploy:token:rotate \- Rotate the secure deployment gateway token on both local and remote environments with zero downtime
.SH SYNOPSIS
.B php spp.php deploy:token:rotate
.SH DESCRIPTION
Rotate the secure deployment gateway token on both local and remote environments with zero downtime
