.TH "deploy:plan" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
deploy:plan \- Perform a dry run to view file changes and raw database SQL diffs before deploying
.SH SYNOPSIS
.B php spp.php deploy:plan
.SH DESCRIPTION
Perform a dry run to view file changes and raw database SQL diffs before deploying
