.TH "deploy:maintenance" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
deploy:maintenance \- Toggle manual maintenance mode on a remote target or local environment
.SH SYNOPSIS
.B php spp.php deploy:maintenance
.SH DESCRIPTION
Toggle manual maintenance mode on a remote target or local environment
