.TH "docs-openapi-generate" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
docs-openapi-generate \- Generate an automated OpenAPI 3.1 specification schema from SPPEntity configurations and Controllers across the application.
.SH SYNOPSIS
.B php spp.php docs-openapi-generate
.SH DESCRIPTION
Generate an automated OpenAPI 3.1 specification schema from SPPEntity configurations and Controllers across the application.
