.TH "ebpf-profile-attach" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
ebpf-profile-attach \- Attach eBPF kernel and user-space probes to running workers for zero-overhead profiling.
.SH SYNOPSIS
.B php spp.php ebpf-profile-attach
.SH DESCRIPTION
Attach eBPF kernel and user-space probes to running workers for zero-overhead profiling.
