.TH "generate" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
generate \- AI Copilot: Generate an entire application feature from a natural language prompt.
.SH SYNOPSIS
.B php spp.php generate
.SH DESCRIPTION
AI Copilot: Generate an entire application feature from a natural language prompt.
