.TH "integration:install" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
integration:install \- Provision an external app directory and register the SPP route bypass
.SH SYNOPSIS
.B php spp.php integration:install
.SH DESCRIPTION
Provision an external app directory and register the SPP route bypass
