.TH "integration:restore" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
integration:restore \- Time-travel a user state to a historical point using CQRS Event Sourcing
.SH SYNOPSIS
.B php spp.php integration:restore
.SH DESCRIPTION
Time-travel a user state to a historical point using CQRS Event Sourcing
