.TH "make:command-test" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
make:command-test \- Generate a boilerplate Parikshak feature test for a given command
.SH SYNOPSIS
.B php spp.php make:command-test
.SH DESCRIPTION
Generate a boilerplate Parikshak feature test for a given command
