.TH "make:mixed-paradigm" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
make:mixed-paradigm \- Scaffold a Kitchen Sink view blending SPPView, Drishyam, and SPPUX
.SH SYNOPSIS
.B php spp.php make:mixed-paradigm
.SH DESCRIPTION
Scaffold a Kitchen Sink view blending SPPView, Drishyam, and SPPUX
