.TH "make:polyglot-partial" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
make:polyglot-partial \- Scaffold a new external polyglot partial service file (Python/Node/Go)
.SH SYNOPSIS
.B php spp.php make:polyglot-partial
.SH DESCRIPTION
Scaffold a new external polyglot partial service file (Python/Node/Go)
