.TH "make:polyglot" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
make:polyglot \- Scaffold a new polyglot service (e.g. php spp.php make:polyglot python MyService)
.SH SYNOPSIS
.B php spp.php make:polyglot
.SH DESCRIPTION
Scaffold a new polyglot service (e.g. php spp.php make:polyglot python MyService)
