.TH "make:blade-scaffold" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
make:blade-scaffold \- Create a full stack Blade scaffold (Entity, YAML Form, Controller, Blade Views)
.SH SYNOPSIS
.B php spp.php make:blade-scaffold
.SH DESCRIPTION
Create a full stack Blade scaffold (Entity, YAML Form, Controller, Blade Views)
