.TH "make:deployment" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
make:deployment \- Generate Enterprise Docker and K8s scaffolding for the application.
.SH SYNOPSIS
.B php spp.php make:deployment
.SH DESCRIPTION
Generate Enterprise Docker and K8s scaffolding for the application.
