.TH "serve:async" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
serve:async \- Boot the persistent memory asynchronous coroutine runtime (FrankenPHP/OpenSwoole)
.SH SYNOPSIS
.B php spp.php serve:async
.SH DESCRIPTION
Boot the persistent memory asynchronous coroutine runtime (FrankenPHP/OpenSwoole)
