.TH "site:install" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
site:install \- Initialize the database and load default configurations for a specific profile.
.SH SYNOPSIS
.B php spp.php site:install
.SH DESCRIPTION
Initialize the database and load default configurations for a specific profile.
