.TH "spp-workflow-dump" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
spp-workflow-dump \- Dump a registered workflow definition as a visual state graph in Mermaid.js or Graphviz DOT format.
.SH SYNOPSIS
.B php spp.php spp-workflow-dump
.SH DESCRIPTION
Dump a registered workflow definition as a visual state graph in Mermaid.js or Graphviz DOT format.
