.TH "spp-config-sync" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
spp-config-sync \- Synchronize framework configurations (e.g. workflows, dynamic fields) to DB schemas or system registries, asserting and provisioning missing required tables.
.SH SYNOPSIS
.B php spp.php spp-config-sync
.SH DESCRIPTION
Synchronize framework configurations (e.g. workflows, dynamic fields) to DB schemas or system registries, asserting and provisioning missing required tables.
