.TH "sppreport-cron" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
sppreport-cron \- Trigger SPP Report threshold alerts, scheduled jobs, webhooks, and automated email deliveries securely with distributed mutex locks.
.SH SYNOPSIS
.B php spp.php sppreport-cron
.SH DESCRIPTION
Trigger SPP Report threshold alerts, scheduled jobs, webhooks, and automated email deliveries securely with distributed mutex locks.
