.TH "storage-crdt-sync" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
storage-crdt-sync \- Perform multi-region active-active CRDT synchronization and resolve write conflicts.
.SH SYNOPSIS
.B php spp.php storage-crdt-sync
.SH DESCRIPTION
Perform multi-region active-active CRDT synchronization and resolve write conflicts.
