.TH "sys:upgrade" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
sys:upgrade \- Synchronize the database schema incrementally from all active module definitions (db.yml)
.SH SYNOPSIS
.B php spp.php sys:upgrade
.SH DESCRIPTION
Synchronize the database schema incrementally from all active module definitions (db.yml)
