.TH "sys:test:auto" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
sys:test:auto \- Runs Automated Evolutionary Testing (Parikshak) for the current application.
.SH SYNOPSIS
.B php spp.php sys:test:auto
.SH DESCRIPTION
Runs Automated Evolutionary Testing (Parikshak) for the current application.
