.TH "theme:activate" 1 "August 2026" "SPP Framework" "SPP Commands Manual"
.SH NAME
theme:activate \- Switch the active theme adapter (native/wp/joomla) and optionally set the theme name
.SH SYNOPSIS
.B php spp.php theme:activate
.SH DESCRIPTION
Switch the active theme adapter (native/wp/joomla) and optionally set the theme name
