<?php
namespace App\Student\Entities;

use SPPMod\SppDb\SPPEntity;

/**
 * Class Student
 * Skeleton generated by SPP Entity Builder
 */
class Student extends \SPPMod\SppDb\SPPEntity
{
    // Custom domain logic here
}
