<?php
namespace SPPDocs\classes;

use SPP\App;
use League\CommonMark\Environment\Environment;
use League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension;
use League\CommonMark\Extension\FrontMatter\FrontMatterExtension;
use League\CommonMark\MarkdownConverter;

class SPPCMS
{
    private static $indexCache = null;

    /**
     * Builds a high-performance PHP array index of all content.
     */
    public static function buildIndex($projectConfig, $projectId)
    {
        $environment = new Environment([]);
        $environment->addExtension(new CommonMarkCoreExtension());
        $environment->addExtension(new FrontMatterExtension());
        $converter = new MarkdownConverter($environment);

        $index = [];
        $contentTypes = $projectConfig['content_types'] ?? [];

        // Fallback to basic 'page' and 'blog' if no explicit types defined
        if (empty($contentTypes)) {
            if (isset($projectConfig['pages_dir'])) {
                $contentTypes['page'] = ['dir' => $projectConfig['pages_dir']];
            }
            if (isset($projectConfig['blog_dir'])) {
                $contentTypes['blog'] = ['dir' => $projectConfig['blog_dir']];
            }
        }

        foreach ($contentTypes as $type => $config) {
            $dir = $config['dir'] ?? '';
            
            // Resolve relative path
            if (strpos($dir, 'C:/') === 0 || strpos($dir, 'c:/') === 0) {
                $dir = str_replace(['C:/projects/apache/school1/', 'c:/projects/apache/school1/'], '', $dir);
            }
            if (!str_starts_with($dir, '/') && !str_contains($dir, ':\\')) {
                $dir = dirname(SPP_BASE_DIR) . '/' . $dir;
            }

            if (!is_dir($dir)) continue;

            $index[$type] = [];

            $iter = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir));
            foreach ($iter as $fileInfo) {
                if ($fileInfo->isFile() && $fileInfo->getExtension() === 'md') {
                    $file = $fileInfo->getPathname();
                    // Ignore revisions
                    if (str_contains($file, '.revisions')) continue;

                    // Extract relative path as unique key instead of just basename
                    $relativePath = substr($file, strlen($dir) + 1, -3);
                    $filename = str_replace('\\', '/', $relativePath);
                    
                    $markdown = file_get_contents($file);
                    
                    try {
                        $doc = $converter->convert($markdown);
                        $frontmatter = [];
                        if ($doc instanceof \League\CommonMark\Extension\FrontMatter\Output\RenderedContentWithFrontMatter) {
                            $frontmatter = $doc->getFrontMatter();
                        }
                        
                        $index[$type][$filename] = [
                            'filename' => $filename,
                            'path' => $file,
                            'frontmatter' => $frontmatter,
                            'modified_at' => filemtime($file),
                            // Calculate excerpt dynamically later to save RAM, 
                            // or save a small snippet here if needed.
                        ];
                    } catch (\Exception $e) {
                        continue; // Skip invalid files
                    }
                }
            }
        }

        $cacheDir = SPP_BASE_DIR . '/var/cache/SPPDocs';
        if (!is_dir($cacheDir)) mkdir($cacheDir, 0755, true);
        
        $cacheFile = $cacheDir . '/sppcms_index_' . $projectId . '.php';
        
        $export = var_export($index, true);
        $phpCode = "<?php\n// Auto-generated by SPPCMS\nreturn $export;\n";
        
        file_put_contents($cacheFile, $phpCode);
    }

    /**
     * Helper to load the index from RAM (OPcache).
     */
    public static function getIndex($projectId)
    {
        if (self::$indexCache !== null && isset(self::$indexCache[$projectId])) {
            return self::$indexCache[$projectId];
        }

        $cacheFile = SPP_BASE_DIR . '/var/cache/SPPDocs/sppcms_index_' . $projectId . '.php';
        if (file_exists($cacheFile)) {
            $data = require $cacheFile;
            self::$indexCache[$projectId] = $data;
            return $data;
        }

        return [];
    }

    /**
     * Query builder entry point.
     * e.g., SPPCMS::query('spp', 'blog')->where('category', 'news')->get();
     */
    public static function query($projectId, $contentType)
    {
        return new SPPCMSQuery($projectId, $contentType);
    }

    public static function collection($projectId, $contentType)
    {
        return self::query($projectId, $contentType);
    }
}

class SPPCMSQuery
{
    private $items = [];

    public function __construct($projectId, $contentType)
    {
        $index = SPPCMS::getIndex($projectId);
        $this->items = $index[$contentType] ?? [];
    }

    public function where($key, $value)
    {
        $this->items = array_filter($this->items, function($item) use ($key, $value) {
            return isset($item['frontmatter'][$key]) && $item['frontmatter'][$key] === $value;
        });
        return $this;
    }

    public function whereIn($key, $array)
    {
        $this->items = array_filter($this->items, function($item) use ($key, $array) {
            return isset($item['frontmatter'][$key]) && in_array($item['frontmatter'][$key], $array);
        });
        return $this;
    }

    public function whereLike($key, $pattern)
    {
        $pattern = strtolower($pattern);
        $this->items = array_filter($this->items, function($item) use ($key, $pattern) {
            $val = strtolower((string)($item['frontmatter'][$key] ?? ''));
            return strpos($val, $pattern) !== false;
        });
        return $this;
    }

    public function whereBetween($key, $min, $max)
    {
        $this->items = array_filter($this->items, function($item) use ($key, $min, $max) {
            $val = $item['frontmatter'][$key] ?? null;
            return $val !== null && $val >= $min && $val <= $max;
        });
        return $this;
    }

    public function publishedOnly()
    {
        $this->items = array_filter($this->items, function($item) {
            $fm = $item['frontmatter'] ?? [];
            if (($fm['status'] ?? 'published') === 'draft') return false;
            if (!empty($fm['date']) && strtotime($fm['date']) > time()) return false;
            return true;
        });
        return $this;
    }

    public function orderBy($key, $direction = 'asc')
    {
        uasort($this->items, function($a, $b) use ($key, $direction) {
            $valA = $a['frontmatter'][$key] ?? '';
            $valB = $b['frontmatter'][$key] ?? '';
            
            if ($valA == $valB) return 0;
            
            if ($direction === 'desc') {
                return $valA < $valB ? 1 : -1;
            } else {
                return $valA > $valB ? 1 : -1;
            }
        });
        return $this;
    }

    public function offset($offset)
    {
        $this->items = array_slice($this->items, $offset, null, true);
        return $this;
    }

    public function limit($count)
    {
        $this->items = array_slice($this->items, 0, $count, true);
        return $this;
    }

    public function count(): int
    {
        return count($this->items);
    }

    public function first(): ?\stdClass
    {
        $res = $this->limit(1)->get();
        return !empty($res) ? $res[0] : null;
    }

    public function paginate(int $page = 1, int $perPage = 15): array
    {
        $totalItems = count($this->items);
        $totalPages = max(1, (int)ceil($totalItems / $perPage));
        $page = max(1, min($page, $totalPages));
        $offset = ($page - 1) * $perPage;
        
        $slice = array_slice($this->items, $offset, $perPage, true);
        $items = array_values(array_map(function($item) {
            $obj = new \stdClass();
            $obj->filename = $item['filename'];
            $obj->path = $item['path'];
            $obj->modified_at = $item['modified_at'];
            foreach ($item['frontmatter'] as $k => $v) {
                $obj->$k = $v;
            }
            return $obj;
        }, $slice));

        return [
            'data' => $items,
            'total' => $totalItems,
            'per_page' => $perPage,
            'current_page' => $page,
            'last_page' => $totalPages,
            'from' => $totalItems > 0 ? $offset + 1 : 0,
            'to' => min($offset + $perPage, $totalItems),
        ];
    }

    public function get()
    {
        // Convert to objects for easy Blade access: $item->title
        return array_map(function($item) {
            $obj = new \stdClass();
            $obj->filename = $item['filename'];
            $obj->path = $item['path'];
            $obj->modified_at = $item['modified_at'];
            foreach ($item['frontmatter'] as $k => $v) {
                $obj->$k = $v;
            }
            return $obj;
        }, $this->items);
    }
}

if (!class_exists('\App\SPPDocs\Classes\SPPCMS', false)) {
    class_alias('\SPPDocs\classes\SPPCMS', '\App\SPPDocs\Classes\SPPCMS');
}
if (!class_exists('\App\SPPDocs\Classes\SPPCMSQuery', false)) {
    class_alias('\SPPDocs\classes\SPPCMSQuery', '\App\SPPDocs\Classes\SPPCMSQuery');
}
