<?php
namespace App\Default\Entities;

use SPPMod\SppDb\SPPEntity;

/**
 * Class Teacher
 * Skeleton generated by SPP Visual Entity Builder
 */
class Teacher extends \SPPMod\SppDb\SPPEntity
{
    // Custom domain logic here
}
