<?php
namespace App\Default\Entities;

use SPPMod\SPPEntity\SPPEntity;

/**
 * Class BlogPost
 * Skeleton generated by SPP Entity Builder
 */
class BlogPost extends \SPPMod\SPPEntity\SPPEntity
{
    // Custom domain logic here
}
