<?php
namespace App\Default\Entities;

use SPPMod\SPPDB\SPPEntity;

/**
 * Class Employee
 * Skeleton generated by SPP Entity Builder
 */
class Employee extends \SPPMod\SPPDB\SPPEntity
{
    // Custom domain logic here
}
