<?php
namespace App\Default\Entities;

use SPPMod\SPPDB\SPPEntity;

/**
 * Class DummyEntity
 * Skeleton generated by SPP Entity Builder
 */
class DummyEntity extends \SPPMod\SPPDB\SPPEntity
{
    public function getTable()
    {
        return 'dummyentitys';
    }

    // Custom domain logic here
    public function define_attributes()
    {
        return [
            'name' => 'varchar(255)',
            'dob' => 'datetime'
        ];
    }

}
