<?php
namespace App\Default\Entities;

use SPPMod\SppDb\SPPEntity;

/**
 * Class Staff
 * Skeleton generated by SPP Visual Entity Builder
 */
class Staff extends \SPPMod\SppDb\SPPEntity
{
    // Custom domain logic here
}
