<?php
namespace App\Default\Entities;

use SPPMod\SPPDB\SPPEntity;

/**
 * Class TestUser
 * Skeleton generated by SPP Entity Builder
 */
class TestUser extends \SPPMod\SPPDB\SPPEntity
{
    // Custom domain logic here
}
