<?php
namespace App\Default\Entities;

use SPPMod\SPPEntity\SPPEntity;

/**
 * Class FeatureModel
 * Skeleton generated by SPP Entity Builder
 */
class FeatureModel extends \SPPMod\SPPEntity\SPPEntity
{
    // Custom domain logic here
}
