<?php
namespace App\Default\Entities;

use SPPMod\SppDb\SPPEntity;

/**
 * Class NewEntity1
 * Skeleton generated by SPP Entity Builder
 */
class NewEntity1 extends \SPPMod\SppDb\SPPEntity
{
    // Custom domain logic here
}
