<?php
namespace App\Default\Entities;

use SPPMod\SppDb\SPPEntity;

/**
 * Class TestEditEntity
 * Skeleton generated by SPP Entity Builder
 */
class TestEditEntity extends SPPEntity
{
    // Custom domain logic here
}
