<?php
namespace App\Default\Entities;

use SPPMod\SppDb\SPPEntity;

/**
 * Class TestEntity
 * Skeleton generated by SPP Entity Builder
 */
class TestEntity extends \SPPMod\SPPAuth\SPPUser
{
    // Custom domain logic here
}
