.TH SPP-db-verify 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-db-verify \- Runs the SPP XDB MySQL Compatibility Verification Suite
.SH SYNOPSIS
.B php spp.php db:verify
[OPTIONS]
.SH DESCRIPTION
Runs the SPP XDB MySQL Compatibility Verification Suite
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes external system binaries or shell commands.
.br
