.TH SPP-drishyam-theme-check 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
drishyam:theme:check
.PP
 \- Validate Drishyam theme assets and structure
.SH DESCRIPTION
Validate Drishyam theme assets and structure
.PP
.SH SYNOPSIS
php spp.php drishyam:theme:check [OPTIONS]
.PP
.SH OPTIONS
\(bu `--app=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Bootstraps a full application execution context via Scheduler.
.br
.PP
.PP
