.TH SPP-serve-async 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
serve:async
.PP
 \- Boot the persistent memory asynchronous coroutine runtime (FrankenPHP/OpenSwoole)
.SH DESCRIPTION
Boot the persistent memory asynchronous coroutine runtime (FrankenPHP/OpenSwoole)
.PP
.SH SYNOPSIS
php spp.php serve:async [OPTIONS]
.PP
.SH OPTIONS
\(bu `--app=` : Expects a value. Extracted via static analysis.
.br
\(bu `--port=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
