.TH SPP-make-eventhand 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-eventhand \- Create a new Event Handler class
.SH SYNOPSIS
.B php spp.php make:eventhand
[OPTIONS]
.SH DESCRIPTION
Create a new Event Handler class
.PP
Usage: php spp.php make:eventhand <HandlerClassName> [--app=appname]
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes external system binaries or shell commands.
.br
\(bu Instantiates key components: Event.
.br
