.TH SPP-make-react-component 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:react-component
.PP
 \- Scaffold a new React component (ESM/No-build)
.SH DESCRIPTION
Scaffold a new React component (ESM/No-build)
.PP
.SH SYNOPSIS
php spp.php make:react-component [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php make:react-component <ComponentName>
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
\(bu Instantiates internal components: React.
.br
.PP
.PP
