.TH SPP-make-java-service 1 "23 June 2026" "SPP Framework" "SPP CLI Manual"
.SH `MAKE:JAVA-SERVICE`
.PP
Purpose: Create a new Java service script
.PP
.SH SYNOPSIS
php spp.php make:java-service [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: spp make:java-service <name> [--app=context]
.PP
.PP
.SH OPTIONS AVAILABLE
No static options detected for this command.
.PP
.SH UNDER THE HOOD ACTIVITY
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
\(bu Instantiates internal components: Java.
.br
.PP
.PP
