.TH SPP-bridge-call 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-bridge-call \- Internal RPC bridge to invoke PHP methods from Polyglot clients
.SH SYNOPSIS
.B php spp.php bridge:call
[OPTIONS]
.SH DESCRIPTION
Internal RPC bridge to invoke PHP methods from Polyglot clients
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: \ReflectionMethod.
.br
