.TH SPP-lang-list 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
lang:list
.PP
 \- List all translations
.SH DESCRIPTION
List all translations
.PP
.SH SYNOPSIS
php spp.php lang:list [OPTIONS]
.PP
.SH OPTIONS
\(bu `--app=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Dynamically loads SPP kernel modules: spplang.
.br
\(bu Bootstraps a full application execution context via Scheduler.
.br
.PP
.PP
