.TH SPP-workflow-process-timeouts 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
workflow:process-timeouts
.PP
 \- Process SLA timeouts on entities and trigger automatic escalation transitions
.SH DESCRIPTION
Process SLA timeouts on entities and trigger automatic escalation transitions
.PP
.SH SYNOPSIS
php spp.php workflow:process-timeouts [OPTIONS]
.PP
.SH OPTIONS
\(bu `--timeout` : Boolean flag or option. Extracted via static analysis.
.br
\(bu `--timeout_transition` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: \SPPMod\SPPDB\SPPDB.
.br
.PP
.PP
