.TH SPP-config-sync 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-config-sync \- Synchronize framework configurations (e.g. workflows, dynamic fields) to DB schemas or system registries
.SH SYNOPSIS
.B php spp.php config:sync
[OPTIONS]
.SH DESCRIPTION
Synchronize framework configurations (e.g. workflows, dynamic fields) to DB schemas or system registries
