.TH SPP-deploy-run 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-deploy-run \- Securely execute an arbitrary shell command on the remote server
.SH SYNOPSIS
.B php spp.php deploy:run
[OPTIONS]
.SH DESCRIPTION
Securely execute an arbitrary shell command on the remote server
.PP
Usage: php spp.php deploy:run [target_uri] \
.PP
.SH OPTIONS
.TP
.B --key=
Expects a value. Extracted via static analysis from DeployRunCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
