.TH SPP-form-crud 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-form-crud \- Manage SPP forms (list, create, edit, delete)
.SH SYNOPSIS
.B php spp.php form:crud
[OPTIONS]
.SH DESCRIPTION
Manage SPP forms (list, create, edit, delete)
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
