.TH SPP-marketing-campaign-sync 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-marketing-campaign-sync \- Synchronize marketing campaigns/templates with external CRMs
.SH SYNOPSIS
.B php spp.php marketing:campaign:sync
[OPTIONS]
.SH DESCRIPTION
Synchronize marketing campaigns/templates with external CRMs
