.TH SPP-deploy-history 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
deploy:history
.PP
 \- 
.SH DESCRIPTION

.PP
.SH SYNOPSIS
php spp.php deploy:history [OPTIONS]
.PP
.SH OPTIONS
\(bu `--key=` : Expects a value. Extracted via static analysis.
.br
\(bu `--status` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
