.TH SPP-auth-tokens 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
auth:tokens
.PP
 \- Manage Personal Access Tokens for API Authentication
.SH DESCRIPTION
Manage Personal Access Tokens for API Authentication
.PP
.SH SYNOPSIS
php spp.php auth:tokens [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: SPPUser, SPPDB.
.br
.PP
.PP
