.TH SPP-list 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
list
.PP
 \- Lists all discovered SPP CLI commands.
.SH DESCRIPTION
Lists all discovered SPP CLI commands.
.PP
.SH SYNOPSIS
php spp.php list [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
