.TH SPP-queue-list 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
queue:list
.PP
 \- List all jobs currently in the queue
.SH DESCRIPTION
List all jobs currently in the queue
.PP
.SH SYNOPSIS
php spp.php queue:list [OPTIONS]
.PP
.SH OPTIONS
\(bu `--app=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Bootstraps a full application execution context via Scheduler.
.br
\(bu Instantiates internal components: \SPPMod\SPPDB\SPPDB.
.br
.PP
.PP
