.TH SPP-polyglot-async 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
polyglot:async
.PP
 \- Internal command to execute polyglot calls asynchronously
.SH DESCRIPTION
Internal command to execute polyglot calls asynchronously
.PP
.SH SYNOPSIS
php spp.php polyglot:async [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
