.TH SPP-sys-seed 1 "23 June 2026" "SPP Framework" "SPP CLI Manual"
.SH `SYS:SEED`
.PP
Purpose: Run all database seeders for an application
.PP
.SH SYNOPSIS
php spp.php sys:seed [OPTIONS]
.PP
.SH OPTIONS AVAILABLE
No static options detected for this command.
.PP
.SH UNDER THE HOOD ACTIVITY
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: SPPDB.
.br
.PP
.PP
