.TH SPP-xdb-list-dbs 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-xdb-list-dbs \- List all available XDB databases
.SH SYNOPSIS
.B php spp.php xdb:list-dbs
[OPTIONS]
.SH DESCRIPTION
List all available XDB databases
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: \SPPMod\SPPXDB\SPP_XDB.
.br
