.TH SPP-ext-install 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-ext-install \- Install an extension from a zip or directory
.SH SYNOPSIS
.B php spp.php ext:install
[OPTIONS]
.SH DESCRIPTION
Install an extension from a zip or directory
.PP
Usage: php spp.php ext:install --source=<path_or_url>
.br

.PP
.SH OPTIONS
.TP
.B --source=
Expects a value. Extracted via static analysis from ExtInstallCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
