.TH SPP-component-crud 1 "23 June 2026" "SPP Framework" "SPP CLI Manual"
.SH `COMPONENT:CRUD`
.PP
Purpose: Manage SPP UI components (list, create, edit, delete)
.PP
.SH SYNOPSIS
php spp.php component:crud [OPTIONS]
.PP
.SH OPTIONS AVAILABLE
No static options detected for this command.
.PP
.SH UNDER THE HOOD ACTIVITY
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
