.TH SPP-app-config 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-app-config \- Configure application settings (e.g., base_url, table_prefix)
.SH SYNOPSIS
.B php spp.php app:config
[OPTIONS]
.SH DESCRIPTION
Usage: php spp.php app:config <app_name> [--base_url=...] [--table_prefix=...]
