.TH SPP-make-twig 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-twig \- Scaffold a new Twig template (Drishyam Paradigm)
.SH SYNOPSIS
.B php spp.php make:twig
[OPTIONS]
.SH DESCRIPTION
Scaffold a new Twig template (Drishyam Paradigm)
.PP
Usage: php spp.php make:twig <ViewName>
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Performs raw filesystem modifications (create/write/delete).
.br
\(bu Instantiates key components: Drishyam, Twig.
.br
