.TH SPP-xdb-make-migration 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
xdb:make:migration
.PP
 \- Create a new SPP_XDB migration file
.SH DESCRIPTION
Create a new SPP_XDB migration file
.PP
.SH SYNOPSIS
php spp.php xdb:make:migration [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php xdb:make:migration <name_of_table>
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: SPP_XDB, MigrationManager.
.br
.PP
.PP
