.TH SPP-theme-activate 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-theme-activate \- Switch the active theme adapter (native/wp/joomla) and optionally set the theme name
.SH SYNOPSIS
.B php spp.php theme:activate
[OPTIONS]
.SH DESCRIPTION
Switch the active theme adapter (native/wp/joomla) and optionally set the theme name
