.TH SPP-integration-queue-work 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
integration:queue:work
.PP
 \- Run the persistent CDC integration event queue worker
.SH DESCRIPTION
Run the persistent CDC integration event queue worker
.PP
.SH SYNOPSIS
php spp.php integration:queue:work [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: DBAdapter.
.br
.PP
.PP
