.TH SPP- 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME

.PP
 \- Test SCIM User Provisioning locally
.SH DESCRIPTION
Test SCIM User Provisioning locally
.PP
.SH SYNOPSIS
php spp.php  [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php scim:test:user <username> [email]
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: SCIMHandler, \ReflectionClass.
.br
.PP
.PP
