.TH SPP-mesh-add 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
mesh:add
.PP
 \- Mounts a legacy application as a passthrough route in the WebOS Mesh
.SH DESCRIPTION
Mounts a legacy application as a passthrough route in the WebOS Mesh
.PP
.SH SYNOPSIS
php spp.php mesh:add [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
