.TH SPP-polyglot-list 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
polyglot:list
.PP
 \- Discovers and tabulates all registered polyglot services
.SH DESCRIPTION
Discovers and tabulates all registered polyglot services
.PP
.SH SYNOPSIS
php spp.php polyglot:list [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: \RecursiveIteratorIterator, \RecursiveDirectoryIterator.
.br
.PP
.PP
