.TH SPP-migrate 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
migrate
.PP
 \- Run pending database migrations
.SH DESCRIPTION
Run pending database migrations
.PP
.SH SYNOPSIS
php spp.php migrate [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: SPPMigrationManager.
.br
.PP
.PP
