.TH SPP-deploy-maintenance 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
deploy:maintenance
.PP
 \- Toggle manual maintenance mode on a remote target or local environment
.SH DESCRIPTION
Toggle manual maintenance mode on a remote target or local environment
.PP
.SH SYNOPSIS
php spp.php deploy:maintenance [OPTIONS]
.PP
.SH OPTIONS
\(bu `--key=` : Expects a value. Extracted via static analysis.
.br
\(bu `--on` : Boolean flag or option. Extracted via static analysis.
.br
\(bu `--off` : Boolean flag or option. Extracted via static analysis.
.br
\(bu `--status` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
