.TH SPP-make-dotnet-service 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:dotnet-service
.PP
 \- Create a new .NET service project
.SH DESCRIPTION
Create a new .NET service project
.PP
.SH SYNOPSIS
php spp.php make:dotnet-service [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: spp make:dotnet-service <name> [--app=context]
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
\(bu Executes external system binaries or shell commands.
.br
\(bu Instantiates internal components: console.
.br
.PP
.PP
