.TH SPP-sys-test-auto 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-sys-test-auto \- Runs Automated Evolutionary Testing (Parikshak) for the current application.
.SH SYNOPSIS
.B php spp.php sys:test:auto
[OPTIONS]
.SH DESCRIPTION
Runs Automated Evolutionary Testing (Parikshak) for the current application.
