.TH SPP-view-service-remove 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-view-service-remove \- Remove an AJAX service endpoint from an app
.SH SYNOPSIS
.B php spp.php view:service:remove
[OPTIONS]
.SH DESCRIPTION
Usage: php spp.php view:service:remove --name=<service> [--app=default] [--source=yaml|db]
