.TH SPP-sys-seed 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-sys-seed \- Run all database seeders for an application
.SH SYNOPSIS
.B php spp.php sys:seed
[OPTIONS]
.SH DESCRIPTION
Run all database seeders for an application
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: SPPDB.
.br
