.TH SPP-make-command 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-command \- Create a new CLI command class
.SH SYNOPSIS
.B php spp.php make:command
[OPTIONS]
.SH DESCRIPTION
Create a new CLI command class
.PP
Usage: php spp.php make:command <name> [--app=appname] [--command=cmd:name]
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: CLI.
.br
