.TH SPP-marketing-campaign-dispatch 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-marketing-campaign-dispatch \- Dispatch a marketing campaign manually
.SH SYNOPSIS
.B php spp.php marketing:campaign:dispatch
[OPTIONS]
.SH DESCRIPTION
Usage: php spp.php marketing:campaign:dispatch --id=<campaign_id>
