.TH SPP-app-default 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-app-default \- Set or view the default global CLI application context
.SH SYNOPSIS
.B php spp.php app:default
[OPTIONS]
.SH DESCRIPTION
Set or view the default global CLI application context
.PP
.SH OPTIONS
.TP
.B --set=
Expects a value. Extracted via static analysis from AppDefaultCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Performs raw filesystem modifications (create/write/delete).
.br
