.TH SPP-diff-apply 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
diff:apply
.PP
 \- Apply a patch or delta file
.SH DESCRIPTION
Apply a patch or delta file
.PP
.SH SYNOPSIS
php spp.php diff:apply [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: diff:apply --file=patch.json
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
