.TH SPP-make-drupal-bridge 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:drupal-bridge
.PP
 \- Scaffold a Drupal module to bridge SPP into Drupal
.SH DESCRIPTION
Scaffold a Drupal module to bridge SPP into Drupal
.PP
.SH SYNOPSIS
php spp.php make:drupal-bridge [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
\(bu Instantiates internal components: TwigFunction.
.br
.PP
.PP
