.TH SPP-profile-report-generate 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
profile:report:generate
.PP
 \- Dump a performance profile trace for debugging
.SH DESCRIPTION
Dump a performance profile trace for debugging
.PP
.SH SYNOPSIS
php spp.php profile:report:generate [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
