.TH SPP-make-model 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:model
.PP
 \- Create a new model class (Fluent-ready)
.SH DESCRIPTION
Create a new model class (Fluent-ready)
.PP
.SH SYNOPSIS
php spp.php make:model [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php make:model <name> [--app=appname] [--table=tablename]
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: model.
.br
.PP
.PP
