.TH SPP-env-get 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-env-get \- Get a specific configuration variable
.SH SYNOPSIS
.B php spp.php env:get
[OPTIONS]
.SH DESCRIPTION
Get a specific configuration variable
.PP
Usage: php spp.php env:get <key> [--app=appname]
.br

.PP
.SH OPTIONS
.TP
.B --app=
Expects a value. Extracted via static analysis from EnvGetCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Bootstraps a full application execution context (Scheduler::withContext).
.br
