.TH SPP-migrate-deploy 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-migrate-deploy \- Pushes local app state and configurations to a remote SPPMigrate instance
.SH SYNOPSIS
.B php spp.php migrate:deploy
[OPTIONS]
.SH DESCRIPTION
Usage: php spp.php migrate:deploy <target_uri> [--full] [--key=YOUR_API_KEY]
