.TH SPP-xdb-shell 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-xdb-shell \- Launch the interactive SPPXDB shell
.SH SYNOPSIS
.B php spp.php xdb:shell
[OPTIONS]
.SH DESCRIPTION
Launch the interactive SPPXDB shell
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
