.TH SPP-admin-bootstrap 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
admin:bootstrap
.PP
 \- Initialize SPP Admin environment (XDB Provisioning)
.SH DESCRIPTION
Initialize SPP Admin environment (XDB Provisioning)
.PP
.SH SYNOPSIS
php spp.php admin:bootstrap [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: SPPDB.
.br
.PP
.PP
