.TH SPP-lekhak-setup 1 "23 June 2026" "SPP Framework" "SPP CLI Manual"
.SH `LEKHAK:SETUP`
.PP
Purpose: Initializes Lekhak CMS database tables.
.PP
.SH SYNOPSIS
php spp.php lekhak:setup [OPTIONS]
.PP
.SH OPTIONS AVAILABLE
No static options detected for this command.
.PP
.SH UNDER THE HOOD ACTIVITY
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: SPPDB.
.br
.PP
.PP
