.TH SPP-interdb-mapping-remove 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
interdb:mapping:remove
.PP
 \- Remove an InterDB mapping
.SH DESCRIPTION
Remove an InterDB mapping
.PP
.SH SYNOPSIS
php spp.php interdb:mapping:remove [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php interdb:mapping:remove <alias>
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
