.TH SPP-dev-spplang 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
dev:spplang
.PP
 \- Manage Dev spplang operations. Usage: admin:spplang <action> [--payload=...] [--json]
.SH DESCRIPTION
Manage Dev spplang operations. Usage: admin:spplang <action> [--payload=...] [--json]
.PP
.SH SYNOPSIS
php spp.php dev:spplang [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: translation.
.br
.PP
.PP
