.TH SPP-iam-roles 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
iam:roles
.PP
 \- List all Roles and Entity Role Assignments
.SH DESCRIPTION
List all Roles and Entity Role Assignments
.PP
.SH SYNOPSIS
php spp.php iam:roles [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php iam:roles list
.PP
.PP
.SH OPTIONS
\(bu `--json` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: SPPDB.
.br
.PP
.PP
