.TH SPP-make-seeder 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-seeder \- Create a new Database Seeder class
.SH SYNOPSIS
.B php spp.php make:seeder
[OPTIONS]
.SH DESCRIPTION
Create a new Database Seeder class
.PP
.SH OPTIONS
.TP
.B --app=
Expects a value. Extracted via static analysis from MakeSeederCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Interacts with the SPP database layer directly.
.br
\(bu Performs raw filesystem modifications (create/write/delete).
.br
\(bu Instantiates key components: Database.
.br
