.TH SPP-oauth-client-create 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
oauth:client:create
.PP
 \- Create a new OAuth 2.0 Client App
.SH DESCRIPTION
Create a new OAuth 2.0 Client App
.PP
.SH SYNOPSIS
php spp.php oauth:client:create [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php oauth:client:create --name=\
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: OAuth, SPPDB.
.br
.PP
.PP
