.TH SPP-test 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
test
.PP
 \- Run Parikshak Unit and Feature Tests
.SH DESCRIPTION
Run Parikshak Unit and Feature Tests
.PP
.SH SYNOPSIS
php spp.php test [OPTIONS]
.PP
.SH OPTIONS
\(bu `--coverage` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: \SPPMod\SPPDB\SPPDB, SPPTestRunner.
.br
.PP
.PP
