.TH SPP-dev-config 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
dev:config
.PP
 \- Manage Dev Config operations. Usage: admin:config <action> [--payload=...] [--json]
.SH DESCRIPTION
Manage Dev Config operations. Usage: admin:config <action> [--payload=...] [--json]
.PP
.SH SYNOPSIS
php spp.php dev:config [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
