.TH SPP-interdb-config 1 "23 June 2026" "SPP Framework" "SPP CLI Manual"
.SH `INTERDB:CONFIG`
.PP
Purpose: Get or set the interdb operating mode
.PP
.SH SYNOPSIS
php spp.php interdb:config [OPTIONS]
.PP
.SH OPTIONS AVAILABLE
\(bu `--mappings` : Boolean flag or option. Extracted via static analysis from InterdbConfigCommand.php.
.br
.PP
.SH UNDER THE HOOD ACTIVITY
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
