.TH SPP-deploy-run 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
deploy:run
.PP
 \- Securely execute an arbitrary shell command on the remote server
.SH DESCRIPTION
Securely execute an arbitrary shell command on the remote server
.PP
.SH SYNOPSIS
php spp.php deploy:run [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php deploy:run [target_uri] \
.PP
.SH OPTIONS
\(bu `--key=` : Expects a value. Extracted via static analysis.
.br
\(bu `--status` : Boolean flag or option. Extracted via static analysis.
.br
\(bu `--exit_code` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
