.TH SPP-logger-tail 1 "23 June 2026" "SPP Framework" "SPP CLI Manual"
.SH `LOGGER:TAIL`
.PP
Purpose: Tail the SPP application log file
.PP
.SH SYNOPSIS
php spp.php logger:tail [OPTIONS]
.PP
.SH OPTIONS AVAILABLE
No static options detected for this command.
.PP
.SH UNDER THE HOOD ACTIVITY
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
