.TH SPP-make-middleware 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:middleware
.PP
 \- Create a new middleware class
.SH DESCRIPTION
Create a new middleware class
.PP
.SH SYNOPSIS
php spp.php make:middleware [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php make:middleware <name> [--app=appname]
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: middleware.
.br
.PP
.PP
