.TH SPP-mesh-list 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
mesh:list
.PP
 \- Lists all active Mesh passthrough routes
.SH DESCRIPTION
Lists all active Mesh passthrough routes
.PP
.SH SYNOPSIS
php spp.php mesh:list [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
