.TH SPP-polyglot-run 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
polyglot:run
.PP
 \- Executes a specific polyglot service directly
.SH DESCRIPTION
Executes a specific polyglot service directly
.PP
.SH SYNOPSIS
php spp.php polyglot:run [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php polyglot:run --path=<relative_path_to_service> [args...]
.PP
.PP
.SH OPTIONS
\(bu `--path=` : Expects a value. Extracted via static analysis.
.br
\(bu `--app=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes external system binaries or shell commands.
.br
.PP
.PP
