.TH SPP-userprofile-export 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
userprofile:export
.PP
 \- Export user profile data for compliance/GDPR
.SH DESCRIPTION
Export user profile data for compliance/GDPR
.PP
.SH SYNOPSIS
php spp.php userprofile:export [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php userprofile:export --user=<user_id>
.PP
.PP
.SH OPTIONS
\(bu `--user=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
