.TH SPP-xdb-migrate 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
xdb:migrate
.PP
 \- Run SPP_XDB Database Migrations
.SH DESCRIPTION
Run SPP_XDB Database Migrations
.PP
.SH SYNOPSIS
php spp.php xdb:migrate [OPTIONS]
.PP
.SH OPTIONS
\(bu `--steps=` : Expects a value. Extracted via static analysis.
.br
\(bu `--rollback` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: SPP_XDB, MigrationManager.
.br
.PP
.PP
