.TH SPP-service-crud 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-service-crud \- Manage SPP services (list, create, edit, delete)
.SH SYNOPSIS
.B php spp.php service:crud
[OPTIONS]
.SH DESCRIPTION
Manage SPP services (list, create, edit, delete)
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Performs raw filesystem modifications (create/write/delete).
.br
