.TH SPP-cache-purge 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
cache:purge
.PP
 \- Purge cache tags or URLs from the reverse proxy (Varnish/CDN).
.SH DESCRIPTION
Purge cache tags or URLs from the reverse proxy (Varnish/CDN).
.PP
.SH SYNOPSIS
php spp.php cache:purge [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes external system binaries or shell commands.
.br
\(bu Makes outbound HTTP requests to external APIs or services.
.br
.PP
.PP
