.TH SPP-module-setting-update 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
module:setting:update
.PP
 \- Update a configuration setting for a specific module
.SH DESCRIPTION
Update a configuration setting for a specific module
.PP
.SH SYNOPSIS
php spp.php module:setting:update [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
