.TH SPP-make-service 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-service \- Create a new service class
.SH SYNOPSIS
.B php spp.php make:service
[OPTIONS]
.SH DESCRIPTION
Create a new service class
.PP
Usage: php spp.php make:service <name> [--app=appname] [--lang=python]
.br

.PP
.SH OPTIONS
.TP
.B --lang=
Expects a value. Extracted via static analysis from MakeServiceCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: service, MakePythonCommand, MakeNodeCommand, MakeGoCommand, MakeDotNetCommand.
.br
