.TH SPP-bridge-call 1 "23 June 2026" "SPP Framework" "SPP CLI Manual"
.SH `BRIDGE:CALL`
.PP
Purpose: Internal RPC bridge to invoke PHP methods from Polyglot clients
.PP
.SH SYNOPSIS
php spp.php bridge:call [OPTIONS]
.PP
.SH OPTIONS AVAILABLE
No static options detected for this command.
.PP
.SH UNDER THE HOOD ACTIVITY
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: \ReflectionMethod.
.br
.PP
.PP
