.TH SPP-make-eventhand 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:eventhand
.PP
 \- Create a new Event Handler class
.SH DESCRIPTION
Create a new Event Handler class
.PP
.SH SYNOPSIS
php spp.php make:eventhand [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php make:eventhand <HandlerClassName> [--app=appname]
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes external system binaries or shell commands.
.br
\(bu Instantiates internal components: Event.
.br
.PP
.PP
