.TH SPP-ext-disable 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-ext-disable \- Disable a specific extension
.SH SYNOPSIS
.B php spp.php ext:disable
[OPTIONS]
.SH DESCRIPTION
Disable a specific extension
.PP
Usage: php spp.php ext:disable <extension_name>
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
