.TH SPP-make-go-service 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-go-service \- Create a new Go service script
.SH SYNOPSIS
.B php spp.php make:go-service
[OPTIONS]
.SH DESCRIPTION
Create a new Go service script
.PP
Usage: spp make:go-service <name> [--app=context]
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: Go.
.br
