.TH SPP-test-run 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
test:run
.PP
 \- Runs Parikshak evaluation for an entity or the whole suite
.SH DESCRIPTION
Runs Parikshak evaluation for an entity or the whole suite
.PP
.SH SYNOPSIS
php spp.php test:run [OPTIONS]
.PP
.SH OPTIONS
\(bu `--coverage` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Dynamically loads SPP kernel modules: parikshak.
.br
\(bu Bootstraps a full application execution context via Scheduler.
.br
\(bu Instantiates internal components: \SPPMod\Parikshak\Parikshak.
.br
.PP
.PP
