.TH SPP-make-perl-service 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-perl-service \- Create a new Perl service script
.SH SYNOPSIS
.B php spp.php make:perl-service
[OPTIONS]
.SH DESCRIPTION
Create a new Perl service script
.PP
Usage: spp make:perl-service <name> [--app=context]
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: Perl.
.br
