.TH SPP-make-twig 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:twig
.PP
 \- Scaffold a new Twig template (Drishyam Paradigm)
.SH DESCRIPTION
Scaffold a new Twig template (Drishyam Paradigm)
.PP
.SH SYNOPSIS
php spp.php make:twig [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php make:twig <ViewName>
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
\(bu Instantiates internal components: Drishyam, Twig.
.br
.PP
.PP
