.TH SPP-serve 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
serve
.PP
 \- Start a local development server for the current application
.SH DESCRIPTION
Start a local development server for the current application
.PP
.SH SYNOPSIS
php spp.php serve [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes external system binaries or shell commands.
.br
.PP
.PP
