.TH SPP-sys-upgrade 1 "23 June 2026" "SPP Framework" "SPP CLI Manual"
.SH `SYS:UPGRADE`
.PP
Purpose: Synchronize the database schema incrementally from all active module definitions (db.yml)
.PP
.SH SYNOPSIS
php spp.php sys:upgrade [OPTIONS]
.PP
.SH OPTIONS AVAILABLE
No static options detected for this command.
.PP
.SH UNDER THE HOOD ACTIVITY
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: SPPDB.
.br
.PP
.PP
