.TH SPP-make-controller 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-controller \- Create a new controller class
.SH SYNOPSIS
.B php spp.php make:controller
[OPTIONS]
.SH DESCRIPTION
Create a new controller class
.PP
Usage: php spp.php make:controller <name> [--app=appname] [--resource]
.br

.PP
.SH OPTIONS
.TP
.B --resource
Boolean flag. Extracted via static analysis from MakeControllerCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: controller.
.br
