.TH SPP-make-live-component 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-live-component \- Create a new Live Component class
.SH SYNOPSIS
.B php spp.php make:live-component
[OPTIONS]
.SH DESCRIPTION
Create a new Live Component class
.PP
Usage: php spp.php make:live-component <name> [--app=appname]
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: Live.
.br
