.TH SPP-make-command 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:command
.PP
 \- Create a new CLI command class
.SH DESCRIPTION
Create a new CLI command class
.PP
.SH SYNOPSIS
php spp.php make:command [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php make:command <name> [--app=appname] [--command=cmd:name]
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: CLI.
.br
.PP
.PP
