.TH SPP-mesh-add 1 "04 September 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-mesh-add \- Mounts a legacy application as a passthrough route in the WebOS Mesh
.SH SYNOPSIS
.B php spp.php mesh:add
[OPTIONS]
.SH DESCRIPTION
Mounts a legacy application as a passthrough route in the WebOS Mesh
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Performs raw filesystem modifications (create/write/delete).
.br
