.TH SPP-module-setting-list 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-module-setting-list \- List all settings for a given module
.SH SYNOPSIS
.B php spp.php module:setting:list
[OPTIONS]
.SH DESCRIPTION
List all settings for a given module
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
