.TH SPP-migrate-make 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
migrate:make
.PP
 \- Generate a new database migration class.
.SH DESCRIPTION
Generate a new database migration class.
.PP
.SH SYNOPSIS
php spp.php migrate:make [OPTIONS]
.PP
.SH OPTIONS
\(bu `--name=` : Expects a value. Extracted via static analysis.
.br
\(bu `--app=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
\(bu Instantiates internal components: database.
.br
.PP
.PP
