.TH SPP-make-command-test 1 "04 September 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-command-test \- Generate a boilerplate Parikshak feature test for a given command
.SH SYNOPSIS
.B php spp.php make:command-test
[OPTIONS]
.SH DESCRIPTION
Generate a boilerplate Parikshak feature test for a given command
.PP
Usage: php spp.php make:command-test <CommandName> [--app=appname]
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
