.TH SPP-lang-set 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
lang:set
.PP
 \- Set a translation for a key
.SH DESCRIPTION
Set a translation for a key
.PP
.SH SYNOPSIS
php spp.php lang:set [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php lang:set <key> <locale> <translation>
.PP
.PP
.SH OPTIONS
\(bu `--app=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Dynamically loads SPP kernel modules: spplang.
.br
\(bu Bootstraps a full application execution context via Scheduler.
.br
.PP
.PP
