.TH SPP-queue-work 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
queue:work
.PP
 \- Starts a worker loop to process background jobs from the queue.
.SH DESCRIPTION
Starts a worker loop to process background jobs from the queue.
.PP
.SH SYNOPSIS
php spp.php queue:work [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
