.TH SPP-i18n-import 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
i18n:import
.PP
 \- Import translations from a JSON file into the database.
.SH DESCRIPTION
Import translations from a JSON file into the database.
.PP
.SH SYNOPSIS
php spp.php i18n:import [OPTIONS]
.PP
.SH OPTIONS
\(bu `--locale=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: \SPPMod\SPPDB\SPPDB.
.br
.PP
.PP
