.TH SPP-api-key-generate 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
api:key:generate
.PP
 \- Generates a new permanent API Key.
.SH DESCRIPTION
Generates a new permanent API Key.
.PP
.SH SYNOPSIS
php spp.php api:key:generate [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: permanent, \SPPMod\SPPDB\SPPDB.
.br
.PP
.PP
