.TH SPP-docs-man 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
docs:man
.PP
 \- Documentation utilities (build, api, openapi, man, phpdoc).
.SH DESCRIPTION
Documentation utilities (build, api, openapi, man, phpdoc).
.PP
.SH SYNOPSIS
php spp.php docs:man [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
\(bu Executes external system binaries or shell commands.
.br
\(bu Instantiates internal components: \SPPMod\SPPDoc\SPPDocGenerator.
.br
.PP
.PP
