.TH SPP-view-cache 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
view:cache
.PP
 \- Pre-compiles all AST views into PHP for optimal performance
.SH DESCRIPTION
Pre-compiles all AST views into PHP for optimal performance
.PP
.SH SYNOPSIS
php spp.php view:cache [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: \RecursiveIteratorIterator, \RecursiveDirectoryIterator.
.br
.PP
.PP
