.TH SPP-kernel-compile 1 "04 September 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-kernel-compile \- Compiles the WebOS Kernel into the FastCGI performance cache.
.SH SYNOPSIS
.B php spp.php kernel:compile
[OPTIONS]
.SH DESCRIPTION
Compiles the WebOS Kernel into the FastCGI performance cache.
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
