.TH SPP-import-component 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
import:component
.PP
 \- Imports pristine air-gapped sovereign UI components
.SH DESCRIPTION
Imports pristine air-gapped sovereign UI components
.PP
.SH SYNOPSIS
php spp.php import:component [OPTIONS]
.PP
.SH OPTIONS
\(bu `--target=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
