.TH SPP-lekhak-generate-docs 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-lekhak-generate-docs \- Generates documentation nodes for SPP Core and Modules.
.SH SYNOPSIS
.B php spp.php lekhak:generate-docs
[OPTIONS]
.SH DESCRIPTION
Generates documentation nodes for SPP Core and Modules.
