.TH SPP-man-generate 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
man:generate
.PP
 \- Generate highly detailed man-pages in Markdown and UNIX roff formats
.SH DESCRIPTION
Generate highly detailed man-pages in Markdown and UNIX roff formats
.PP
.SH SYNOPSIS
php spp.php man:generate [OPTIONS]
.PP
.SH OPTIONS
\(bu `--force` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Performs direct filesystem modifications (create/write/delete).
.br
\(bu Instantiates internal components: \ReflectionClass.
.br
\(bu Makes outbound HTTP requests to external APIs or services.
.br
\(bu Interacts with the application cache layer (Redis/Memcached).
.br
.PP
.PP
