.TH SPP-config-sync 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
config:sync
.PP
 \- Synchronize framework configurations (e.g. workflows, dynamic fields) to DB schemas or system registries
.SH DESCRIPTION
Synchronize framework configurations (e.g. workflows, dynamic fields) to DB schemas or system registries
.PP
.SH SYNOPSIS
php spp.php config:sync [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Executes external system binaries or shell commands.
.br
\(bu Instantiates internal components: \SPPMod\SPPDB\SPPDB.
.br
.PP
.PP
