.TH SPP-session-destroy-all 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
session:destroy-all
.PP
 \- Invalidate all active sessions across the application
.SH DESCRIPTION
Invalidate all active sessions across the application
.PP
.SH SYNOPSIS
php spp.php session:destroy-all [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
