.TH SPP-dbsettings-import 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-dbsettings-import \- Import SPP module DB settings from JSON
.SH SYNOPSIS
.B php spp.php dbsettings:import
[OPTIONS]
.SH DESCRIPTION
Import SPP module DB settings from JSON
.PP
Usage: php spp.php dbsettings:import --file=settings.json [--app=<app_name>]
.br

.PP
.SH OPTIONS
.TP
.B --file=
Expects a value. Extracted via static analysis from DBSettingsImportCommand.php
.TP
.B --app=
Expects a value. Extracted via static analysis from DBSettingsImportCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Bootstraps a full application execution context (Scheduler::withContext).
.br
