.TH SPP-make-form 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-form \- Create a new SPP form definition
.SH SYNOPSIS
.B php spp.php make:form
[OPTIONS]
.SH DESCRIPTION
Create a new SPP form definition
.PP
Usage: php spp.php make:form <name> [--app=appname]
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: SPP.
.br
