.TH SPP-diff-history 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
diff:history
.PP
 \- View revision history of an entity
.SH DESCRIPTION
View revision history of an entity
.PP
.SH SYNOPSIS
php spp.php diff:history [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php diff:history --type=<ModelClass> --id=<ID> [--json]
.PP
.PP
.SH OPTIONS
\(bu `--type=` : Expects a value. Extracted via static analysis.
.br
\(bu `--id=` : Expects a value. Extracted via static analysis.
.br
\(bu `--json` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
