.TH SPP-diff-history 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-diff-history \- View revision history of an entity
.SH SYNOPSIS
.B php spp.php diff:history
[OPTIONS]
.SH DESCRIPTION
View revision history of an entity
.PP
Usage: php spp.php diff:history --type=<ModelClass> --id=<ID>
.br

.PP
.SH OPTIONS
.TP
.B --type=
Expects a value. Extracted via static analysis from DiffHistoryCommand.php
.TP
.B --id=
Expects a value. Extracted via static analysis from DiffHistoryCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
