.TH SPP-dbsettings-export 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
dbsettings:export
.PP
 \- Export SPP module DB settings to JSON
.SH DESCRIPTION
Export SPP module DB settings to JSON
.PP
.SH SYNOPSIS
php spp.php dbsettings:export [OPTIONS]
.PP
.SH OPTIONS
\(bu `--app=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Bootstraps a full application execution context via Scheduler.
.br
.PP
.PP
