.TH SPP-make-python-service 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:python-service
.PP
 \- Create a new Python service script
.SH DESCRIPTION
Create a new Python service script
.PP
.SH SYNOPSIS
php spp.php make:python-service [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: spp make:python-service <name> [--app=context]
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: Python.
.br
.PP
.PP
