.TH SPP-config-import 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-config-import \- Import database tables and settings from an exported SQL, SQLite, or XDB file
.SH SYNOPSIS
.B php spp.php config:import
[OPTIONS]
.SH DESCRIPTION
Import database tables and settings from an exported SQL, SQLite, or XDB file
