.TH SPP-interdb-mapping-list 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-interdb-mapping-list \- List all InterDB mappings
.SH SYNOPSIS
.B php spp.php interdb:mapping:list
[OPTIONS]
.SH DESCRIPTION
List all InterDB mappings
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
