.TH SPP-db-verify 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
db:verify
.PP
 \- Runs the SPP XDB MySQL Compatibility Verification Suite
.SH DESCRIPTION
Runs the SPP XDB MySQL Compatibility Verification Suite
.PP
.SH SYNOPSIS
php spp.php db:verify [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes external system binaries or shell commands.
.br
.PP
.PP
