.TH SPP-make-view 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-view \- Create a new view definition (equivalent to Drupal Views).
.SH SYNOPSIS
.B php spp.php make:view
[OPTIONS]
.SH DESCRIPTION
Create a new view definition (equivalent to Drupal Views).
.PP
.SH OPTIONS
.TP
.B --table=
Expects a value. Extracted via static analysis from MakeViewCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Interacts with the SPP database layer directly.
.br
\(bu Instantiates key components: view, \SPPMod\SPPDB\SPPDB.
.br
