.TH SPP-admin-iam 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
admin:iam
.PP
 \- Manage Admin IAM operations. Usage: admin:iam <action> [--payload=...] [--json]
.SH DESCRIPTION
Manage Admin IAM operations. Usage: admin:iam <action> [--payload=...] [--json]
.PP
.SH SYNOPSIS
php spp.php admin:iam [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Performs direct filesystem modifications (create/write/delete).
.br
\(bu Instantiates internal components: \SPPMod\SPPDB\SPPDB, \SPPMod\SPPAuth\SPPGroup, secret.
.br
.PP
.PP
