.TH SPP-make-ux-component 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-ux-component \- Scaffold a new SPP-UX reactive component
.SH SYNOPSIS
.B php spp.php make:ux-component
[OPTIONS]
.SH DESCRIPTION
Scaffold a new SPP-UX reactive component
.PP
Usage: php spp.php make:ux-component <ComponentName> [--template=external]
.br

.PP
.SH OPTIONS
.TP
.B --template=external
Boolean flag. Extracted via static analysis from MakeUXComponentCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Performs raw filesystem modifications (create/write/delete).
.br
\(bu Instantiates key components: reactive, SPP.
.br
