.TH SPP-env-get 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
env:get
.PP
 \- Get a specific configuration variable
.SH DESCRIPTION
Get a specific configuration variable
.PP
.SH SYNOPSIS
php spp.php env:get [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php env:get <key> [--app=appname]
.PP
.PP
.SH OPTIONS
\(bu `--app=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Bootstraps a full application execution context via Scheduler.
.br
.PP
.PP
