.TH SPP-make-deployment 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:deployment
.PP
 \- Generate Enterprise Docker and K8s scaffolding for the application.
.SH DESCRIPTION
Generate Enterprise Docker and K8s scaffolding for the application.
.PP
.SH SYNOPSIS
php spp.php make:deployment [OPTIONS]
.PP
.SH OPTIONS
\(bu `--with-redis` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
