.TH SPP-make-event 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-event \- Create a new event entry and scaffold its handler
.SH SYNOPSIS
.B php spp.php make:event
[OPTIONS]
.SH DESCRIPTION
Create a new event entry and scaffold its handler
.PP
Usage: php spp.php make:event <EventName> <HandlerClassName> [--app=appname] [--overridable] [--default-handler]
.br

.PP
.SH OPTIONS
.TP
.B --overridable
Boolean flag. Extracted via static analysis from MakeEventCommand.php
.TP
.B --default-handler
Boolean flag. Extracted via static analysis from MakeEventCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Performs raw filesystem modifications (create/write/delete).
.br
\(bu Executes external system binaries or shell commands.
.br
\(bu Instantiates key components: event.
.br
