.TH SPP-make-form 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:form
.PP
 \- Create a new SPP form definition
.SH DESCRIPTION
Create a new SPP form definition
.PP
.SH SYNOPSIS
php spp.php make:form [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php make:form <name> [--app=appname]
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: SPP.
.br
.PP
.PP
