.TH SPP-clear-cache 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
clear:cache
.PP
 \- Clear the application file/redis cache
.SH DESCRIPTION
Clear the application file/redis cache
.PP
.SH SYNOPSIS
php spp.php clear:cache [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Bootstraps a full application execution context via Scheduler.
.br
\(bu Interacts with the application cache layer (Redis/Memcached).
.br
.PP
.PP
