.TH SPP-clear-aicache 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
clear:aicache
.PP
 \- Clears the WebOS AI Decision cache.
.SH DESCRIPTION
Clears the WebOS AI Decision cache.
.PP
.SH SYNOPSIS
php spp.php clear:aicache [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
