.TH SPP-dev-core 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
dev:core
.PP
 \- Manage Dev Core operations. Usage: admin:core <action> [--payload=...] [--json]
.SH DESCRIPTION
Manage Dev Core operations. Usage: admin:core <action> [--payload=...] [--json]
.PP
.SH SYNOPSIS
php spp.php dev:core [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes external system binaries or shell commands.
.br
\(bu Instantiates internal components: \SPPMod\SPPDB\SPPDB, \SPP\EventParams.
.br
.PP
.PP
