.TH SPP-dev-adminrbac 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
dev:adminrbac
.PP
 \- Manage Dev AdminRBAC operations. Usage: dev:adminrbac <action> [--payload=...] [--json]
.SH DESCRIPTION
Manage Dev AdminRBAC operations. Usage: dev:adminrbac <action> [--payload=...] [--json]
.PP
.SH SYNOPSIS
php spp.php dev:adminrbac [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: \SPPMod\SPPXDB\SPP_XDB.
.br
.PP
.PP
