.TH SPP-site-install 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-site-install \- Initialize the database and load default configurations for a specific profile.
.SH SYNOPSIS
.B php spp.php site:install
[OPTIONS]
.SH DESCRIPTION
Initialize the database and load default configurations for a specific profile.
