.TH SPP-make-polyglot 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:polyglot
.PP
 \- Scaffold a new polyglot service (e.g. php spp.php make:polyglot python MyService)
.SH DESCRIPTION
Scaffold a new polyglot service (e.g. php spp.php make:polyglot python MyService)
.PP
.SH SYNOPSIS
php spp.php make:polyglot [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: spp make:polyglot <language> <service_name> [--app=context]
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: polyglot.
.br
.PP
.PP
