.TH SPP-make-scaffold 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:scaffold
.PP
 \- Create a full stack scaffold (Entity, DB, Controller, View)
.SH DESCRIPTION
Create a full stack scaffold (Entity, DB, Controller, View)
.PP
.SH SYNOPSIS
php spp.php make:scaffold [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
