.TH SPP-bridge-call 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
bridge:call
.PP
 \- Internal RPC bridge to invoke PHP methods from Polyglot clients
.SH DESCRIPTION
Internal RPC bridge to invoke PHP methods from Polyglot clients
.PP
.SH SYNOPSIS
php spp.php bridge:call [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: \ReflectionMethod.
.br
.PP
.PP
