.TH SPP-xdb-describe 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-xdb-describe \- Describe the schema of an XDB table
.SH SYNOPSIS
.B php spp.php xdb:describe
[OPTIONS]
.SH DESCRIPTION
Describe the schema of an XDB table
.PP
Usage: php spp xdb:describe <table_name> [--db=dbname]
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: \SPPMod\SPPXDB\SPP_XDB.
.br
