.TH SPP-make-blade-project 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-blade-project \- Scaffold a new Blade-enabled SPP application
.SH SYNOPSIS
.B php spp.php make:blade-project
[OPTIONS]
.SH DESCRIPTION
Scaffold a new Blade-enabled SPP application
.PP
Usage: php spp.php make:blade-project <app_name>
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Performs raw filesystem modifications (create/write/delete).
.br
\(bu Instantiates key components: Blade, SPP, app.
.br
