.TH SPP-xdb-make-seeder 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-xdb-make-seeder \- Create a new SPP_XDB seeder file
.SH SYNOPSIS
.B php spp.php xdb:make:seeder
[OPTIONS]
.SH DESCRIPTION
Create a new SPP_XDB seeder file
.PP
Usage: php spp.php xdb:make:seeder <name_of_seeder>
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: SPP_XDB, SeederManager.
.br
