.TH SPP-admin-audit 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
admin:audit
.PP
 \- Manage Admin Audit operations. Usage: admin:audit <action> [--payload=...] [--json]
.SH DESCRIPTION
Manage Admin Audit operations. Usage: admin:audit <action> [--payload=...] [--json]
.PP
.SH SYNOPSIS
php spp.php admin:audit [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: \SPPMod\SPPDB\SPPDB.
.br
.PP
.PP
