.TH SPP-app-set-base 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
app:set-base
.PP
 \- Set an application as the primary/base application
.SH DESCRIPTION
Set an application as the primary/base application
.PP
.SH SYNOPSIS
php spp.php app:set-base [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php app:set-base <app_name>
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
