.TH SPP-userprofile-schema-update 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-userprofile-schema-update \- Sync extended user profile metadata schemas
.SH SYNOPSIS
.B php spp.php userprofile:schema:update
[OPTIONS]
.SH DESCRIPTION
Sync extended user profile metadata schemas
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
