.TH SPP-dev-routing 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
dev:routing
.PP
 \- Manage Dev Routing operations. Usage: admin:routing <action> [--payload=...] [--json]
.SH DESCRIPTION
Manage Dev Routing operations. Usage: admin:routing <action> [--payload=...] [--json]
.PP
.SH SYNOPSIS
php spp.php dev:routing [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Bootstraps a full application execution context via Scheduler.
.br
.PP
.PP
