.TH SPP-make-controller 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:controller
.PP
 \- Create a new controller class
.SH DESCRIPTION
Create a new controller class
.PP
.SH SYNOPSIS
php spp.php make:controller [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php make:controller <name> [--app=appname] [--resource]
.PP
.PP
.SH OPTIONS
\(bu `--resource` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: controller.
.br
.PP
.PP
