.TH SPP-polyglot-worker 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
polyglot:worker
.PP
 \- Manage Polyglot persistent workers
.SH DESCRIPTION
Manage Polyglot persistent workers
.PP
.SH SYNOPSIS
php spp.php polyglot:worker [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: spp polyglot:worker [start|stop|restart|status] <module> [<lang>]
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
\(bu Executes external system binaries or shell commands.
.br
.PP
.PP
