.TH SPP-admin-general 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
admin:general
.PP
 \- Manage Admin General operations. Usage: admin:general <action> [--payload=...] [--json]
.SH DESCRIPTION
Manage Admin General operations. Usage: admin:general <action> [--payload=...] [--json]
.PP
.SH SYNOPSIS
php spp.php admin:general [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: \SPPMod\SPPAPI\LiveAction.
.br
.PP
.PP
