.TH SPP-lekhak-generate-docs 1 "23 June 2026" "SPP Framework" "SPP CLI Manual"
.SH `LEKHAK:GENERATE-DOCS`
.PP
Purpose: Generates documentation nodes for SPP Core and Modules.
.PP
.SH SYNOPSIS
php spp.php lekhak:generate-docs [OPTIONS]
.PP
.SH OPTIONS AVAILABLE
No static options detected for this command.
.PP
.SH UNDER THE HOOD ACTIVITY
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: DocGen, LekhakNode.
.br
.PP
.PP
