.TH SPP-mesh-remove 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
mesh:remove
.PP
 \- Unmounts a legacy application from the WebOS Mesh
.SH DESCRIPTION
Unmounts a legacy application from the WebOS Mesh
.PP
.SH SYNOPSIS
php spp.php mesh:remove [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
