.TH SPP-make-view 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:view
.PP
 \- Create a new view definition (equivalent to Drupal Views).
.SH DESCRIPTION
Create a new view definition (equivalent to Drupal Views).
.PP
.SH SYNOPSIS
php spp.php make:view [OPTIONS]
.PP
.SH OPTIONS
\(bu `--table=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: view, \SPPMod\SPPDB\SPPDB.
.br
.PP
.PP
