.TH SPP-man 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
man
.PP
 \- Format and display manual pages for SPP commands
.SH DESCRIPTION
Format and display manual pages for SPP commands
.PP
.SH SYNOPSIS
php spp.php man [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: elements.
.br
.PP
.PP
