.TH SPP-module-enable 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-module-enable \- Enable an SPP module
.SH SYNOPSIS
.B php spp.php module:enable
[OPTIONS]
.SH DESCRIPTION
Enable an SPP module
.PP
Usage: php spp.php module:enable <modulename>
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
