.TH SPP-view-cache 1 "23 June 2026" "SPP Framework" "SPP CLI Manual"
.SH `VIEW:CACHE`
.PP
Purpose: Pre-compiles all AST views into PHP for optimal performance
.PP
.SH SYNOPSIS
php spp.php view:cache [OPTIONS]
.PP
.SH OPTIONS AVAILABLE
No static options detected for this command.
.PP
.SH UNDER THE HOOD ACTIVITY
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: \RecursiveIteratorIterator, \RecursiveDirectoryIterator.
.br
.PP
.PP
