.TH SPP-group-edit 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-group-edit \- Edit an existing shared resource group
.SH SYNOPSIS
.B php spp.php group:edit
[OPTIONS]
.SH DESCRIPTION
Edit an existing shared resource group
.PP
Usage: php spp.php group:edit <group_name> [--extends=...] [--prefix=...]
.br

.PP
.SH OPTIONS
.TP
.B --extends=
Expects a value. Extracted via static analysis from GroupEditCommand.php
.TP
.B --prefix=
Expects a value. Extracted via static analysis from GroupEditCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Performs raw filesystem modifications (create/write/delete).
.br
