.TH SPP-view-service-test 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-view-service-test \- Test an AJAX service endpoint from the CLI
.SH SYNOPSIS
.B php spp.php view:service:test
[OPTIONS]
.SH DESCRIPTION
Usage: php spp.php view:service:test --name=<service> [--app=default] [--payload=
