.TH SPP-db-sync 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
db:sync
.PP
 \- Synchronize data between two database adapters (e.g. MySQL to XDB)
.SH DESCRIPTION
Synchronize data between two database adapters (e.g. MySQL to XDB)
.PP
.SH SYNOPSIS
php spp.php db:sync [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php db:sync --from=[engine:table] --to=[engine:table]
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: SPPDB.
.br
.PP
.PP
