.TH SPP-module-setting-update 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-module-setting-update \- Update a configuration setting for a specific module
.SH SYNOPSIS
.B php spp.php module:setting:update
[OPTIONS]
.SH DESCRIPTION
Update a configuration setting for a specific module
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Executes native PHP logic without major side-effects or external dependencies.
.br
