.TH SPP-view-service-add 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-view-service-add \- Register a new AJAX service endpoint
.SH SYNOPSIS
.B php spp.php view:service:add
[OPTIONS]
.SH DESCRIPTION
Usage: php spp.php view:service:add --name=<service> --script=<path> [--method=POST] [--app=default] [--source=yaml|db]
