.TH SPP-view-page-list 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
view:page:list
.PP
 \- List all registered pages/routes for an app
.SH DESCRIPTION
List all registered pages/routes for an app
.PP
.SH SYNOPSIS
php spp.php view:page:list [OPTIONS]
.PP
.SH OPTIONS
\(bu `--app=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Bootstraps a full application execution context via Scheduler.
.br
.PP
.PP
