.TH SPP-lekhak-generate-docs 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
lekhak:generate-docs
.PP
 \- Generates documentation nodes for SPP Core and Modules.
.SH DESCRIPTION
Generates documentation nodes for SPP Core and Modules.
.PP
.SH SYNOPSIS
php spp.php lekhak:generate-docs [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: DocGen, LekhakNode.
.br
.PP
.PP
