.TH SPP-dev-xdb 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
dev:xdb
.PP
 \- Manage Dev XDB operations. Usage: admin:xdb <action> [--payload=...] [--json]
.SH DESCRIPTION
Manage Dev XDB operations. Usage: admin:xdb <action> [--payload=...] [--json]
.PP
.SH SYNOPSIS
php spp.php dev:xdb [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: \SPPMod\SPPXDB\SPP_XDB, \SPPMod\SPPXDB\MigrationManager, \SPPMod\SPPXDB\SeederManager.
.br
.PP
.PP
