.TH SPP-make-deployment 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-deployment \- Generate Enterprise Docker and K8s scaffolding for the application.
.SH SYNOPSIS
.B php spp.php make:deployment
[OPTIONS]
.SH DESCRIPTION
Generate Enterprise Docker and K8s scaffolding for the application.
.PP
.SH OPTIONS
.TP
.B --with-redis
Boolean flag. Extracted via static analysis from MakeDeploymentCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Performs raw filesystem modifications (create/write/delete).
.br
