.TH SPP-polyglot-list 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-polyglot-list \- Discovers and tabulates all registered polyglot services
.SH SYNOPSIS
.B php spp.php polyglot:list
[OPTIONS]
.SH DESCRIPTION
Discovers and tabulates all registered polyglot services
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: \RecursiveIteratorIterator, \RecursiveDirectoryIterator.
.br
