.TH SPP-make-go-service 1 "23 June 2026" "SPP Framework" "SPP CLI Manual"
.SH `MAKE:GO-SERVICE`
.PP
Purpose: Create a new Go service script
.PP
.SH SYNOPSIS
php spp.php make:go-service [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: spp make:go-service <name> [--app=context]
.PP
.PP
.SH OPTIONS AVAILABLE
No static options detected for this command.
.PP
.SH UNDER THE HOOD ACTIVITY
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: Go.
.br
.PP
.PP
