.TH SPP-group-create 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-group-create \- Create a new shared resource group
.SH SYNOPSIS
.B php spp.php group:create
[OPTIONS]
.SH DESCRIPTION
Create a new shared resource group
.PP
Usage: php spp.php group:create <group_name> [--extends=core] [--prefix=...]
.br

.PP
.SH OPTIONS
.TP
.B --extends=
Expects a value. Extracted via static analysis from GroupCreateCommand.php
.TP
.B --prefix=
Expects a value. Extracted via static analysis from GroupCreateCommand.php
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Performs raw filesystem modifications (create/write/delete).
.br
\(bu Instantiates key components: shared.
.br
