.TH SPP-interdb-config 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
interdb:config
.PP
 \- Get or set the interdb operating mode
.SH DESCRIPTION
Get or set the interdb operating mode
.PP
.SH SYNOPSIS
php spp.php interdb:config [OPTIONS]
.PP
.SH OPTIONS
\(bu `--mappings` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
