.TH SPP-make-view 1 "23 June 2026" "SPP Framework" "SPP CLI Manual"
.SH `MAKE:VIEW`
.PP
Purpose: Create a new view definition (equivalent to Drupal Views).
.PP
.SH SYNOPSIS
php spp.php make:view [OPTIONS]
.PP
.SH OPTIONS AVAILABLE
\(bu `--table=` : Expects a value. Extracted via static analysis from MakeViewCommand.php.
.br
.PP
.SH UNDER THE HOOD ACTIVITY
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Interacts with the SPP relational database layer.
.br
\(bu Instantiates internal components: view, \SPPMod\SPPDB\SPPDB.
.br
.PP
.PP
