.TH SPP-dbsettings-import 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
dbsettings:import
.PP
 \- Import SPP module DB settings from JSON
.SH DESCRIPTION
Import SPP module DB settings from JSON
.PP
.SH SYNOPSIS
php spp.php dbsettings:import [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php dbsettings:import --file=settings.json [--app=<app_name>]
.PP
.PP
.SH OPTIONS
\(bu `--file=` : Expects a value. Extracted via static analysis.
.br
\(bu `--app=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Bootstraps a full application execution context via Scheduler.
.br
.PP
.PP
