.TH SPP-blade-clear 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
blade:clear
.PP
 \- Clear the compiled Blade view cache
.SH DESCRIPTION
Clear the compiled Blade view cache
.PP
.SH SYNOPSIS
php spp.php blade:clear [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
