.TH SPP-cache-compile-registry 1 "04 September 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-cache-compile-registry \- Rebuilds the Orion Cache and System Registry
.SH SYNOPSIS
.B php spp.php cache:compile-registry
[OPTIONS]
.SH DESCRIPTION
Rebuilds the Orion Cache and System Registry
.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: \SPP\EventParams.
.br
