.TH SPP-env-token-rotate 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
env:token:rotate
.PP
 \- Rotate the system deployment token
.SH DESCRIPTION
Rotate the system deployment token
.PP
.SH SYNOPSIS
php spp.php env:token:rotate [OPTIONS]
.PP
.SH OPTIONS
\(bu `--app=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Bootstraps a full application execution context via Scheduler.
.br
\(bu Instantiates internal components: \SPPMod\SPPXDB\SPP_XDB.
.br
.PP
.PP
