.TH SPP-xdb-seed 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
xdb:seed
.PP
 \- Run SPP_XDB Database Seeders
.SH DESCRIPTION
Run SPP_XDB Database Seeders
.PP
.SH SYNOPSIS
php spp.php xdb:seed [OPTIONS]
.PP
.SH OPTIONS
\(bu `--class=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: SPP_XDB, SeederManager.
.br
.PP
.PP
