.TH SPP-make-migration 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:migration
.PP
 \- Create a new database migration file
.SH DESCRIPTION
Create a new database migration file
.PP
.SH SYNOPSIS
php spp.php make:migration [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
\(bu Instantiates internal components: database.
.br
.PP
.PP
