.TH SPP- 1 "27 June 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp- \- Test SCIM User Provisioning locally
.SH SYNOPSIS
.B php spp.php 
[OPTIONS]
.SH DESCRIPTION
Test SCIM User Provisioning locally
.PP
Usage: php spp.php scim:test:user <username> [email]
.br

.PP
.SH OPTIONS
No explicit options statically detected.
.SH UNDER THE HOOD
Static analysis reveals the following runtime behaviors:
.PP
\(bu Instantiates key components: SCIMHandler, \ReflectionClass.
.br
