.TH SPP-ext-list 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
ext:list
.PP
 \- List all available and installed extensions
.SH DESCRIPTION
List all available and installed extensions
.PP
.SH SYNOPSIS
php spp.php ext:list [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
