.TH SPP-logger-clear 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
logger:clear
.PP
 \- Clear the SPP application logs
.SH DESCRIPTION
Clear the SPP application logs
.PP
.SH SYNOPSIS
php spp.php logger:clear [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
