.TH SPP-make-blade-scaffold 1 "31 May 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
spp-make-blade-scaffold \- Create a full stack Blade scaffold (Entity, YAML Form, Controller, Blade Views)
.SH SYNOPSIS
.B php spp.php make:blade-scaffold
[OPTIONS]
.SH DESCRIPTION
Create a full stack Blade scaffold (Entity, YAML Form, Controller, Blade Views)
