.TH SPP-group-list 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
group:list
.PP
 \- List all shared resource groups
.SH DESCRIPTION
List all shared resource groups
.PP
.SH SYNOPSIS
php spp.php group:list [OPTIONS]
.PP
.SH OPTIONS
\(bu `--entities` : Boolean flag or option. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
