.TH SPP-module-uninstall 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
module:uninstall
.PP
 \- Uninstall a module (drops tracking but retains data tables)
.SH DESCRIPTION
Uninstall a module (drops tracking but retains data tables)
.PP
.SH SYNOPSIS
php spp.php module:uninstall [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php module:uninstall <modulename>
.PP
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Executes native PHP logic without major side-effects.
.br
.PP
.PP
