.TH SPP-blade-view 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
blade:view
.PP
 \- Manage Blade views (list, create, delete)
.SH DESCRIPTION
Manage Blade views (list, create, delete)
.PP
.SH SYNOPSIS
php spp.php blade:view [OPTIONS]
.PP
.SH OPTIONS
No static options detected for this command.
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Performs direct filesystem modifications (create/write/delete).
.br
.PP
.PP
