.TH SPP-make-service 1 "19 July 2026" "SPP Framework" "SPP CLI Manual"
.SH NAME
make:service
.PP
 \- Create a new service class
.SH DESCRIPTION
Create a new service class
.PP
.SH SYNOPSIS
php spp.php make:service [OPTIONS]
.PP
.SH EXTENDED USAGE
Usage: php spp.php make:service <name> [--app=appname] [--lang=python]
.PP
.PP
.SH OPTIONS
\(bu `--lang=` : Expects a value. Extracted via static analysis.
.br
.PP
.SH UNDER THE HOOD
Based on static analysis of the command's source code, invoking this command performs the following operations:
\(bu Instantiates internal components: service, MakePythonCommand, MakeNodeCommand, MakeGoCommand, MakeDotNetCommand, MakePerlCommand, MakeJavaCommand.
.br
.PP
.PP
