<?php

namespace SPP\CLI\Commands;

/**
 * Class MakePolyglotPartialCommand
 * Scaffolds a new external polyglot partial service file (Python, Node.js, Go).
 */
class MakePolyglotPartialCommand extends BaseMakeCommand
{
    protected string $name = 'make:polyglot-partial';
    protected string $description = 'Scaffold a new external polyglot partial service file (Python/Node/Go)';

    
    public function isCLIOnly(): bool
    {
        return true;
    }

    public function execute(array $args): void
    {
        $name = null;
        $lang = null;
        
        foreach ($args as $i => $arg) {
            if (strpos(strtolower($arg), '--name=') === 0) {
                $name = substr($arg, 7);
            } elseif (strpos(strtolower($arg), '--lang=') === 0) {
                $lang = strtolower(substr($arg, 7));
            } elseif ($i === 0 && strpos($arg, '--') !== 0) {
                $name = $arg;
            }
        }

        if (!$name) {
            echo "Usage: php spp.php make:polyglot-partial <ModuleName.py|.js|.go> [--lang=python|node|go] [--app=AppName]\n";
            return;
        }

        $context = $this->getContext($args);
        $targetDir = $this->getTargetDir('services/polyglot', $context);
        
        $fileName = $name;
        $ext = strtolower(pathinfo($fileName, PATHINFO_EXTENSION));

        if (!$lang) {
            if ($ext === 'py') {
                $lang = 'python';
            } elseif ($ext === 'js') {
                $lang = 'node';
            } elseif ($ext === 'go') {
                $lang = 'go';
            } else {
                $lang = 'python';
                $fileName .= '.py';
                $ext = 'py';
            }
        } else {
            if ($lang === 'python' && $ext !== 'py') {
                $fileName .= '.py';
                $ext = 'py';
            } elseif ($lang === 'node' && $ext !== 'js') {
                $fileName .= '.js';
                $ext = 'js';
            } elseif ($lang === 'go' && $ext !== 'go') {
                $fileName .= '.go';
                $ext = 'go';
            }
        }
        
        $filePath = $targetDir . "/" . ltrim($fileName, '/\\');

        if (file_exists($filePath)) {
            echo "Error: Polyglot partial service {$name} already exists at {$filePath}.\n";
            return;
        }

        if ($lang === 'python') {
            $content = <<<'PARTIAL'
# External Polyglot View Partial Service: {{PARTIAL_NAME}}
# Context: {{CONTEXT}}
# Designed to be invoked via ViewController::renderPolyglotPartial or @polyglotpartial

import json

def render_partial(args=None):
    if args is None:
        args = {}
    
    title = args.get('title', '{{PARTIAL_NAME}}')
    user = args.get('user', 'Guest')
    
    html = f"""
    <div class="spp-partial-container polyglot python" id="polyglot-{title.lower()}">
        <div class="partial-header">
            <h4>{title} (Python Polyglot Service)</h4>
            <span class="badge badge-primary">{{CONTEXT}}</span>
        </div>
        <div class="partial-body">
            <p>Welcome, <strong>{user}</strong>! This partial markup was dynamically generated by a backend Python AI/Data service without inline HTML literals in PHP controllers.</p>
            <div class="metrics-box">
                <pre>{json.dumps(args, indent=2)}</pre>
            </div>
        </div>
    </div>
    """
    return html.strip()
PARTIAL;
        } elseif ($lang === 'node') {
            $content = <<<'PARTIAL'
/**
 * External Polyglot View Partial Service: {{PARTIAL_NAME}}
 * Context: {{CONTEXT}}
 * Designed to be invoked via ViewController::renderPolyglotPartial or @polyglotpartial
 */

function renderPartial(args = {}) {
    const title = args.title || '{{PARTIAL_NAME}}';
    const user = args.user || 'Guest';

    const html = `
    <div class="spp-partial-container polyglot node" id="polyglot-${title.toLowerCase()}">
        <div class="partial-header">
            <h4>${title} (Node.js Polyglot Service)</h4>
            <span class="badge badge-primary">{{CONTEXT}}</span>
        </div>
        <div class="partial-body">
            <p>Welcome, <strong>${user}</strong>! This partial markup was dynamically generated by a backend Node.js SSR service without inline HTML literals in PHP controllers.</p>
            <div class="metrics-box">
                <pre>${JSON.stringify(args, null, 2)}</pre>
            </div>
        </div>
    </div>
    `;
    return html.trim();
}

module.exports = { renderPartial };
PARTIAL;
        } else {
            $content = <<<'PARTIAL'
// External Polyglot View Partial Service: {{PARTIAL_NAME}}
// Context: {{CONTEXT}}
// Designed to be invoked via ViewController::renderPolyglotPartial or @polyglotpartial

package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

func RenderPartial(args map[string]interface{}) string {
	title := "{{PARTIAL_NAME}}"
	if t, ok := args["title"].(string); ok {
		title = t
	}
	user := "Guest"
	if u, ok := args["user"].(string); ok {
		user = u
	}

	argsJson, _ := json.MarshalIndent(args, "", "  ")

	html := fmt.Sprintf(`
    <div class="spp-partial-container polyglot go" id="polyglot-%s">
        <div class="partial-header">
            <h4>%s (Go Polyglot Service)</h4>
            <span class="badge badge-primary">{{CONTEXT}}</span>
        </div>
        <div class="partial-body">
            <p>Welcome, <strong>%s</strong>! This partial markup was dynamically generated by a backend Go microservice without inline HTML literals in PHP controllers.</p>
            <div class="metrics-box">
                <pre>%s</pre>
            </div>
        </div>
    </div>
    `, strings.ToLower(title), title, user, string(argsJson))

	return strings.TrimSpace(html)
}
PARTIAL;
        }

        $content = str_replace(
            ['{{PARTIAL_NAME}}', '{{CONTEXT}}'], 
            [basename($name, ".$ext"), $context], 
            $content
        );
        
        if (!is_dir(dirname($filePath))) {
            mkdir(dirname($filePath), 0777, true);
        }
        
        file_put_contents($filePath, $content);
        echo "Success: External polyglot partial service created at {$filePath}\n";
    }
}
