base_url: /lekhak
is_base_app: true
app_init: init.php
etc_path: etc
var_path: var
modules_path: modules
theme: eduxpro
lekhni:
    media_path: var/media/lekhni
admin_icon: 🖋️
admin_title: Lekhak

admin_menu:
  - { id: 'marketing', title: 'Marketing', icon: 'dY"' }
  - { id: 'commerce', title: 'Commerce', icon: 'dY>''' }
